### ISSUE TITLE
Android app crashing while capturing

### ISSUE THREAD

**Issue by PeterMead** [mapillary/mapillary_issues#724] opened 2015-02-24 12:55 UTC
I have the app set up and ready to go in my car before I head off then when I'm at an appropriate location I start capturing.  But it only captures 5 to 15 images before crashing.

I turned off "pause on stop" and tried it while parked in a car park and it took over a hundred pictures before I stopped it.  Then before I set off I started capturing again and it took at least 20 images before I started moving, then crashed after five images once I was moving.

**Comment by peterneubauer** [comment] 2015-02-24 20:16
E/AndroidRuntime( 9689): FATAL EXCEPTION: main

E/AndroidRuntime( 9689): java.lang.RuntimeException: startPreview failed

E/AndroidRuntime( 9689): 	at android.hardware.Camera.startPreview(Native Method)

E/AndroidRuntime( 9689): 	at app.mapillary.android.activity.CameraActivity$10.onPictureTaken(CameraActivity.java:597)

E/AndroidRuntime( 9689): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:692)

E/AndroidRuntime( 9689): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime( 9689): 	at android.os.Looper.loop(Looper.java:154)

E/AndroidRuntime( 9689): 	at android.app.ActivityThread.main(ActivityThread.java:4945)

E/AndroidRuntime( 9689): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 9689): 	at java.lang.reflect.Method.invoke(Method.java:511)

E/AndroidRuntime( 9689): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)

E/AndroidRuntime( 9689): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)

E/AndroidRuntime( 9689): 	at dalvik.system.NativeStart.main(Native Method)


Seems the camera API might be a bit shaky. Not sure what that comes from, looks like deeper down in the HW layers. Will try to add more debugging in the next versions. Thanks!

**Comment by PeterMead** [comment] 2015-03-18 10:23
I've tried it again on version 1.20 and it still crashed soon after starting capturing.

Most of the time it will just go back to the home screen of the app and I can go back into the camera and start capturing again for another few images.  But sometimes will not load the camera and suggest that I restart the phone.  After restarting it will work again (for a few images before crashing).

**Comment by PeterMead** [comment] 2015-07-30 08:47
I installed a custom Android 5.1 ROM and it now works.  Must be an issue with the stock Android 4.0 ROM.

**Comment by polarbearing** [comment] 2015-08-27 09:36
1.39 either crashes or freezes after taking some pictures. 

Comparing v.1.29, 1.35 and 1.39: Version 1.29 was the first I used where the phone was able to take pictures in 1-sec interval more or less fluently. Version 1.35 was a severe regression, the app froze after two pictures for quite a while. 

Version 1.39 is more fluent again, it takes 10-20 pictures in 1-sec interval, but then it freezes for about 10-30 seconds. Either it comes back with flashing: "Error: Method called after release()" (the last word not visible on screen), and continues, or it crashes after the freeze. The error is in the log, which I'll email Peter.

**Comment by polarbearing** [comment] 2015-09-13 18:51
1.42 does not freeze that long anymore, however it crashes more often than 1.39. 
I occasionally get "Error: takePicture failed", but not directly related to the crashes. 

On the other hand, "ERROR:  - Method called after release()" is in the log directly before crashes. 

Log is on the way.

**Comment by peterneubauer** [comment] 2015-09-14 11:24
Thanks,
will check!

/peter

**Comment by polarbearing** [comment] 2015-09-17 00:51
Today 1.42 was crashing rapidly, after taking a few pictures each. In one case, it created 3 empty sequence folders before writing an image into the 4th. Log on the way.

**Comment by polarbearing** [comment] 2015-09-27 18:56
1.43 still crashing, though the behaviour has changed a bit. 

Camera freezes for several seconds, shows a black screen for several seconds, and lands then in the 'Feed' menu. A small message says it cannot open the camera, but disappears soon. Pressing the green aperture icon leads back to the camera. Sequences often crash after very few shots.

Log on the way.

**Comment by polarbearing** [comment] 2015-11-06 12:23
Testing 1.47 and 1.52 with different settings for the capture rate, I had the following observations:

1.47, 0 sec setting: worked without crash for a longer sequence, however effective capture rate was around 4-6 sec between frames.
1.47, 1 sec setting: crashing after very few frames
1.52, 0 sec setting no longer possible
1.52, 1 sec setting: crashing after very few frames
1.52, 2 sec setting: worked without crash for a longer sequence, effective capture rate between 2-4 sec.

I'm trying to separate the log for the cases, which is a bit tricky since the capture setting is not written to the log. 

Thus with the 2sec setting in 1.52 the app is getting useful again, I just wonder if the seffective hooting rate could get closer to the 2 sec. Those "Queue/Executor size" and "executor pool size" values look always quite empty in the log.

**Comment by peterneubauer** [comment] 2015-11-22 18:28
Mmh,
how is it with v 1.59 and thumbnailing disabled?

**Comment by polarbearing** [comment] 2015-11-24 23:23
I was driving with 1.58, same behaviour as above (2 sec ok, 1 sec crashing), and 1.60, which shows a regression.

In 1.6.0, even in the 2 sec setting it was crashing after the first 1-4 images. Only in 3 sec it was shooting fluently. I had "Generate Thumbnails" off and was testing "Process images in background" on and off, no difference. 

There is a strange thing with the frequency setting itself. When you select the green writing, and e.g. it is set to 5 sec, the slider shows up with one less, thus 4 sec in this example. Observed since some 1.5x.

**Comment by HolgerJeromin** [comment] 2015-11-25 09:03
yes the frequency setting has a off by one error.

**Comment by HolgerJeromin** [comment] 2015-11-25 15:06
the frequency thing is reported as #1352

**Comment by polarbearing** [comment] 2015-11-25 18:52
Was downgrading to 1.59 today to see which version introduced the crash regression. Result was ambiguous. In the 2sec setting, it did not crash in the first 1-4 images, but did somewhere at 75, 15 or 5.

**Comment by polarbearing** [comment] 2015-11-26 09:46
Testing 1.61 this morning, 0 and 1 sec setting still unusable (crash within first 4 images), 2 sec is getting better again compared to 1.60. Longest sequence was 138 but also crashed eventually. Need to check the log for details later. 

Another observation I have for a while it that the app needs some "warmup", i.e. the frequency is slower for the first 20-30 images, as if the app has to squezze out other processes from memory.

**Comment by polarbearing** [comment] 2015-11-27 09:39
Testing 1.61 today with a 500 uninterrupted frames sequence n 2 sec setting, quite fluently. (All foggy, but that's not your fault). Setting to 1 sec crashed at first frame.

**Comment by peterneubauer** [comment] 2015-11-27 10:11
Yeah,
That's to be expected - you have an older Nexus S?

**Comment by polarbearing** [comment] 2015-11-27 10:13
All the same device, you know my logs.

**Comment by peterneubauer** [comment] 2015-12-01 13:33
Ok, I'm closing this issue, I have added a log-cleaning preference for easier reporting, and the other issues are very device-dependent and hard to debug (the native camera is not giving a lot of stack trace when it e.g. runs out of buffer or memory. Setting intervals too short is going to simply overload less capable devices.

**Closed by peterneubauer** 2015-12-01 13:33 UTC
Labels: android, bug
