### ISSUE TITLE
GPS lock very slow/not achieved across multiple Android phones

### ISSUE THREAD

**Issue by DaCor1** [mapillary/mapillary_issues#1700] opened 2016-02-14 12:44 UTC
Yesterday we went out with 2 virbs and several phones

- Samsung Galaxy Nexus
- HTC One M8
- Nexus 5 (Oscar)
- Samsung Galaxy S2

Every one of the phones, at several points during the day, had problems getting a GPS lock. 

This issue was isolated to the Mapillary app as testing with several other apps across all the phones showed no issues connecting e.g. Maps.me, Google maps, OSMand, various GPS test apps

**Comment by peterneubauer** [comment] 2016-02-14 13:21
@DaCor1 is it that the GPS indicator was red?

**Comment by DaCor1** [comment] 2016-02-14 13:45
Yes and no.

Firstly, indicator red for an extended period and either never makes a
connection or takes an extended length of time to get a lock.

Secondly, indicator turns green but app does not take any images

**Comment by HolgerJeromin** [comment] 2016-02-14 22:09
GPS icon green, debug info says we have an fix, but taking images says "waiting for a better fix" is an issue which has an entry here already.  #1655
It hits my phone with changing apps. 
For me leaving camera and reentering works. Other people have to leave the whole app.

**Comment by echeloni2p** [comment] 2016-02-15 10:10
Hi!

Got this, too. Sent already tracelogs to mapillary.
It hels to kill the mapillary app and restart it.
Sometimes only restarting the mobile helps.

echelon

**Comment by domdomegg** [comment] 2016-02-28 19:29
Same problem here, on a S2 (which had temperamental GPS, but Mapillary is especially bad), and a S6 (which has flawless GPS, usually accurate to ~5m on a cloudy-ish day, but shows up red/yellow on Mapillary)

**Comment by domdomegg** [comment] 2016-02-28 19:32
May be related:
http://forum.mapillary.io/t/android-mapillary-app-refuse-taking-pictures-bad-gps/335

**Comment by rsahlin** [comment] 2016-03-05 10:34
Hi, My name is Richard Sahlin and I will be taking over development of the Mapillary Android app.

This issue seems to be 2 separate issues 
- one that is duplicate of #1655 - which is fixed in the 1.77 Beta release.
- the other seems to be about bad GPS precision

Could you please check if 1.77 solves your problems?
- If you are not in the Beta program you can download it from https://www.mapillary.com/using.html - scroll down to 'Direct Android .apk link'

For the time being I would like to close this issue, if the location fix problem still persists please re-open #1655.
If you still feel that we should investigate the  (non google play services) GPS location accuracy then please open a new issue for that.

Thanks for your support!
Best regards
/Richard

**Closed by rsahlin** 2016-03-05 10:34 UTC
Labels: android, bug
