### ISSUE TITLE
Detection of license plate fails frequently

### ISSUE THREAD

**Issue by ray66** [mapillary/mapillary_issues#2755] opened 2017-10-20 04:43 UTC
Blurring of license plates that are perfectly readable fails systematically when character size is below a certain size and/or the plate is not horizontal. This is very annoying as it obliges to go trough every recorded sequence to blur manually  in order to be compliant with local privacy legislation in many European countries. This consumes more time than the capturing itself.

Examples:

[example 1](https://www.mapillary.com/map/im/MpSXGtxs6LnrUX9nSvAzVg) None of the license plates of the four cars in the center have been blurred

[example 2](https://www.mapillary.com/map/im/cSVo9mu-OSnsZjeAQRK5ZQ) The plate of the white Audi on the left has not been detected.

**Comment by katrinhumal** [comment] 2017-10-20 14:53
Thanks for the examples @ray66! We're working on improving the detection algorithms to include more shapes and sizes of license plates. The improvements won't be seen instantly but as we gradually process everything with better algorithms, you will hopefully notice this. We really appreciate your work with manually fixing this! 

cc @ybkuang to check out the particular examples referred to here.

**Comment by ray66** [comment] 2017-10-25 08:33
Good to hear that you work on improving the blur detection algorithm. My main concern is to stress the importance of this issue. Currently on my captures **_none_** of the license blades that are 10 to 15 pixels high are detected. With the camera and resolution I use this corresponds to a distance of around 20 meters. In urban environment I get an average of one to two undetected plates per picture which makes manual blurring the most time consuming part of my workflow leaving less time for capturing and OSM editing. On the long term this either will put off contributors and/or create privacy issues.    

[Another example](https://www.mapillary.com/map/im/8_E3egcMKKuAWWCBLB0goQ)

BTW, detection of text on traffic signs seems to work much better than blur detection.

**Comment by GITNE** [comment] 2017-10-25 11:21
> My main concern is to stress the importance of this issue.

If I may chime in here, I totally agree with this too. Not because of my personal opinion or taste but for **legal** reasons. Continuous training of the blur algorithm really must be a top priority.

Having said that, I am not sure this takes place at Mapillary today because I did not seem to observe any improvement on new images lately. Of course, this is only my subjective observation which may or may not be true. The point is that virtually any European court will argue that the provider has do to everything possible in his power to comply with the law, and this is something the court would definitely check if any complaint would be brought into case. Automated *continuous training* of the blur algorithm based on improved training data from manual input is indeed possible and feasible today. So, a court will have a hard time believing any other explanation for not complying with the law in select instances.

This legal situation is comparable to the regulations which require website operators to remove illegal or *fake* (while its definition is still debatable) content or hate speech. It is clear and obvious that any operator of an open interactive forum like website cannot comply 100% in this regard with the law all the time. But, he/she must do everything what is feasible in his/her power to comply with the law, usually within 24 hours.

**Comment by katrinhumal** [comment] 2017-10-26 09:26
Thanks for the insights, everyone. This really sums up the main reasons for putting time and resources into our blur algorithms. I understand it doesn't always seem obvious that it's getting better but we'll keep striving in any case.

@ToeBee great minds think alike! ;) Considering the context of the detected license plate is exactly one of the things that we're developing that should help judge if it's really a license plate or, for example, a street sign instead.

**Comment by majkaz** [comment] 2017-11-18 15:38
There is another problem with license plate blurs - the blurs are detected at the standard European ratio - the long one. However, the second possible ratio for license plates (for example trucks, some American models of cars) which is more square, are not detected. Example of the license plate can be seen in [this photo](https://www.mapillary.com/map/im/1FVUdFgJzNoNNeWOcvBaCw).

**Comment by katrinhumal** [comment] 2017-11-20 12:40
@majkaz Totally right - this is also something that we'll be working on.

**Comment by nereocystis** [comment] 2018-01-05 04:33
Are the license plate blurs separated by country? I think that the blurs do not specify license plate or face.

Probably blurs should be separated by country, since US license plate have different dimensions than European license plates.

**Comment by katrinhumal** [comment] 2018-01-05 09:38
@nereocystis you are right and training different shapes from different countries is exactly what we are doing.

I'm closing this issue now since the "fix" is a longer process that is already in the works.

**Closed by katrinhumal** 2018-01-05 09:38 UTC

**Comment by nereocystis** [comment] 2018-01-08 19:29
@katrinhumal Closing the issue is a bit strange, since the issue has not been fixed. As a software developer, I prefer to leave an unfixed issue open, with a notice that the fix is not coming soon.

**Comment by katrinhumal** [comment] 2018-01-09 09:33
@nereocystis it's a very good point and we understand that, but have chosen another process for ourselves. I hope that's ok.
