### ISSUE TITLE
Video time in uploader counts backwards

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#982] opened 2015-05-03 17:59 UTC
When I upload a video using the video upload function and then play it, the video time counts _backwards_ and doesn't stop when the video is paused.

The video was converted, cutted and had its audio removed using avconv.

A sample file can be found here: https://www.dropbox.com/s/133squv385epx51/short.mp4?dl=0

I'm using Firefox on Ubuntu.

**Comment by ltog** [comment] 2015-05-04 05:04
I tested also with Windows 7:

- Firefox: Counts backwards (and keeps counting when paused) as described above.
- Chrome: Seems to be fine.

**Comment by grinapo** [comment] 2015-07-06 17:22
It indeed does. Completely unusable, apart from crashing e10s mode firefox 8 out of 10 times. (Crome stopping works but there the playback is pretty broken, that's a different issue.)

**Comment by Sergey82K** [comment] 2016-05-30 06:26
I have the some problem in Internet Explorer v11.0 and Google Crome v51.0. After I start play video the video time counts backwards and doesn't stop when the video is paused. 
In Maxthon 4.4.8 this bug absent, but I uploaded video 4 days ago and still no any results of video on map and I can not see any info about uploaded video in my profile.
How long video processing? Video is 2.5 minutes long.

Also, in Maxthon 4.4.8 photo upload freeze on 0%, and in Maxthon and Crome browser main map does not show - only white field.

**Comment by Sergey82K** [comment] 2016-05-30 06:26
I have the some problem in Internet Explorer v11.0 and Google Crome v51.0. After I start play video the video time counts backwards and doesn't stop when the video is paused. 
In Maxthon 4.4.8 this bug absent, but I uploaded video 4 days ago and still no any results of video on map and I can not see any info about uploaded video in my profile.
How long video processing? Video is 2.5 minutes long.

Also, in Maxthon 4.4.8 photo upload freeze on 0%, and in Maxthon and Crome browser main map does not show - only white field.

**Comment by Sergey82K** [comment] 2016-05-30 06:26
I have the some problem in Internet Explorer v11.0 and Google Crome v51.0. After I start play video the video time counts backwards and doesn't stop when the video is paused. 
In Maxthon 4.4.8 this bug absent, but I uploaded video 4 days ago and still no any results of video on map and I can not see any info about uploaded video in my profile.
How long video processing? Video is 2.5 minutes long.

Also, in Maxthon 4.4.8 photo upload freeze on 0%, and in Maxthon and Crome browser main map does not show - only white field.

**Comment by Sergey82K** [comment] 2016-05-30 06:27
I have the some problem in Internet Explorer v11.0 and Google Crome v51.0. After I start play video the video time counts backwards and doesn't stop when the video is paused. 
In Maxthon 4.4.8 this bug absent, but I uploaded video 4 days ago and still no any results of video on map and I can not see any info about uploaded video in my profile.
How long video processing? Video is 2.5 minutes long.

Also, in Maxthon 4.4.8 photo upload freeze on 0%, and in Maxthon and Crome browser main map does not show - only white field.

**Comment by paulinus** [comment] 2016-06-01 13:44
@Sergey82K did the video images finally appeared on your profile?

**Comment by Sergey82K** [comment] 2016-06-01 14:01
@paulinus, yes, I added video 27 May, and received notification about accept upload images (from video) only 30 May. 31 May I received mail about images OK.
I do not checked result on WEB because now I in working travel without PC.
Thanks!

**Comment by paulinus** [comment] 2016-06-01 14:27
That was slower than it should be, but happy to know that it worked.

I'm letting the issue opened to keep track of the original issue with the video player in the browsers. Support for videos in HTML5 is still unstable in many browsers.

**Comment by Sergey82K** [comment] 2016-06-17 19:11
@paulinus, I checked! My old uploaded videos is fully OK.
But I upload new video's near week ago and still no any notifications. No new video's in my profile :(
Can You add in profile info like as "video file ___ uploaded and wait for conversion"?
Thanks!

**Comment by paulinus** [comment] 2018-07-19 11:39
Closing this issue now that mapillary_issues is no longer an active repository and that the problem is related to an, now old, version of firefox.

**Closed by paulinus** 2018-07-19 11:39 UTC
Labels: affects-backend, affects-vision, affects-web-uploader, bug
