### ISSUE TITLE
Adjusting images in manual uploader results in out of sequence pictures

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#2291] opened 2016-10-04 16:27 UTC
### Basic information
- Platform: `Web`
- System/Browser: `Chromium` (probably v52 but not 100% sure - don't have laptop with me right now)
### Steps to reproduce behavior
1. Use the manual upload page at https://www.mapillary.com/app/uploader
2. Adjust the location of a few pictures before uploading
### Expected behavior

Pictures should remain in proper sequence after uploaded.
### Actual behavior

The pictures that had their location altered are pulled out of the sequence and appended to the end
### Example

There are several spots in this sequence that are out of order. For example, start at this picture:  
https://www.mapillary.com/app/?pKey=uEFEv4FUT_qYnVIKQXfVDg&focus=map
The next one **should** be: 
https://www.mapillary.com/app/?pKey=DwTbRy2WEBXBY8sOfebfKA&focus=map

Screenshot of the resulting sequence:
![image](https://cloud.githubusercontent.com/assets/348948/19082820/5a45bcc0-8a25-11e6-925d-471402367d65.png)

**Comment by GITNE** [comment] 2016-10-16 14:50
I have experienced a similar problem. Please have a look at sequence ```bE3Ur3XDvSpF9kvzgpX8sQ```. The last three photos have been improperly reordered. See here: https://www.mapillary.com/app/?pKey=QNG_r5F05HAWNe7bJzpnfQ
I have also repositioned the photos before hitting the upload button. Everything looked fine before upload. The reordering has only become noticeable after the sequence has been published.

Besides, I have also realized that the cool :sunglasses: groovy smooth Mapillary transitions are based on the original GPS data in the files instead on the “meta” sequence. Because of these two problems I am considering to delete and upload this sequence again.

**Comment by GITNE** [comment] 2016-10-16 14:59
> Besides, I have also realized that the cool :sunglasses: groovy smooth Mapillary transitions are based on the original GPS data in the files instead on the “meta” sequence.

Oh, and the navigation in space too! :worried:

**Comment by gyllen** [comment] 2016-10-17 20:01
@GITNE The cool groovy transitions :) are based on both the position and also a "3D reconstruction" of the area (correct me if I am wrong here @paulinus 

Not sure about the rewrite of the EXIF before upload (is this something you can take a look at @nickplesha )

**Comment by GITNE** [comment] 2016-10-18 18:46
Reordering is more severe than I have initially assumed. My next sequence ```CnBJy5B-Z9pQrs8lR4fZxg``` uploaded via the web uploader got reordered improperly: https://www.mapillary.com/app/?pKey=ospVD_Fw83OYW1DX4hZh5Q
This time, the first and fifth photo have been swapped. I have **not** touched the sequence before upload.

I suppose the backend is computing the GPS date time stamp incorrectly, probably the divisor portion of the seconds rational number is not applied correctly.

**Comment by gyllen** [comment] 2016-10-19 20:12
@nickplesha Can you try to repeat this bug?

**Comment by GITNE** [comment] 2016-10-20 09:43
Unfortunately, further sequences got reordered. :unamused:
https://www.mapillary.com/app?focus=map&pKey=uHk1ASnkkBL-coZGDqEbwA
https://www.mapillary.com/app?focus=map&pKey=A2s9X1Y-lrR8M1IJO-4xww

Can you put them into the correct order? Uploading these photos again is way too time consuming. This bug is very annoying. You should really fix this **asap** because it messes up the database and the navigation in space too.
BTW, I do not think the files themselves are the issue because all tools, including the web uploader handle them properly, it is only the backend that seems to create the problem.

**Comment by gyllen** [comment] 2016-10-22 19:18
@GITNE We are looking into this and tracking the bug. I might take a couple for us to get back to you though. Some big upgrades going on.

It looks to me that the order is right on the map though. So this might be some caching issue.

**Comment by GITNE** [comment] 2016-10-23 02:45
@gyllen Hmm, I do not see any cdn caching effects you are referring to, even after clearing the browser cache and reloading the page after days. Hence, I have deleted the first affected sequence and are going to upload it again. I would like to find out if this may be an issue with the uploading process because some sequences turn out fine after upload. Unfortunately, I will not be able to test if this bug is reproducible with this sequence because I do not have the uploaded files anymore. However, I still have the uploaded files of other disordered sequences, so I should be able to report later on those then.

**Comment by GITNE** [comment] 2016-10-23 16:53
@gyllen I have reuploaded the photos of sequence https://www.mapillary.com/app/?pKey=ospVD_Fw83OYW1DX4hZh5Q&focus=map. Fortunately, the new sequence has been ordered correctly. :smile: As I mentioned before, because the replacement sequence's photos are not bit identical this does not say anything about any possible cause that might have disrupted the correct order of the first sequence.

**Comment by GITNE** [comment] 2016-10-24 12:21
@gyllen @peterneubauer I have reuploaded sequence https://www.mapillary.com/app?focus=map&pKey=uHk1ASnkkBL-coZGDqEbwA with bit identical photos. The effects are reproducible and it is like I have assumed. The sequence gets disordered on the first photo that has a GPS time stamp with non-integer seconds, or in other words where it has a granularity of fractions of a second (the divisor is ```> 1```). This clearly shows that at some point the backend computes the GPS time stamp incorrectly. Should be easy to fix. :wink: Good luck!

**Comment by ybkuang** [comment] 2016-10-24 12:28
@GITNE @gyllen I've checked that this is a backend processing error. It is due to an error in the parsing datetime format with subsec in GPS Time. I will make a fix for it and reprocess the photos (so you don't need to upload again). This will take a few days. Sorry for the error and the delay.

**Comment by gyllen** [comment] 2016-10-25 01:38
@ybkuang Thanks for finding this, reassigning ticket.

**Comment by ToeBee** [comment] 2016-10-25 04:03
It seems like this issue has been sidetracked from its original problem?

**Comment by GITNE** [comment] 2016-10-25 08:54
@toebee This is what I get when I look at your sequence.
![map720p](https://cloud.githubusercontent.com/assets/15823872/19679181/1f5a6bd8-9aa1-11e6-87d5-3a6f92984430.png)
Hence, your problem has been resolved. It was a cdn caching issue indeed, so everything worked as designed for you so far. It is not pretty but correct. The next backend update will probably resolve the delay in cdn caching pretty much. So, please wait and enjoy. :wink:

But, you are correct, although my issue was is similar in effects it turned out to be unrelated to yours.

**Comment by ToeBee** [comment] 2016-10-25 17:26
No, my problem was not a caching issue. The sequence I uploaded and took a screenshot of was manually split up by someone at Mapillary to mask the problem on the map. Here are the split out parts that were originally all part of the long sequence:
* https://www.mapillary.com/app/?pKey=DwTbRy2WEBXBY8sOfebfKA
*  https://www.mapillary.com/app/?pKey=_IqLpFJjtEX5i7ZN6uOgEA
* https://www.mapillary.com/app/?pKey=x0e97pW-ERFQJL-IfGSljQ
* https://www.mapillary.com/app/?pKey=6J9oHeAU1IVomM3JNBn2iQ

**Comment by GITNE** [comment] 2016-10-25 22:43
>The sequence I uploaded and took a screenshot of was manually split up by someone at Mapillary to mask the problem on the map.

Okay, I did not know that.
@ToeBee Can you please download the original files and check the seconds component of the GPS time stamp field for fraction second values (I would have done it myself but I cannot because only owners of uploads can)? If you can, please examine also the photos that came before those you've mentioned in the original sequence. If either of these have fraction second values then we are talking about the same problem and it has nothing to do with adjusting or not adjusting photos in the uploader.

**Comment by ToeBee** [comment] 2016-10-25 23:08
These are from a GoPro Hero 4 camera which doesn't have GPS functionality. They were geotagged with the geotag_from_gpx script. There is no "GPS Time" field in the EXIF. All I see is: 
`Date/Time Original = 2016:09:17 22:25:12`
`Create Date = 2016:09:17 17:25:12`
`Modify Date = 2016:09:17 17:25:12`

So no fractional seconds anywhere.

**Comment by GITNE** [comment] 2016-10-26 10:43
> They were geotagged with the geotag_from_gpx script.


This is an important piece of information. However, I am still not convinced that the web uploader is the cause because it does not do very much. Particularly, it does not do anything to files and it is only the files that the backend works on. When it comes to building or ordering a sequence it is only the time stamp that matters. You cannot change that with the web uploader by any means. It is the backend that is responsible for the final sequence as it appears on the map.

Btw, I am a bit surprised that the `geotag_from_gpx` script puts the time stamp into the Date/Time Original (`0x9003`) field instead of the GPS date (`0x1D`) and time (`0x7`) fields. I have not used the script, so I cannot comment much on that. Well, I guess it is semantically correct, since the clock on the device that wrote the file may not have been synced to the GPS atomic clock. But then, there is the problem when reaching for the file system's time stamp because it may be time zone agnostic which unfortunately in many cases is, since many devices use FAT32 formatted SD/MMC cards or internal storage. Sadly, FAT32 is time zone agnostic. Well, but that's a topic of its own. :laughing:

**Comment by ToeBee** [comment] 2016-11-14 18:06
I think the camera sets the Date/Time Original. I don't think the script changes any time stamps.

However I have confirmed that this bug still exists in the web uploader. I uploaded a sequence last night while adjusting the location of a single image. That image was reordered to the end of the sequence.

Image [mA2S0QugR36JBA_iS](https://www.mapillary.com/app/?pKey=mA2S0QugR36JBA_iS) is at the end of the sequence when it should be immediately after [_WXshfTNysLpeKeBSOo3UQ](https://www.mapillary.com/app/?pKey=_WXshfTNysLpeKeBSOo3UQ)

**Comment by GITNE** [comment] 2016-11-14 19:49
> Image [mA2S0QugR36JBA_iS](https://www.mapillary.com/app/?pKey=mA2S0QugR36JBA_iS) is at the end of the sequence when it should be immediately after [_WXshfTNysLpeKeBSOo3UQ](https://www.mapillary.com/app/?pKey=_WXshfTNysLpeKeBSOo3UQ)

Unfortunately, I cannot access these photos on Mapillary just yet. And, it is hard to tell anything without looking at the original data. Can you upload the affected photos in *your* original source form, the form processed by the `geotag_from_gpx` script, and the Mapillary *original* form (you know, the one which only photo owners can download) to Github (or any other file sharing service)? That is, if you wish me to look at it. :wink: Thank you!

**Comment by ToeBee** [comment] 2016-11-14 20:35
Whoops. I seem to have made a mistake while copying the image URL of the first one so it shows up as a "not found" error.

Fixed links: [mA2S0QugR36JBA_iSlfmig](https://www.mapillary.com/app/?pKey=mA2S0QugR36JBA_iSlfmig) should be after [_WXshfTNysLpeKeBSOo3UQ](https://www.mapillary.com/app/?pKey=_WXshfTNysLpeKeBSOo3UQ)

I looked at the EXIF tags and I see what is going on. The web uploader is modifying the `Date/Time Original` field when you drag an image and there is a time zone discrepancy which ends up putting the modified picture at the end of the sequence.

After using the "Download unprocessed original" link on the 3 pictures that should be in sequence with each other I see the following time stamps:

    Image Description               : DCIM\100GOPRO\G0010998.JPG
    Date/Time Original              : 2016:11:12 11:15:26
    Image Description               : DCIM\100GOPRO\G0010999.JPG
    Date/Time Original              : 2016:11:12 17:15:28
    Image Description               : DCIM\100GOPRO\G0011000.JPG
    Date/Time Original              : 2016:11:12 11:15:30


I am in Central US time which is now 6 hours from UTC so this explains the 6 hour change.

It looks like this is similar to #2146 but with the Date/Time original instead of the orientation flag. Adjusting the location in the review screen should only modify the coordinate tags and leave everything else with its original values.

**Comment by GITNE** [comment] 2016-11-14 21:02
> After using the "Download unprocessed original" link on the 3 pictures that
> should be in sequence with each other I see the following time stamps:
> ```
> Image Description : DCIM\100GOPRO\G0010998.JPG
> Date/Time Original : 2016:11:12 11:15:26
> Image Description : DCIM\100GOPRO\G0010999.JPG
> Date/Time Original : 2016:11:12 17:15:28
> Image Description : DCIM\100GOPRO\G0011000.JPG
> Date/Time Original : 2016:11:12 11:15:30
> ```

Seems like you have found the culprit. Awesome! :+1: Can you validate this by deleting the sequence, setting the time zone of your browser's instance to UTC, and then modifying the location of these two affected photos in the web uploader before uploading again? This should produce a correctly ordered sequence after adjustment.

Since, the web uploader seems to be currently buggy, you may want to consider using [JOSM](https//josm.openstreetmap.de) with the [PhotoAdjust](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/PhotoAdjust) plug-in in the future. You do not need to learn mapping in JOSM to do that but the thing about these tools is that they work and produce correct results. Hence, you won't have to bother with the Mapillary web uploader, just hitting the ”Upload“ button should do the job for you.

> Adjusting the location in the review screen should only modify the coordinate
> tags and leave everything else with its original values.

You're absolutely right about this.

**Comment by gyllen** [comment] 2016-11-15 13:06
@GITNE I agree on this

**Comment by pkoby** [comment] 2016-12-09 17:08
I have encountered this issue myself. Just adding myself to the pile. I did modify the position of at least half the photos in the online manual uploader.

I was impressed to see that the timestamp matches what I expected (see https://github.com/mapillary/mapillary_issues/issues/2349), so at least my code works right. The thing is, I checked the timestamps in all the photos which were affected, and they all have the correct time in the EXIF tags. The timestamp that now shows up for the misordered photos is 5 hours too early, which does seem to correlate to the difference to UTC etc.

This is the affected sequence: https://www.mapillary.com/app/user/pkoby?lat=40.7963152136752&lng=-77.8624645806957&z=17&pKey=EC1F_tn8dcXryZSKYYlpRw

**Comment by peterneubauer** [comment] 2016-12-10 21:18
Thanks for the chiming in, we will check! We very soon have a reprocessing
pipeline from the the original down the line in place so we can deal with
this and things like changing rotation. Will investigate.

**Comment by GITNE** [comment] 2017-01-17 21:08
> @GITNE @gyllen I've checked that this is a backend processing error. It is
> due to an error in the parsing datetime format with subsec in GPS Time. I
> will make a fix for it and reprocess the photos (so you don't need to upload
> again). This will take a few days. Sorry for the error and the delay.

@ybkuang Hmm, I am still seeing this error on sequences. What's the holdup?

**Comment by gyllen** [comment] 2017-01-18 18:44
@nickplesha This is a part of the issue you are working on.

@GITNE Working on it.

**Comment by ToeBee** [comment] 2017-03-17 15:53
I think my original bug here about the manual reviewer incorrectly modifying the timestamp may be fixed. I modified one image in a sequence I uploaded last night and it seems to still be in the correct sequence order.

**Comment by nickplesha** [comment] 2017-03-22 13:52
@ToeBee Thanks for the feedback! We've made changes to the uploader and how it handles timestamps and timezones so this issue should not occur again.

**Comment by GITNE** [comment] 2018-06-28 12:39
@ybkuang You mentioned that you will reorder sequences automatically on the backend and add sub-second support. However, the affected sequences, like [`CnBJy5B-Z9pQrs8lR4fZxg`](https://www.mapillary.com/app?pKey=ospVD_Fw83OYW1DX4hZh5Q) and [`99U8cIMncsZ3O_mnpIe6YA`](https://www.mapillary.com/app?pKey=2C2-8O_-AqlL6hMeGlckOA), with fractional second `GPSTimeStamp`s still have not been put into the correct order after the latest full reprocessing. I do know what happens to lately uploaded sequences (have not tested), so I do not know if sub-second support has been added or not.

**Comment by ybkuang** [comment] 2018-06-28 12:52
@GITNE Sorry about the delay! I didn't manage to run the full reprocessing on the images. Since this bug is affecting other images, I would like to find a cost-effective way to fix this. I will put this into our to fix list and bundle the reprocessing with other tasks we have. I will keep you updated on this. Again, sorry for not having fixing this already.

**Comment by GITNE** [comment] 2018-06-28 14:28
@ybkuang I understand that full reprocessing is costly but the time stamping issues have been lingering since 2015. And, since not only third-party cameras support shooting multiple photos per second, the Mapillary app does so too, hence sub-second support is significant. Sub-second support becomes vital when capturing from cars (but even on bikes) if you want to have nicely smooth overlapping images.

While at it, since all the time stamping and ordering issues are intertwined, please also add timezone support via `OffsetTime`, `OffsetDateTimeOriginal`, and `OffsetDateTimeDigitized`.

**Comment by GITNE** [comment] 2018-07-03 11:01
@ybkuang You probably have thought of this yourself already but I will mention this just for the sake of completeness. You do not have to do reprocessing *at full speed*, as long as you:
* batch full reprocessing updates
  * or make sure all updates are in sequential order per image
* always process all fresh imagery  on the latest pipeline.

Hence, full reprocessing may run on as little as one machine, even if it takes a couple of months. Thus, you can minimize processing cost at the expense of time. :wink:

**Comment by peterneubauer** [comment] 2018-07-03 13:35
Yes agreed. The thing is that the information on the affected Android
versions is in an unindexed column in our postgres backend database. We
can't right now not even query the affected images although we have the
information. The first step is to migrate that data into an indexed format,
like our elasticsearch cluster. Since we can't search the info, we need to
sequentially go through all the images from that time and read out the
info. After that, we can have the slow-moving reparation job running. It's
the first part that I still haven't got to, but it's not forgotten. We are
emptying that database right now and moving it to another, much faster
instance as we speak, after that I might have the time to migrate that
data. For newer images, that info is already indexed I think elasticsearch
so this is just for the old images from that period when the date error was
present on the Android app.

**Comment by GITNE** [comment] 2018-07-04 11:17
@peterneubauer Thank you for this deep insight. It is great to read that there is some progress on this. :smile: Makes me optimistic!

And, if I understand your post correctly the new or *full speed* pipeline already has sub-second support in `GPSTimeStamp`, `SubsecTime`, `SubsecTimeOriginal`, and `SubsecTimeDigitized`, and time zone support via `OffsetTime`, `OffsetTimeOriginal`, and `OffsetTimeDigitized`. I am asking because I had issues again. But, if the new pipeline has these issues addressed then please write a blog post about it.

**Comment by peterneubauer** [comment] 2018-09-10 12:50
So,
yes, the original problem is that the order of the images was incorrect. Now, the sequence cutter went in and split the sequences, so they look a bit weird. Going forward, we are going to factor in  GPS timestamp, and the ordering errors should be fixed now. Not going to reprocess these sequences as most of it has been removed and the rest looks ok ...

**Closed by peterneubauer** 2018-09-10 12:50 UTC
Labels: affects-web-uploader, bug, info-tracked
