### ISSUE TITLE
Python: BadStatusLine: '' while uploading

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1716] opened 2016-02-18 07:16 UTC
During my nightly upload of around 20k images, I got the error below, which halted the process. The script has not returned to the console - it just sits doing nothing:

Uploading './sony-0deg/7'...
Uploading sequence 8c8c492d-e4ec-48f9-98e3-da727e825d9e.
Exception in thread Thread-3:--------------------------------] 33.7% ... 619 images left.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/home/tryl/almen/scripts/external/mapillary_tools/python/lib/uploader.py", line 51, in run
    upload_file(filepath, **self.params)
  File "/home/tryl/almen/scripts/external/mapillary_tools/python/lib/uploader.py", line 247, in upload_file
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

 ============================================================] 100.0% ... 0 images left..

**Comment by simonmikkelsen** [comment] 2016-02-19 06:15
Just had the issue again. The stack trace was shown in the console, but the upload process continued and  the last text that was printed was "100.0% ... 0 images left.". Then nothing more was printed and control was not returned to the console. No final done-file was uploaded and no done text printed.
In the folder from which the images were uploaded, one last image was not moved to the success folder. Nothing was in the error folder.

**Comment by richlv** [comment] 2016-03-07 06:26
note that mapillary uses a separate github project for the tools - https://github.com/mapillary/mapillary_tools/issues
and this issues seems to be a duplicate of https://github.com/mapillary/mapillary_tools/issues/27

**Comment by ybkuang** [comment] 2016-06-01 07:48
Closing this. Referring to mapillary/mapillary_tools#27.

**Closed by ybkuang** 2016-06-01 07:48 UTC
