### ISSUE TITLE
3d pointcloud does work strange...

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1562] opened 2015-11-24 11:41 UTC
Hi!

It looks like GPS postitions are much higher ranked than 3D pointcloud information. Look in here:
http://www.mapillary.com/map/im/IGQlIkiUiXBm58pChej6XQ/photo
Same way, 3 or 4 tracks, this special track is a bit left out. If you look into pointcloud, e.g. the bathtub is 2 times in the pointcloud.
I was under the impression, 3d pointcloud creation was better and did not care about GPS?

echelon

**Comment by echeloni2p** [comment] 2015-11-29 21:12
Another example:
http://www.mapillary.com/map/im/WUCD3kt2s_vODLOjiyqAbw/photo
Same street, but in pointcloud it makes 2 street, as photos are taken by GPS information. 3D Pointcloud could be far better, if the position would be better.
And I cannot change position of photos, as edit mode is on hold for position.

echelon

**Comment by paulinus** [comment] 2015-11-30 09:01
Hi @echeloni2p,

In the first example you mention, there are two sequences following the same path looking to slightly different directions. Our algorithms have unfortunately not been able to match the two directions, so they are building the two independent reconstructions that you are seeing.

We use the GPS as a soft constrain to place the reconstructions with respect to each other. In this case, the reconstruction looking to the left drifted to the left with respect to the other. While the GPS trace in this case is more accurate we don't trust it enough to be able to correct that drift.

I don't see this problem on the second example you mention.

thanks for looking at this,
pau

**Comment by paulinus** [comment] 2016-06-01 09:38
@echeloni2p I'm closing this one. The problem is the same as in #1669. Let me know if you have further comments. Thanks!

**Closed by paulinus** 2016-06-01 09:38 UTC
