### ISSUE TITLE
Time filter is not inclusive

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#1437] opened 2015-10-06 09:43 UTC
The end date doesn't seem to be included when using the time filter. For example, when I want to see photos take on the 1st or 2nd of October, I have to set the time filter from the 1st to the 3rd! If I set the end date to the 2nd of October, I will only get to see photos taken on the 1st.

**Comment by knikel** [comment] 2016-09-20 12:51
We have same behaviour in current filters. We should make sure the we have 23:59 on the `toDate`, since setting the `fromDate` and `toDate` to the same day will filter out everything.  Is that possible @nickplesha?

**Comment by pbb72** [comment] 2016-09-27 06:23
Settings the time stamp to 23:59 on the end date, feels like it could cause all kinds of mayhem with time zones.

The time evaluator simply needs to be made non-inclusive for the end date. In pseudo-code:

`... where (date >= start_date and date < end_date) ...`

instead of:

`... where (date >= start_date and date <= end_date) ...`

**Comment by knikel** [comment] 2016-09-27 06:33
Yes, that was just a joking/silly suggestion; the fundamental the problem is both `fromDate` and `toDate` currently are the same (as in stringified date YYYY-MM-DD) and filter out everything when applied to dates from vector tiles after conversion to milis.

**Comment by pbb72** [comment] 2016-09-28 17:05
Oh dear, I see my suggested code is very wrong, what I suggested is actually close to what is already being done at the moment.

It should be more something like this:

`... where (date >= start_date && date < (end_date + one_day)) ...`

Your suggestion was actually quite good :-)

**Comment by nickplesha** [comment] 2016-09-30 12:33
@pbb72 Thanks for reporting this, the issue is now fixed. 

The date filter applied was `date >= startDate and date <= endDate` but the problem was that dates both had `0:00:00` as `h:mm:ss` so the filter excluded everything. Now, the `endDate` has `23:59:59` so filtering by a specific day should show the images taken on that day correctly.

**Closed by nickplesha** 2016-09-30 12:33 UTC
Labels: affects-web-map, feature
