### ISSUE TITLE
Sequence Missing On Mapillary Browser But Viewable in OSM ID Editor

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/mapillary_issues#2147] opened 2016-08-02 07:25 UTC
I submitted some time ago a sequence that covers a stretch of road that passes through map location: https://www.mapillary.com/app/?lat=51.64273368030783&lng=0.034643390178388245&z=20

It is not viewable on Mapillary browser but is on the OSM ID Editor.
### Basic information
- Platform: `iOS` 
- Version: 9.3.3
### Steps to reproduce behavior
1. Go to location https://www.mapillary.com/app/?lat=51.64273368030783&lng=0.034643390178388245&z=20
2. You can see there is no sequence where there should have been. This sequence went from South to North.
   3.
### Expected behavior

Sequence should be visible on Mapillary borswer. This sequence is viewable on OSM ID editor.
### Actual behavior

Sequence is not visible on Mapilalry Browser but is on OSM ID Editor.
...
### Additional information

![mapillary](https://cloud.githubusercontent.com/assets/9841560/17320239/ce94335a-5892-11e6-88f9-c8f0bd471736.JPG)

**Comment by gyllen** [comment] 2016-08-02 14:03
@PaulColinSimpson Sometimes the green layer takes a little longer to update. Meanwhile can you give me an image key of one of the images in the sequence so I can check why its taking so damn long.

Thanks for reporting on this.

**Comment by PaulColinSimpson** [comment] 2016-08-03 06:13
Im afraid I cannot provide the image key for this sequence. It used to be on the previous browser version of Mapillary that you could still see the images on sequences that were not displayed in green.....but with this new browser this is not possible. I tried to get the key off of OSM....but for some reason in ID editor all Mapillary images are nt being displayed (only the location of the images) in IE 11.0.9600.18349.

**Comment by gyllen** [comment] 2016-08-03 18:55
@PaulColinSimpson No problem we will investigate the tile.

@ptpt Can you take a look at this

**Comment by ptpt** [comment] 2016-08-03 21:06
@PaulColinSimpson Thanks for reporting this issue. This is related to #1858.

@gyllen Another issue with DB. This is one of the missing sequence across this area https://www.mapillary.com/app/?focus=map&pKey=PAzA2CSi37GJFCi0jHST0Q&lat=51.55708058065477&lng=-0.010873258071001146&z=11.237846173260557 which has only 160 coordinates found, but it has thousands of photos.

**Comment by gyllen** [comment] 2016-08-03 22:40
@ptpt We are gonna have to look into caching of this sequence. I will reassign to @peterneubauer

**Comment by gyllen** [comment] 2016-08-03 22:41
@peterneubauer Can you take a look at the caching of this sequence?

**Comment by rausk** [comment] 2016-08-04 16:00
Here is another sequence shown with no green line (just a green dot):
lqAfF2i2Ij3o9C4t7RBEmw

The following sequence is not shown in one instance of the browser (not_shown 1.JPG)
mREFtwKLiz2UxarBQ_ZegQ
In JOSM you can see the sequence with the Mapillary add-on (Version 32639) and you can change from the Mapillary window inside JOSM to a look on the corresponding website and ...uups... now another instance of the browser does show the sequence (shown 2.JPG).
![not_shown 1](https://cloud.githubusercontent.com/assets/19711616/17408880/2f13dde4-5a6d-11e6-8b16-ebd5a4f2137a.JPG)
![shown 2](https://cloud.githubusercontent.com/assets/19711616/17408881/2f143988-5a6d-11e6-95cb-3e735ffb47c5.JPG)

**Comment by jfburke3** [comment] 2016-08-04 17:10
I just want to add a comment that I'm experiencing this, too.

**Comment by gyllen** [comment] 2016-08-04 19:05
@rausk I think your problem is caching, if you do a hard reload of the page (shift+update) this will probably solve it. However we should probably limit the cache time for all of our tiles so sequences gets viewed faster/

@jfburke3 Do you have an image key/ sequence key for the missing sequence I want to investigate.

**Comment by rausk** [comment] 2016-08-04 19:40
"Here is another sequence shown with no green line (just a green dot):
 lqAfF2i2Ij3o9C4t7RBEmw
"
This is definitely not a caching problem...

What is 
"hard reload of the page (shift+update)"
F5?

**Comment by gyllen** [comment] 2016-08-04 19:43
@rausk Yeah seems like all images got the same coordinates. To do some debugging can you help me with providing what method you used to upload these images.

**Comment by jfburke3** [comment] 2016-08-04 23:28
@gyllen It is definitely not a browser cache problem.  I use Chrome almost exclusively, but can reproduce the problem in IE and Firefox, which I rarely use, and can't think of a time when I've ever used them for Mapillary (other than when I was just getting started and had problems with the website when logging in from work).

Here are a couple of sequences of mine that have the problem:
alI_YsP8YVSi8l1RO4FOKg
gUqe61_lHJgdNBIqgKwwSg

Because of when they were uploaded, I'm almost certain that I used the Android Mapillary app to upload.  I'm also reasonably certain that they _used to_ display properly, until sometime very recently (either coinciding with the website redesign, or shortly thereafter).

**Comment by jfburke3** [comment] 2016-08-04 23:29
@rausk If you press Shift while clicking reload, then in most browsers, it's supposed to re-pull everything from the website instead of relying on locally cached data.

**Comment by rausk** [comment] 2016-08-05 07:48
@gyllen:

> Yeah seems like all images got the same coordinates. To do some debugging can you help me with providing what method you used to upload these images.

I used the Mapillary App which was up-to-date in Feb 2016 on my mobile with Android 4.4.2 for uploading the photos.
Please note: you can see the photos of that sequence in JOSM at the correct locations!

**Comment by ptpt** [comment] 2016-08-05 09:00
@rausk @gyllen The DB shows that this sequence `lqAfF2i2Ij3o9C4t7RBEmw` has all same points, though from photos they were obviously not taken at the same place. It is probably a problem with the mobile app.

`mREFtwKLiz2UxarBQ_ZegQ` has on any backend data issue, and all points shown on my Chrome 52 and Firefox 48/Linux. Which browser doesn't this sequence show in? It is probably a frontend issue.

@gyllen is JSON still using the old sequence tiles? Both new and old tiles are rendered from the same data source; they should have the same issue. I wonder why as well here.

**Comment by jfburke3** [comment] 2016-08-05 14:08
@rausk @ptpt Does sequence lqAfF2i2Ij3o9C4t7RBEmw show up in the correct location in the OSM ID or JOSM editors?

**Comment by ptpt** [comment] 2016-08-05 15:00
@jfburke3 Yes it is showing correctly here in both OSM iD and Mapillary.


https://www.openstreetmap.org/edit?editor=id#map=15/48.9127/8.5317
![2016-08-05 16-56-24](https://cloud.githubusercontent.com/assets/87357/17440632/bce83e56-5b2d-11e6-8980-fdfd82d4107d.png)

https://www.mapillary.com/app/?lat=48.9133270920172&lng=8.533421976014523&z=14.216579167022221&pKey=9fvSXALUk2UVhF4nl0zpLw
![2016-08-05 16-56-09](https://cloud.githubusercontent.com/assets/87357/17440635/befe27be-5b2d-11e6-9f01-2aea41bbfda4.png)

**Comment by ptpt** [comment] 2016-08-05 15:05
Ah sorry @jfburke3 the screenshots above are showing another sequence `mREFtwKLiz2UxarBQ_ZegQ`.

The sequence `lqAfF2i2Ij3o9C4t7RBEmw` you are asking about is correctly shown as well in both sides:

https://www.mapillary.com/app/?lat=48.90214499999999&lng=8.580497400000013&z=17&pKey=Nu3YOTHxBf6RcYJPiijJnw

https://www.openstreetmap.org/edit?editor=id#map=19/48.90207/8.58067

**Comment by peterneubauer** [comment] 2018-08-28 13:58
I just submitted sequences for re-calculation, let's see how things look tomorrow.

```
    'lqAfF2i2Ij3o9C4t7RBEmw',
    'alI_YsP8YVSi8l1RO4FOKg',
    'gUqe61_lHJgdNBIqgKwwSg',
    'mREFtwKLiz2UxarBQ_ZegQ'
```

**Comment by peterneubauer** [comment] 2018-08-29 07:44
After re-caching, these sequences look ok to me now, closing.

**Closed by peterneubauer** 2018-08-29 07:44 UTC
Labels: affects-backend, bug
