### ISSUE TITLE
In uploader trash icon is invisible when on white background

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2198] opened 2016-08-16 09:56 UTC
### Basic information
* Platform:  `Web`

### Steps to reproduce behavior

 1. put photos in uploader
 2. try to delete a photo with a white right-top-corner

### Expected behavior

finding a button somewhere that let me delete the photo

### Actual behavior

the delete button is invisible when it's on a white background

**Comment by angelday** [comment] 2016-08-16 10:05
Duplicate of https://github.com/mapillary/mapillary_issues/issues/2187 closing.

**Closed by angelday** 2016-08-16 10:05 UTC
