### ISSUE TITLE
Android new version 3.86 issues 

### ISSUE THREAD

**Issue by damjang** [mapillary/mapillary_issues#2673] opened 2017-08-20 21:33 UTC
I have tested the last android version and find that on my Samsung Galaxy S7 the Distance base capture don't work anymore. It take near 2 photo per second and also if I'm stopped take non stop photos. And also the "Use device compass" don't save the correct rotation.

PS: now I see that there are 2 new build in beta repository (android-releases.mapillary.io/index.html). Can someone explain what the snapshot1 mean? And where I can find the history/changes of every beta version?

PS2: tested with 3.89 and find same problems

**Comment by katrinhumal** [comment] 2017-09-05 08:02
Hi @damjang - sorry for the delayed reply! Would you please be able to try the current version 3.93-BETA as well and let us know? 

The snapshot versions are not released on Google Play, but we use and sometimes distribute them via download links to our users to test specific issues and fixes. We don't have a public log of all the app version release notes.

**Comment by damjang** [comment] 2017-09-23 11:24
And sorry for my delayed replay. Finally today I have time to test the last 3.95 version and on my device nothing change, the same problems as before.

**Comment by katrinhumal** [comment] 2017-09-25 11:46
Thanks @damjang - bringing in @ovivoda for help!

**Comment by ovivoda** [comment] 2017-09-25 12:39
@damjang Can you please send us some logs from the app so I can see what's wrong? Are you capturing with GMS?

**Comment by damjang** [comment] 2017-09-26 17:47
@ovivoda Here's my log: [mapillary_2017.09.26.zip](https://github.com/mapillary/mapillary_issues/files/1334278/mapillary_2017.09.26.zip)

Sorry,  but what's GMS?

**Comment by ovivoda** [comment] 2017-09-27 07:40
@damjang GMS = Google Mobile Services that is used to get a better location fix. We have the setting to use this service in Settings -> Developer -> Use Google Mobile Services. Do you capture with a phone that has internet connection while capturing? 

Thanks for the logs. Unfortunately the log contains few information. Please try and capture and send the logs again.

**Comment by damjang** [comment] 2017-09-27 19:42
@ovivoda Thank you. I have GMS disabled and I have internet connection during capturing, but sometimes I disable it.

I have installed the last 3.98beta version and done 3 capture sequence:
- distance capture (20m) - direction no compass, without internet
- distance capture (20m) - direction with compass, without internet
- distance capture (20m) - direction with compass, with internet

All 3 have already said problems, but this beta version capture images more slowly (is a way not responsive).
Here the new log: [mapillary2017.09.27.zip](https://github.com/mapillary/mapillary_issues/files/1338510/mapillary2017.09.27.zip)

**Comment by damjang** [comment] 2017-10-11 19:12
Sorry for late replay. I have tested some of the last 3-4 version of beta (gplay beta) and in all distance capture don't work - it take shots every x second, x is the setting of time base capture.
In all this last versions I also find that when I lose gps signal (if I go in tunnel) when gps is again visible also if Mapillary show the green flag for good gps the gps is not take in account and used. Also I can not stop (red button) the capture because no gps signal is find. I have to use back button to continue to use Mapillary.

**Comment by ovivoda** [comment] 2017-10-12 08:06
@damjang Do you have the developer setting -> skip location set to ON? That might be the cause for ignoring location when capturing.

**Comment by damjang** [comment] 2017-10-12 08:32
@ovivoda Yes, sure, I have it enable. But I think that this option is only "active" when no gps signal/fix and not always, also if I have a good gps fix. Will try with skip location to off. Thank you

**Comment by ovivoda** [comment] 2018-07-06 10:11
This issue has been fixed in the latest app version

**Closed by ovivoda** 2018-07-06 10:11 UTC
