### ISSUE TITLE
Problem deleting broken images in Android App

### ISSUE THREAD

**Issue by flohoff** [mapillary/mapillary_issues#79] opened 2014-04-14 07:55 UTC
Hi,

i am having problems deleting images in the Android App. I select 80 Pictures press on delete and the App deletes only a part of the images e.g 2 or 5. it seems purely random. It might be that the deletion is beeing interrupted working on the image list again. Am unshure about that.

Flo

**Comment by gyllen** [comment] 2015-02-09 04:17
Closing since duplicate of closed ticket

**Closed by gyllen** 2015-02-09 04:17 UTC
