### ISSUE TITLE
Sequences zigzag between far-appart photos instead of following photos in sequence

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#2531] opened 2017-04-14 21:08 UTC
### Basic information
* Platform: `Web` & JOSM

### Steps to reproduce behavior

Open one of these sequences:
* https://www.mapillary.com/app/index/debigc?lat=53.40089564357103&lng=-6.257590717851883&z=17.87387300919241&pKey=Ai_2kdcYMEzysJ80gUG4dQ&focus=map&menu=false 
* https://www.mapillary.com/app/index/debigc?lat=53.40411128322401&lng=-6.305160219932532&z=15.4466186715402&pKey=VGXfO5eSGBf8a6Qn3sXg9Q&focus=map&menu=false 
* https://www.mapillary.com/app/index/debigc?lat=53.40730578538154&lng=-6.299157474498315&z=16.22013799636387&pKey=EUEgvPuG5E9SMVtcI-w7gg&focus=map&menu=false

### Expected behavior

Photos should follow each other geographically.

### Actual behavior

Instead, photos zigzag from one end of the trip to the other, making them confusing to follow using the "next picture" button and drawing a messy "spider's net".

### Additional information

![screenshot_20170414_230549](https://cloud.githubusercontent.com/assets/115401/25056087/ec3f3344-2166-11e7-8388-bc6b6713d8cf.png)

Couldn't find a way to reorder the sequence myself, and this task calls for some scripting anyway. I didn't upload these sequences, just stumbled upon them.

**Comment by MrYadro** [comment] 2017-04-15 03:55
I think, the problem is the same as #2529

**Comment by echeloni2p** [comment] 2017-04-17 20:32
hey

should be fixed as of 3.47 on android. Side effect of change of processing GPS and camera on android.
Works fine here since 3.47 on 2 mobiles.

echelon

**Comment by vincentdephily** [comment] 2017-04-18 14:28
Cool, hopefully these won't show up again. Is there any way to fix already-uploaded sequences ?

**Comment by peterneubauer** [comment] 2017-04-19 10:10
Duplicate of https://github.com/mapillary/mapillary_issues/issues/2535

**Closed by peterneubauer** 2017-04-19 10:10 UTC
