### ISSUE TITLE
Overlay maptiles does not render corrected positions

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2385] opened 2016-11-30 08:08 UTC
Thanks for the new raster tiles! ref #1366
I corrected positions of some images (a few weeks ago) and they are rendered on the original position:

https://d6a1v2w10ny40.cloudfront.net/v0.1/17/68625/43368.png

https://www.mapillary.com/app/?lat=51.876170312342055&lng=8.486313783826148&z=18.092393909969125

**Comment by gyllen** [comment] 2016-12-05 23:18
@ptpt New on this?

**Comment by ptpt** [comment] 2016-12-05 23:48
This change didn't seem to be applied on the main database when tiler rendered the images (green dots). We will investigate further into this issue. Thanks for reporting.

**Comment by GITNE** [comment] 2017-02-06 19:49
I am observing this issue too. It is not that big of a problem if you are dealing with just one sequence in *no* *where*. But, in areas of high sequence density this becomes a real issue. @ptpt Is it feasible to fix this (and potentially the `HTTP 403` error issue) any time soon, or is it really too much work to take care of it at all?

**Comment by ptpt** [comment] 2018-07-06 08:54
@GITNE @HolgerJeromin sorry for taking so long. The problem is tracked internally and will hopefully be solved as soon as we switch to our new database in a few weeks. Closing here.

**Closed by ptpt** 2018-07-06 08:54 UTC
Labels: affects-tiler, bug
