### ISSUE TITLE
No CORS headers in vector tile response for zoom=0

### ISSUE THREAD

**Issue by wladich** [mapillary/mapillary_issues#2605] opened 2017-06-29 09:53 UTC
### Basic information
* Platform: `Web`
* System/Browser: `Chrome 59`

### Steps to reproduce behavior

Make a XMLHTTPRequest for tile with url https://d25uarhxywzl1j.cloudfront.net/v0.1/0/0/0.mvt

### Expected behavior
xhr.onreadystatechange is called upon completion

### Actual behavior
Error message in console:
> XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/0/0/0.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

### Additional information
To reproduce in console:
`curl 'https://d25uarhxywzl1j.cloudfront.net/v0.1/0/0/0.mvt' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,ru;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:3000/' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed -v > /dev/null
`

....
< HTTP/1.1 200 OK
< Content-Type: application/vnd.mapbox-vector-tile
< Content-Length: 421587
< Connection: keep-alive
< Date: Thu, 29 Jun 2017 09:05:47 GMT
< Last-Modified: Thu, 29 Jun 2017 03:26:03 GMT
< ETag: "3ce33b1bd6815d0b233579514aaf676e"
< Accept-Ranges: bytes
< Server: AmazonS3
< Age: 313
< X-Cache: Hit from cloudfront
< Via: 1.1 c40ee2288a7db28fefd61c3f2ec7ccd7.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: NmF3ZmRxbP_VYZxJ5pA5fRc352s3DGEiywEaay2BTaWAgpZCeaESKw==

If zoom=1 then Access-Control-Allow-Origin is in response:

`
curl 'https://d25uarhxywzl1j.cloudfront.net/v0.1/1/0/0.mvt' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,ru;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:3000/' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed -v > /dev/null
`

< HTTP/1.1 200 OK
< Content-Type: application/vnd.mapbox-vector-tile
< Content-Length: 296764
< Connection: keep-alive
< Date: Thu, 29 Jun 2017 09:00:32 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET
< Last-Modified: Thu, 29 Jun 2017 07:51:44 GMT
< ETag: "840dd562b7998ff52da12edebb7d7011"
< Accept-Ranges: bytes
< Server: AmazonS3
< X-Cache: RefreshHit from cloudfront
< Via: 1.1 831ce605dd77f58786c993787cdac90b.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 9lRJMhIqINz1Ou6b-veuzILJAnXJiB9QgzAuRwt5IlH10Ff1GB566Q==

**Comment by gyllen** [comment] 2017-07-02 21:48
@wladich Im trying to see the difference between the 2 calls. Copy and paste for both do return the correct `Access-Control-Allow-Origin` header for me though

**Comment by wladich** [comment] 2017-07-02 21:58
There was error in second curl -- it was  for zoom 0 also. Fixed.

**Comment by wladich** [comment] 2017-07-02 21:58
I checked request for zoom 0 again -- still no Access-Control-Allow-Origin when I request from home (Russia). If I make same request from server in Lithuana (Eastern Europe) then headers are ok.

**Comment by gyllen** [comment] 2017-07-02 22:08
This is super strange, Im trying from west coast us and I get the header for both 0 and 1. Could it have anything todo with cache in your browser?

**Comment by wladich** [comment] 2017-07-02 22:29
No, as far as I know curl does not use any cache.
I rechecked ajax request in browser with cache disabled in devtools -- still same error.

And I get good headers for other zoom levels, both for ajax and curl requests.

I guess it's related to CDN serving wrong headers for my area.

**Comment by gyllen** [comment] 2017-07-04 14:24
@wladich Its interesting though that its only one tile /0/0/0, I might need to get a russian proxy to try this out.

**Comment by wladich** [comment] 2017-07-04 14:44
Checked again from two hosts in Russia -- today it works, headers Access-Control-Allow-* are present in response.

**Comment by wladich** [comment] 2017-07-13 09:07
Not working again: no headers line in curl output and error in browser console (checked in Chrome and Firefox).
BTW I see the same error in browser console on mapillary map page at https://www.mapillary.com/app/ when zooming to minimum level
`
XMLHttpRequest cannot load https://d25uarhxywzl1j.cloudfront.net/v0.1/0/0/0.mvt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mapillary.com' is therefore not allowed access.
`

**Comment by gyllen** [comment] 2017-07-25 07:55
@martinskans Can you help investigate, seems to be something CDN related.

**Comment by wladich** [comment] 2017-07-25 14:28
How can I help?

**Comment by martinskans** [comment] 2017-08-08 10:19
So looking at the cloudfront url above it seemed to be for tiles3 so I looked into the configuration for that one and found that headers were cached. That might be what is causing it to work for some regions and not for others so I have white-listed the `Origin` field which they suggest should solve the problem.

Possibly there may be more cloudfront urls involved so maybe if you see it again I will have to see more of those error messages to see which ones!

**Comment by nicolas17** [comment] 2018-02-05 02:52
Duplicate of #2648? And there may be more...

**Comment by gyllen** [comment] 2018-02-12 08:42
@ptpt ^^^

**Closed** 2018-07-06 08:43 UTC
