### ISSUE TITLE
Unable to upload any sequence since latest mapilary android app update

### ISSUE THREAD

**Issue by quicky2000** [mapillary/mapillary_issues#2530] opened 2017-04-13 13:07 UTC
### Basic information
* Platform:  `Android`
* Version: `3.45` 
* System/Browser: `Android 6.0.1`
* Phone : Samasung Galaxy A5 2017
* Phone reference : SM-A520F

### Steps to reproduce behavior

 1. Capture some photos
 2. Upload them
 3.

### Expected behavior

Fast processing sequence display, then upload progress and upload successfully terminated

### Actual behavior

Slow sequence processing ( compared to previous version ), no upload progress display.
At the end Upload failed. The display indicate `Error 400 0 of 23 images uploaded

### Additional information
I have the issue with both 4G+ and Wifi connection. in android application monitoring I see that Mapillary App is using data connection.
I started with Mapillary on Android 2 weeks ago and it was working fine. This morning I noticed that mapillary application can be updated so I performed the update, do some captures and then tried to upload them but it doe not work anymore....
I tried to reboot my phone, to logout from mapillary apps but didn`t see any improvement

**Comment by quicky2000** [comment] 2017-04-13 13:15
Hi,

In addition to that blocking issue I noticed that since this morning app update the capture screen froze sometimes

**Comment by katrinhumal** [comment] 2017-04-13 14:22
@quicky2000 Thanks for reporting! Could you possibly send us logs of that? Please go to Settings -> Developer and enable `Save debug logs to file`, then try capture and upload again to reproduce the error, and send us the logs via the left-hand menu. Thanks!

**Comment by quicky2000** [comment] 2017-04-13 16:43
Here is what I obtained

Some logs:

**Comment by quicky2000** [comment] 2017-04-13 17:19
Or with more  details

Mapillary Android logs, user=quicky, version=345(3.45)
Some logs:

**Comment by jfburke3** [comment] 2017-04-13 17:36
I'm having upload problems with 3.46-SNAPSHOT.  I'll try to get you some logs in just a bit.

I just upgraded from 3.45 this morning when I saw the new one in the beta channel, and went to resume some of my sequence uploads from the weekend, and now it doesn't seem to actually be uploading anything (that I can tell).

I've been staring at an "Upload in progress" screen for the past 5 minutes, with no "# of ##" progression count happening.  The status bar message just says "Processing ..."

When I change tabs in the app, then go back to the upload tab, I'm back at the list-of-sequences with no upload progress notification at all.

**Comment by jfburke3** [comment] 2017-04-13 17:39
I should add that, while I had some occasional quirks and error messages in 3.45, I didn't have any major problem uploading with that release.

**Comment by quicky2000** [comment] 2017-04-13 17:41
Hi,

Thanks this is exactly the same issue I have.if you wait a sufficient time you should obtain the error 400.
I have 11Go to upload and I will have a lot more on saturday but I will not have enough storage in my phone ...is there any way to put it aside (on a PC ? ) by the time there is a solution ?

**Comment by jfburke3** [comment] 2017-04-13 17:45
@quicky2000 Yes, you can copy the folder containing your images to a computer, and then upload them using the web interface, or use their upload scripts to upload from there.  I haven't done it in a while, but the last time I did, it worked fairly well.

https://github.com/mapillary/UserGuide/wiki/Uploading

**Comment by peterneubauer** [comment] 2017-04-13 19:37
I'm on it, there will hopefully be an update tomorrow for the aloha
testers, so wait with the upload until then?

**Comment by quicky2000** [comment] 2017-04-13 20:30
Hi Peter, good news.
I succeed to obtain the trace file. You can find it in attachment.
Hope this helps
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/920768/mapillary_trace.txt)

**Comment by quicky2000** [comment] 2017-04-13 21:46
@jfburke3 Unfortunately from my Linux PC I cannot find the pictures taken by Mapillary apps so I have no choice, I have to wait for a new version of the app :-(

**Comment by echeloni2p** [comment] 2017-04-14 06:35
@quicky2000 it is in your android path, you can see the path if you go in mapillary on the settings under storage, by default it is /storage/emulated/0/Android/data/app.mapillary/files
On the USB connection choose file transfer and internal storage, afterwards it should be the Android/data/app.mapillary/files directory

echelon

**Comment by quicky2000** [comment] 2017-04-14 08:06
@echeloni2p Itried it but Android/data contains only a directory that is not app.mappilary
I tried  with mtp and ptp mode but the result is the same.
I dont have a mass storage mode with Android 6.0.1 contrary to what I had with my S2 on Android 4.0.4.
I tried a search in file tree with hidden files displayed but no result with mapillary string...
Perhaps is it due to my kubuntu?

**Comment by quicky2000** [comment] 2017-04-14 08:09
For the usb connection I have only mtp ptp and charge only.
Where do you find file transfer and internal storage? Is it on Android 6?

**Comment by echeloni2p** [comment] 2017-04-14 09:19
Hey, no in the mobile phone after connecting with USB you can select the USB mode your mobile uses. At least thats what my androids show me.
On a different solution: you can use apps like total commander to move the pictures from internal storage to a SDCard (e.g. a 128GB one...) and read the SD card with a card reader. Not as comfy, but works, to.

echelon

**Comment by quicky2000** [comment] 2017-04-14 20:54
@jfburke3 @echeloni2p after more investigation and a trial with a different method I succeeded to transfer photos taken by mapillary app on my Kubuntu PC, thanks for your tips

**Comment by quicky2000** [comment] 2017-04-14 23:07
@peterneubauer @jfburke3 @katrinhumal I think I have a better view of the issue. I remarked that my free storage decrease very fast compared to what I had with previous version and by looking at pictures taken by mapillary apps I realised they are very big: 30.4MB per picture.
They are at full resolution ( 4608 *3456 ) of my photo sensor and I compared to unprocessed original files I uploaded before app update. Pitures were in same resolution but with a weight of 3.4MB.
I tried various combinations with old camera API,low resolution but the result is always the same: 30.4MB picture. A manual upload on mapillary website lead to upload failed too and after some research on internet it seems that picture are limited to 8.5MB for upload.
Could you check on your side if you can reproduce the issue ?
I tested too the 3.47 beta version and the result is the same....
I think that this very big weight foe picture could explain the freeze I observe in capture mode and while preprocessing and upload are so slow
Thanks by advance for your support

**Comment by jfburke3** [comment] 2017-04-17 19:45
I'm going to send in a fresh trace log in just a bit.  @peterneubauer , unfortunately, after Saturday's brief test uploads, it seems to have stopped working again.  I don't know if the problem is the Android app, or the upload service on the server end of things.

In the trace log, you should see several upload attempts on wifi (I tried at two places, just to rule out a problem at one), and one on cellular.

**Comment by jfburke3** [comment] 2017-04-17 19:59
For today's upload failures, I tried to do individual sequences.  It never left the "Processing sequence 1 of 1, 13 / 13" message (i.e., never indicated that it had started uploading, never shows an upload progress message).

**Comment by jfburke3** [comment] 2017-04-17 20:00
Oh, should add that I'm using version 3.48.

**Comment by echeloni2p** [comment] 2017-04-17 20:26
Hi
I see the box "processing sequence x of y" long time, it disappears after you did finish a upload of a picture. If you do close the app/change the app in between, you need to wait until it uploaded a picture 100%, else the box will not update...

echelon

**Comment by jfburke3** [comment] 2017-04-17 21:51
How long should I have to wait?  I let it sit for more than 20 minutes trying to upload some short sequences (less than 50 images), and the "processing" message never went away.  Note that it never said "uploading....." which it used to do.

**Comment by peterneubauer** [comment] 2017-04-17 23:02
You should not have to wait long for processing. It seems there are some problems reading some of your images:

```

Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_48_198.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_49_007.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_50_199.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_51_003.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_52_065.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_54_094.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_55_147.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_55_798.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_56_764.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_57_701.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_58_711.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_45_59_641.jpg has null date
Mon Apr 17 15:23:11 EDT 2017 : app.mapillary.android.exif.ExifUtils  - Image 2017_04_16_19_46_02_088.jpg has null date
```

Can you please send me one of these @jfburke3 ? Also, I will check so the progress is shown even though the images are not actually uploaded.

**Comment by peterneubauer** [comment] 2017-04-17 23:38
@jfburke3 you can try http://android-releases.mapillary.io/Mapillary_Android_3.49-SNAPSHOT1.apk for a hopefully better progress dialog. However, there are no pictures uploaded since the date can not be found, please send me at least on of these, see above? (you can see them via a normal file explorer, navigating to the Mapillary directory and into the sequence 2017_04_16_19_46

**Comment by jfburke3** [comment] 2017-04-18 03:37
@peterneubauer , I've e-mailed 3 of the requested images separately; let me know if you want more.  I'll download that apk and see what it does.

I noted that #2533 appears to have been opened on the same problem.

**Comment by peterneubauer** [comment] 2017-04-18 05:35
Ok, @jfburke3 if you try http://android-releases.mapillary.io/Mapillary_Android_3.49-SNAPSHOT2.apk, I'm failing over the missing DateTimeOriginal EXIF tag to CreateDate. Does that work better?

**Comment by peterneubauer** [comment] 2017-04-18 09:20
![image](https://cloud.githubusercontent.com/assets/11977/25123542/0dc152a8-2429-11e7-9784-45397a01924d.png)

**Comment by quicky2000** [comment] 2017-04-18 12:27
Hi,

Do you have some news about the issue I encountered : pictures taken by mapillary apps were suddenly very big ( 30.4MB) what was making the server reject them.
During the week end, after unsucessful testing with 3.47 beta I deleted all sequences having big pictures and new sequences started after that now have pictures with correct size I don't understand why...

**Comment by jfburke3** [comment] 2017-04-18 15:20
@quicky2000 Just a side comment that my images are all around 3MB.  I have no idea how you're ending up with 30MB images.

**Comment by peterneubauer** [comment] 2017-04-18 15:25
@quicky2000 if you have any of the big images left, did they look OK or faulty, and could you send me one if possible? @jfburke3 hiw is the new 3.49 working out for you?

**Comment by quicky2000** [comment] 2017-04-18 15:42
@jfburke3 OK so you have same symptoma but different cause
@peterneubauer Yes I still have them, I intend to try to postprocess them to upload them. as they look OK You can find one of these images here http://dl.free.fr/f7U4sGtdI

**Comment by jfburke3** [comment] 2017-04-18 16:39
@peterneubauer Mapillary_Android_3.49-SNAPSHOT2.apk is uploading images.  It has several problems, but it *is* uploading.

Among the issues I've observed:

* the dialog boxes "come back" and won't go away.  E.g., after a sequence finishes uploading, it gives me the "upload finished" message and then the message box goes away.  But, if I open another sequence, the "upload finished" box is back, and I cannot get it to go away except by exiting the app.

* After uploading a couple of short sequences, I picked a larger one (81 images).  It looked like it went through the processing phase 3 times, then started uploading "1 / 14".  It apparently only recognized 14 images in the sequence at first, and yes, it left the other 67.  I had to exit the app and go back in, and was then able to get it to upload the remaining 67 images.

**Comment by jfburke3** [comment] 2017-04-18 16:43
I see the uploaded images in my Feed on the website, but I don't see their tracks on the map....  I can select them in the feed, but that doesn't make the track show up.

**Comment by peterneubauer** [comment] 2017-04-19 09:58
@jfburke3 for the not-processing 81 images, can you get the logs after you tried to process them?

**Comment by jfburke3** [comment] 2017-04-19 20:37
I already cleared the log from that upload, but if I can get it to happen again, I'll send a log.  This *was* happening pretty reliably in the 3.49 SNAPSHOT release, but I updated to 3.50, and now it doesn't seem to be occurring.

**Comment by jfburke3** [comment] 2017-04-20 16:11
@peterneubauer Ever since updating to 3.50, I haven't had it skip any images.

**Comment by jfburke3** [comment] 2017-04-21 00:03
@peterneubauer It finally skipped some images that I shot and tried to upload today.  For several sequences, it would only upload a portion of the sequence.  I had to exit the app, go back in, and keep trying to upload the rest of the problem sequences to get them all uploaded.  I'll e-mail trace logs in a bit.

**Comment by ovivoda** [comment] 2017-05-21 16:27
@jfburke3 Pease try http://android-releases.mapillary.io/Mapillary_Android_3.57-SNAPSHOT3.apk and let me know if the upload works better.

**Comment by ovivoda** [comment] 2018-07-06 08:34
This issue should be fixed in the latest version of Mappillary Android application

**Closed by ovivoda** 2018-07-06 08:34 UTC
Labels: affects-android, bug
