### ISSUE TITLE
Image still processing

### ISSUE THREAD

**Issue by iagsav** [mapillary/mapillary_issues#1999] opened 2016-07-09 22:20 UTC
Hello I have 8 images, which is "still processing". Can you help ?

**Comment by de-vries** [comment] 2016-07-10 07:11
duplicate of #1136 and #1971.

**Comment by gyllen** [comment] 2016-07-11 14:52
Hi @iagsav usually this is just what we call `ghost images` - which means that we have processed everything but we has some hickups along the way and our pipeline did a reprocessing.

Can you confirm that you actually do miss images?

**Comment by iagsav** [comment] 2016-07-11 17:10
I upload 30000 images and i can't say which of them i miss

**Comment by gyllen** [comment] 2016-07-11 22:23
@iagsav Great work!! So for now you can relax about the still processing images. Its really not missing images, just our server that does a bad job counting.

**Comment by polarbearing** [comment] 2016-07-12 08:43
Please consider #1974 in this context.

**Comment by iagsav** [comment] 2016-07-12 12:13
Thanks for all comments!

**Comment by gyllen** [comment] 2018-07-18 07:42
We no longer have this issue.

**Closed by gyllen** 2018-07-18 07:42 UTC
Labels: affects-backend, bug
