### ISSUE TITLE
reverse geocoded location has disappeared from profile thumbnails

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#1402] opened 2015-09-22 14:32 UTC
My recent (from 17 Sept 2015 onwards) uploads don't show any more the reverse geocoded location. I only see "by 'my username'", nothing else. (Windows 10, Firefox and Edge)

**Comment by gyllen** [comment] 2015-09-23 00:33
Im not sure this is if its something wrong from our side or if its actually just that we do not get any location lookup. @peterneubauer did adding gpano change anything of this?

**Comment by voschix** [comment] 2015-09-23 06:34
The problem refers to locations in my immediate neighbourhood where the reverse geocoding worked until 10 Sep 2015. The new courses on 17/18 September started in the same place. So something changed between the two dates. It may be a local map problem. My location is http://osm.org/go/0IBqaXRry--?layers=C&m=&way=131809388
Here are the thumbnails of two sequences that started both in my courtyard:
![reverse geocoding disappeared](https://cloud.githubusercontent.com/assets/11076112/10038957/abbab23a-61cd-11e5-83a1-7838471f6a06.jpg)

**Comment by de-vries** [comment] 2015-09-23 07:06
@gyllen I can confirm this issue

**Comment by peterneubauer** [comment] 2015-09-23 14:38
It seems to be the nominatim server not being up for a while. In the future, a maybe better solution will be not to store location with the images, and instead ask the server in realtime, as locations might change over time.

**Comment by de-vries** [comment] 2015-09-23 14:51
Today I stumbled upon [Photon](http://photon.komoot.de/). they also do reverse geocoding, I haven't tested this but it seems that in some aspects Photon is better than nominatim. maybe it can be used as a backup service.

**Comment by voschix** [comment] 2015-09-24 07:39
@peter: The real-time reverse geocoding is not such a good idea, at least at the moment.
As data producer i need to keep a log of which sequences I have checked already (mainly for missing or wrong pixellation). My log at the moment is a spreadsheet where I use the location as reference (because it's the only info, other than the user name, I can see it by hovering the mouse over the thumbnail). In case of two identical locations I add date and time, but for that I need to open the sequence. BTW Would be nice to have the checking process supported on the Mapillary site somehow. Would be sufficient most likely to have a "checked by author" flag that only the author can set/reset. Or a free-format comment field modifiable only by the author of the photos. I will raise this in the forum.

**Comment by peterneubauer** [comment] 2015-09-24 08:24
True true,
a comment field is actually part of the plan, when @gyllen and I get to it!

**Comment by peterneubauer** [comment] 2018-08-27 10:03
We dropped the reverse geocoding from the platform due to this being a moving target, so I'm closing this for now.

**Closed by peterneubauer** 2018-08-27 10:03 UTC
Labels: affects-backend, bug, feature
