### ISSUE TITLE
picture is upside down

### ISSUE THREAD

**Issue by beer119** [mapillary/mapillary_issues#1919] opened 2016-06-05 12:17 UTC
I dont know if it is a error 40/ user error or an error somewhere else but this picture is upside down:
https://www.mapillary.com/map/im/OIgsB6RjIQ3Qgsy7pZMJmg/photo

**Comment by millenbop** [comment] 2016-06-09 07:56
Can we rotate this? Perhaps @ybkuang or someone else can do it :)

Which platform are you using by the way, iOS or Android?

**Comment by beer119** [comment] 2016-06-09 08:41
I was using Android (nexus 6p). I am not sure how to reproduce this problem. If you have an idear how to test then led me know

**Comment by beer119** [comment] 2016-06-09 08:42
Btw it is the whole serie that seems to be the problem and not onlt one picture?

**Comment by ybkuang** [comment] 2016-06-09 08:46
@beer119 Thanks for reporting this. This is related to #1892 and @rsahlin is investigating. Closing this and refer to #1892.

**Closed by ybkuang** 2016-06-09 08:46 UTC

**Comment by rsahlin** [comment] 2016-06-09 09:16
Hi @beer119 

I am looking for the root cause of this.
Could you please make sure you are using the latest version, at least 2.20, and also enable saving of logs by opening 'Feed' - 'Settings' and enable 'Write trace logs'
This will save the debug logs.
If the problem happens again, please go into 'Feed' and select 'Send debug logs'
If the problem did not happen in a sequence you can check 'Feed' - 'Settings' - 'Start new logs' to clear logs.
Otherwise they will become very large :-)

Thanks for your help!

Best regards
/Richard

**Comment by beer119** [comment] 2016-06-09 11:37
Hi
I will send you a log next time it happends (if it does). But it seems like I cannot preproduce it.
