### ISSUE TITLE
Video Upload not possible anymore

### ISSUE THREAD

**Issue by dr2okevin** [mapillary/mapillary_issues#2923] opened 2018-06-03 20:27 UTC
Since Friday it is not possible for me to upload videos. At 100% upload I get an http 403. And the short 3 minutes Video Clip I uploaded is even after almost 3 days still not visible in my account.

![mapillary](https://user-images.githubusercontent.com/1845792/40890870-07635382-677d-11e8-8720-ea1fdcf5e43e.PNG)

The body of the 403 Page contains this

`<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`

**Comment by madelenarnesdotter** [comment] 2018-06-04 12:07
Hi @dr2okevin - thanks for writing in! We've had some issues with sequences uploaded through scripts and the web uploader. We're really sorry for this, however we've recovered the system and are now waiting for the system to catch up. Your uploads should be visible in a couple of days. I will check in on Wednesday to check status with your uploads!

**Comment by peterneubauer** [comment] 2018-06-04 12:18
@knikel @martinskans this is probably connected to us tightening the security on the S3 bucket for legacy video upload?

**Comment by martinskans** [comment] 2018-06-05 12:55
@dr2okevin Thanks for the screenshot. Yesterday I added the permissions that seemed to be missing to the bucket that I see in your log, so hopefully that should give you back the ability to upload. Sorry for the inconvenience - we have been doing a security review and restricted permissions a little bit too much in this case!

**Comment by martinskans** [comment] 2018-06-08 09:49
Another issue showed itself that related to this that has now been fixed as well. I have confirmed that I am able to upload a video so closing this for now.

**Closed by martinskans** 2018-06-08 09:49 UTC

**Comment by ligfietser** [comment] 2018-06-11 20:40
I have tried to upload several videos lately but none of them showed up. On https://legacy.mapillary.com/map/upload/vi the upload seems to get stuck on 100%, I don't get a message that the upload is succesfully.
Can you check what's wrong here?

**Comment by peterneubauer** [comment] 2018-06-12 07:42
This should now be resolve with @martinskans fixes to the S3 bucket
security setup?

**Comment by martinskans** [comment] 2018-06-12 12:38
Yes the security overhaul we were forced to do led me to find some incompatibilities with older code since before my time (as in the old legacy site above). I managed to fix that just before the weekend for the legacy site and I've done it in a way so it's easier for us to do similar changes in the future without breaking this again. Of course this assumes we don't implement video uploads in the new site before then so we can shut down the old site.

**Comment by ligfietser** [comment] 2018-06-12 14:49
@peterneubauer yes it is resolved now, I see the sequences appearing on the map now.
