### ISSUE TITLE
(0.00% uploaded)

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#962] opened 2015-04-27 19:30 UTC
Since 2 Days i try to upload different sequences.
but webupload freeze and never moves ...

**Comment by jesolem** [comment] 2015-04-27 21:18
Are you using https? Try with http and see if it still hangs.

@knikel is looking into a bug with https

**Comment by Skippern** [comment] 2015-04-28 01:50
I have the same problem, but it freezes at different percentages, even at 100% (without finalising)

**Comment by Skippern** [comment] 2015-04-28 01:51
(same result in http and https)

**Comment by eugensim** [comment] 2015-04-28 09:48
I have uploaded a video 100% (without finalising) that means will be processed or not? The video is quite big, a hour to upload.

**Comment by thoschu96** [comment] 2015-04-28 14:52
ok.. seams to freeze, if you have at least one picture without GPS data in the queue

**Comment by Skippern** [comment] 2015-04-28 16:06
I don't think it is directly linked with frames missing GPS data, I always trim my videos so that they start and end with confirmed position on the gpx file (using `Garmin VIRB Edit` on my videos generated by my VIRB Elite unit). I have seen though that dip in connection during upload freezes the upload. A full ''max'' length video from the Garmin VIRB is a whooping 3.6GB, and I often connect from slow or sluggishly slow connections. Also on hotel connections I often observe 2-3 second outages (and sometimes 2-3 minute outages). I notice such outages by being disconnected shortly from IRC, that my Skype changes status, that my drop box re-sync, etc.

**Comment by ybkuang** [comment] 2015-04-28 16:19
@skippern I think the problem is that the file size is exceeding the size limit set in

**Comment by Skippern** [comment] 2015-04-28 16:44
I have at least 2 successful uploads of files around 3.6GB, and since they freeze on different stages of upload. I can retry the same file several times and it freezes at different places each time

Aun Johnsen

**Comment by eugensim** [comment] 2015-04-28 18:59
maximum limit shall not be less than 100 gb. I have over 50GB videos. (hours of filming at 4k resolution)

**Comment by Skippern** [comment] 2015-04-29 15:06
@eugensim I only trim start and end of video to make sure I have gps data on first and last frames (I do not check to see GPS quality in the middle of the video, but generally this shouldn't be issue unless in urban canyon)

**Comment by Skippern** [comment] 2015-04-29 15:50
Idea: Maybe show upload rate and uploaded size/remaining size, and have a button to "force finalising" so that super-large uploads can be force-completed when the user is satisfied with the length sent (I wouldn't mind cutting the last few frames of a 40min (3.6GB) upload freezing at 100%)

**Comment by Fod90** [comment] 2015-05-08 08:44
+1.

Characteristics:
- Only ~1 out of 10 uploads completes, ~1 out of 10 hangs during upload, ~8 out of 10 never start (0.00% uploaded)
- Reproducible in both Internet Explorer (version 11.0.17) and Chrome (version 42.0.2311.135)
- Reproducible using both http:// and https://

**Comment by knikel** [comment] 2016-06-01 09:29
Uploader is getting a total revamp soon. Will close this when we roll it out.

**Closed** 2016-07-20 20:24 UTC
Labels: bug, fe-new, web
