### ISSUE TITLE
time for LG360 camera is wrong on iOS uploads screen 

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2487] opened 2017-03-09 20:25 UTC
### Basic information
* Platform: `iOS`
* Version: `10.2.1` on a 5S 

### Expected behavior
- Using an LG360 camera and the Mapillary app. Transferred images to phone after capture and the time of the sequence is displayed as being in the future.

![img_0004](https://cloud.githubusercontent.com/assets/4806884/23768913/9000f15a-04db-11e7-8450-745809bb7047.PNG)

**Comment by millenbop** [comment] 2017-04-05 09:04
Thanks for reporting, I'll look into this now.

**Comment by millenbop** [comment] 2017-04-05 10:59
Everything looks good on my end. Either it's a timezone thing or the app failed to set the date or the date has changed by some other means (the LG app did it by itself etc).

- Which firmware are you using on the LG?
- Which time would you expect (roughly)?
- Which timezone are you in?

**Comment by danbjoseph** [comment] 2017-04-05 12:01
I just found it very curious that the time on the phone is 3:16PM and the sequences are all noted as being captured close to 6PM. I had captured the sequences sometime between 1 and 3. I don't have the LG with me right now, but I had made sure everything was up to date the day before. I'm in Washington,DC.

**Comment by millenbop** [comment] 2017-04-05 13:23
Was this a one-off error or have you seen it more than once?

**Comment by danbjoseph** [comment] 2017-04-05 13:53
May have been one-off. I have only used the LG360 and iOS app once since then. Waiting for the ability to do distance-based capture with external camera.

**Comment by danbjoseph** [comment] 2017-04-05 13:55
If it happens again, I will try and gather more data to send about the issue.

**Comment by millenbop** [comment] 2017-04-05 14:00
It will be added soonish when the new camera implementation (V3) is done. The biggest problem with distance based capture for external cameras is that it will consume more battery. I haven't measured how much though.

Basically with time-based capture the phone just sends "start time lapse capture". With distance-based capture the phone needs to send "capture now" all the time. For a 1000 photo sequence that means 998 more commands via WiFi.

Is it ok if I close this issue until then? I cannot reproduce it here, but granted I haven't spent more than an hour investigating it. But if the problem arises for you or someone else, I'll gladly reopen and spend more time on it.

**Comment by danbjoseph** [comment] 2017-04-05 14:06
Yeah, close away. Was more just a "hey, i saw this and it was weird" than a request for some sort of fix.

**Closed** 2017-04-05 16:14 UTC
Labels: affects-ios, bug
