### ISSUE TITLE
Allow login using username

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#318] opened 2014-09-07 21:21 UTC
My username is much shorter than my email. Could you allow logging in using usernames too so that I don't have to type so much, esp on mobile/iOS (which has the multi device login issue). Many other sites allow login using both email and username.

**Comment by jesolem** [comment] 2015-06-01 08:41
@smsm1 Mobile does not have multi-device problem anymore.

**Comment by cldershem** [comment] 2015-07-01 04:16
It would also be good to know that you're not going to use the username to login, but the password when signing up.  I use gmail's plus addressing (`email+websitename@gmail.com`) when I sign up for stuff which is normally fine if you login using a username.  However, in this case I am unable to login to the Android app with the same info that works in the browser.  My guess this has something to do with validation, but I could be wrong.  If there was a way for a user to update their email address through the website, this would be a non-issue for me.

**Comment by gyllen** [comment] 2015-07-01 13:01
@cidershem So you are saying that you have an email+password and it works on the be but not on your android phone?

**Comment by cldershem** [comment] 2015-07-01 17:22
@gyllen Correct.  I cannot login to the android app, but I can login to the web perfectly fine with the same info.  It just tells me that it's an incorrect username/password combo.  My only guess was that it was caused by the `+` in the address.  Like I said before, if there was a way for me to update my email address, I'd be more than happy to test it out.

**Comment by gyllen** [comment] 2015-09-22 23:42
Can you check this on Android?

**Comment by cldershem** [comment] 2015-09-24 07:51
Just tried this again on android with no luck.  Everything works fine on the website, but the same info in the android app gives me an error.

**Comment by peterneubauer** [comment] 2015-09-24 08:19
strange. could you please reset your password to something non-critical and get me your login so I can test?

Also, login via username is not supported anywhere, but a good enhancement request IMHO @gyllen .

**Comment by peterneubauer** [comment] 2018-08-24 13:02
closing this. too old.

**Closed by peterneubauer** 2018-08-24 13:02 UTC
Labels: affects-backend, affects-web, feature
