### ISSUE TITLE
Draw blur/traffic signs rectangles in directions other than down+right

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1514] opened 2015-11-13 11:59 UTC
Currently it is only possible to draw a blur / traffic signs rectangle in the down+right direction. Drawing on other directions does not work: a X sign appears, but the rectangle has no dimension.

![](https://cloud.githubusercontent.com/assets/397851/11098720/eb5c060a-888d-11e5-9d33-af545f4728f8.png) ![](https://cloud.githubusercontent.com/assets/397851/11098801/93f6bf4e-888e-11e5-91da-86a9d10b8f56.png)

Via #1445

**Comment by nicolas17** [comment] 2015-11-14 10:12
Duplicate of #1291? This one has a better title and description though.

**Comment by richlv** [comment] 2015-11-14 17:21
actually a duplicate of an even older #1222 ;)

**Comment by nighto** [comment] 2015-11-16 22:13
Sorry. Should I close this and add the description as a comment on #1222?

**Comment by nicolas17** [comment] 2015-11-16 22:38
Leave it to Mapillary staff; I think they can properly mark the issue as duplicate.

**Comment by knikel** [comment] 2015-11-20 15:42
It is now possible to drag rectangles in any direction (controls stay where they were) thanks to @paulinus and @oscarlorentzon!

**Closed by knikel** 2015-11-20 15:42 UTC
