### ISSUE TITLE
Mapillary in Amazon Appstore is outdated

### ISSUE THREAD

**Issue by kardotim** [mapillary/mapillary_issues#2334] opened 2016-10-30 16:18 UTC
The Mapillary app in the Amazon Appstore for Android hasn't been updated for some time, perhaps you can make this part of the release flow.

https://www.amazon.com/Mapillary/dp/B00JCVFOHW

**Comment by gyllen** [comment] 2016-10-31 17:31
@peterneubauer Thoughts on this, was a long time since we thought about the Amazon app.

**Comment by nicolas17** [comment] 2016-11-02 00:42
Duplicate of #1398, and there may be other tickets...

**Comment by kardotim** [comment] 2017-01-11 21:23
@rsahlin maybe you can include Amazon App store in your release flow?

**Comment by rsahlin** [comment] 2017-01-12 10:13
Good point, I definately think we should include it.
The overhead to release on Amazon is really small.
What do you say @peterneubauer ?

**Comment by jesolem** [comment] 2017-01-12 10:16
@rsahlin If easy to do we should IMHO.

**Comment by ovivoda** [comment] 2018-07-06 08:58
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_

**Closed by ovivoda** 2018-07-06 08:58 UTC
Labels: affects-android
