### ISSUE TITLE
 Bad traffic sign icons

### ISSUE THREAD

**Issue by ray66** [mapillary/mapillary_issues#2545] opened 2017-04-24 11:44 UTC
### Basic information
* Platform:  `Web`
* System/Browser: `Linux Debian Stretch, Firefox ESR 45.8.0`

### Steps to reproduce behavior

 1. Click on the "Filter" icon
 2. Activate "Show detected traffic signs"
 3. Zoom out the map until several signs are grouped and represented as a single sign
 4. Click on such a group of signs  

### Expected behavior

A popup with the icons of the individual signs in the group appears and the user can select the sign for which he wants to see the associated image

### Actual behavior

A popup with some "dummy" icons appears. The user can not identify the signs in the group. The icons represent part of the sequence point icons, i.e. an orange circle and a yellow circle segment.

### Additional information

The same dummy icon appears in the traffic sign filter dialogue. 

I cleared the cache and deleted the cookies, no change.

![bildschirmfoto_2017-04-19_09-41-07](https://cloud.githubusercontent.com/assets/4647893/25335530/bad95f84-28f3-11e7-941b-4eeed6f6c635.png)
![bildschirmfoto_2017-04-19_09-41-34](https://cloud.githubusercontent.com/assets/4647893/25335539/c4047bac-28f3-11e7-84ac-b3ebff2b3836.png)

**Comment by GITNE** [comment] 2017-04-24 12:38
I too can confirm this behavior on Firefox 47.

**Comment by gyllen** [comment] 2017-04-28 18:12
Thanks for reporting this is now internally tracked. We will get back to you as soon as it is fixed.

**Comment by nickplesha** [comment] 2017-05-04 14:48
I can see that you are using older versions of Firefox (latest is 52), can you update to the latest version to remove this as the possible culprit? (I can't reproduce this issue on latest Firefox)

**Comment by GITNE** [comment] 2017-05-04 16:33
You can download and install previews Firefox releases easily. Just go to
[`https://archive.mozilla.org/pub/firefox/releases`](https://archive.mozilla.org/pub/firefox/releases). Please note that not everybody can upgrade to the latest version—for various reasons. And, nobody should really consider Firefox 47, released in November 2016 obsolete.

Besides, I don't think this is a bug in Firefox which may have been fixed in later versions because if you look closely, the flag icons are rendered properly, that is the texture coordinates for these sprites are computed correctly. Things get only out of order with sprites at greater coordinates (lower right side of the sprites texture). Well, it's possible however highly unlikely that Firefox versions < 52 may not support non-square textures.

**Comment by GITNE** [comment] 2017-05-05 19:55
I can reproduce this behavior in Firefox 48.0.2 on Windows too.

**Comment by nickplesha** [comment] 2017-05-08 08:24
@ray66 @GITNE This should be fixed now, tested on the versions you mentioned and it seems OK. Let me know if this issue persists and we can reopen this issue.

**Closed by nickplesha** 2017-05-08 08:24 UTC
Labels: bug

**Comment by GITNE** [comment] 2017-05-08 08:55
Thanks! :smile: Things look finally great in Firefox now too!

However, there as some nits, bits, and pieces with some sprites. These turn restriction sprites have a transparent background which should have probably been white. This applies to all regions using these signs.
![broken eu left turn restriction sign](https://cloud.githubusercontent.com/assets/15823872/25797272/c3d42eea-33dc-11e7-8828-0f88fad4916a.png)
![broken eu right turn restriction sign](https://cloud.githubusercontent.com/assets/15823872/25797271/c3d381f2-33dc-11e7-8093-ffdc8bdede94.png)
Additionally, you can spot some duplicates, especially in the EU region. Do you want to fix those in this issue or should I open a new one?

**Comment by nickplesha** [comment] 2017-05-08 10:43
@GITNE Thanks for the feedback! The traffic signs on `mapillary.com` (and soon to be used in `iD` and `JOSM`) are here: https://github.com/mapillary/mapillary_sprite_source Feel free to open an issue there for any incorrect traffic signs you may find.

**Comment by GITNE** [comment] 2017-05-09 20:52
@nickplesha Now, what about the duplicates? IMHO, the duplicates seem to come from a static code issue than a graphics issue.

**Comment by nickplesha** [comment] 2017-05-10 14:34
@GITNE Yes, there are some duplicate signs in the list (lots of signs have different variants due to country-specific differences, and I guess some are totally identical), this issue should also be in the https://github.com/mapillary/mapillary_sprite_source repository.

**Comment by ray66** [comment] 2017-05-22 16:14
@nickplesha Sorry for my late response but I was AFK for two weeks ;) Id upgraded to FF 52.02, cleared the cache, deleted cookies from Mapillary. The icons in the traffic sign filter dialogue are ok now but the issue when clicking on a cloud of signs still persists.
