### ISSUE TITLE
be able to move easier the photo location

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#1374] opened 2015-09-09 10:05 UTC
1- have a bigger map to move the photos
2- think something that would rectify the sequence location out of buildings
3- if the photos are in the building : ask something like "is this sequence indoor?"

**Comment by HolgerJeromin** [comment] 2015-09-09 11:31
kind of duplicate of #637

**Comment by jesolem** [comment] 2015-09-13 08:34
Good input @JLZIMMERMANN - let's track this in #637

**Closed by jesolem** 2015-09-13 08:34 UTC
