### ISSUE TITLE
Clicking on images in the profile activity no longer takes you to the sequence.

### ISSUE THREAD

**Issue by jrcarlsen** [mapillary/mapillary_issues#1216] opened 2015-07-31 06:06 UTC
Go to a users activity page:
http://www.mapillary.com/profile/hantms/activity

Click on an image, and you'll get redirected to:
http://www.mapillary.com/map

**Comment by lordsutch** [comment] 2015-07-31 07:06
Duplicate of #1215

**Comment by knikel** [comment] 2015-07-31 08:29
@jrcarlsen, @lordsutch Thanks for catching this one. It's fixed now!

**Closed by knikel** 2015-07-31 08:29 UTC
