### ISSUE TITLE
"Pending photos" in iOS app unreadable

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#2467] opened 2017-02-24 16:38 UTC
In the iOS app feed, if I have photos still being processed, it shows the number of photos above the feed items. But it's shown in black over dark gray, so it's pretty much unreadable.

![](http://i.imgur.com/aFNTq8F.jpg)

**Comment by millenbop** [comment] 2017-02-27 10:50
Thanks for reporting! I'll fix!

**Comment by millenbop** [comment] 2017-03-30 08:01
Finally got around to investigating this one. I cannot reproduce it on my end. Do you still have this issue?

![screen shot 2017-03-30 at 09 59 40](https://cloud.githubusercontent.com/assets/12835674/24493634/c33f74ba-152f-11e7-88ba-16ce4c3f3004.png)

Closing for now, will reopen and spend more time if this is still a problem.

**Comment by nicolas17** [comment] 2017-04-02 01:59
I didn't upload photos recently, but I did blur photos, and right now the "Pending blurs: 3" message is showing in black, just like in my [first screenshot](#issue-210096569).

iPhone 6, iOS 9.0.2, Mapillary 4.6.10. Tested in jailbreak "safe mode" (all tweaks disabled).

**Comment by millenbop** [comment] 2017-04-02 11:09
Maybe it's an iOS 9 thing. I'll check it out again!

**Comment by millenbop** [comment] 2017-04-02 13:01
Tested it on 9.3 and there the text was in black. Fixed now though, will be out in 4.6.12.

**Closed by millenbop** 2017-04-02 13:01 UTC
Labels: affects-ios, bug

**Comment by robertogb** [comment] 2017-04-13 21:52
I have the same issue in the web.
I was uploading photos but I hadn't click on publish yet when I accidentally closed the tab. I have the same label "pending photos" with the number of photos I was going to upload. I cannot edit the sequence and I cannot publish it.
