### ISSUE TITLE
Emails look weird in Google Inbox

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1766] opened 2016-03-22 14:58 UTC
For some reason, Google Inbox likes to break up these emails. Could be something with the HTML?

![2016-03-22 10_54_54-inbox elliott plack gmail com](https://cloud.githubusercontent.com/assets/1827881/13955905/eefd5fc4-f01c-11e5-920d-fd30bd5da4b1.png)

**Comment by polarbearing** [comment] 2016-03-30 23:07
I don't think we should expect fro Mapillary to adjust their communication to every potential peculiarities of every email client. There is always the option for the receiver to use a sane client that leaves the thinking to the user. 

On the other hand Mapillary has a tendency to overdecorate things in general. In the emails, there are lots of linked images, which show as broken boxes to me because I have remote content switched off as it is dangerous in emails. A single line in ASCII about the number of pictures received would be sufficient for me.

Similarly the mobile app is growing from version to version, and suggestions to provide lightweight versions #1416 remain unheard.

**Comment by pbb72** [comment] 2016-03-31 07:23
@polarbearing I count only 5 images in the upload emails; the top logo image, and the 4 icons for social networks. I don't think that counts as overdecorating. But if you say they should not adjust their communication to every potential peculiarity, then why do you want them to remove those images (adjust their communication) when you block remote images (which to me seems like a peculiarity)?

I don't think GMail counts as "every email client", I think a substantial share of the users is using the GMail webclient.

But I agree they should support users who block remote content in emails better, by providing alt texts for the images.

**Comment by polarbearing** [comment] 2016-03-31 08:15
> when you block remote images (which to me seems like a peculiarity)

No, that is elementary privacy protection and spam fighting, please read here:
[Remote Content in Messages](https://support.mozilla.org/en-US/kb/remote-content-in-messages) or [Privacy basics - Thunderbird](http://kb.mozillazine.org/Privacy_basics_%28Thunderbird%29)

> I count only 5 images in the upload emails

I don't need _any_ image in this email. All I need is the confirmation that all of the 325 frames the app had promised to upload have arrived, and maybe a link to the sequence.

**Comment by HolgerJeromin** [comment] 2016-03-31 12:05
I do not need the images, but i like them.

**Comment by angelday** [comment] 2016-06-01 07:46
We will be revorking our HTML templates as we go forward. I noted that you prefer less images and are interested in getting feedback on your uploads in an easy to see, convenient way. With regards of Gmail: we will investigate that issue with the new emails, but thanks for the tips (make every email unique so that Google won't group them).

Let me know if you have further questions. In the mean time, I'll close this issue.

**Comment by pbb72** [comment] 2016-06-01 14:09
Please don't close issues before they are actually fixed. Or are the new templates already deployed?

**Comment by angelday** [comment] 2016-06-02 11:14
@pbb72 Reopened and will be closed when the issue is fixed. Sorry for the confusion!

**Comment by talllguy** [comment] 2016-07-27 19:28
![image](https://cloud.githubusercontent.com/assets/1827881/17189265/bb2df5c2-540e-11e6-990e-54ae1d747690.png)
The emails look much better lately.

**Comment by talllguy** [comment] 2016-07-27 19:28
Although that map does look a bit odd.

**Comment by angelday** [comment] 2018-07-27 15:49
We have a new template, closing.

**Closed by angelday** 2018-07-27 15:49 UTC
Labels: affects-backend-notifications, feature
