### ISSUE TITLE
Repeated crashes

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#1677] opened 2016-01-27 08:06 UTC
In the most recent version on iPhone, I have had now 6 crashes in a sequence, while taking photos. I am unable to take sequences much longer than a 100 photos before the app crashes.

**Comment by millenbop** [comment] 2016-01-27 15:57
Hi! Thanks for reporting! Sorry to hear it crashes!

Which iPhone do you have? 
Which iOS version do you have installed? 
How much free space do you have on your phone? 
Do you know when the problems started, i.e. has it worked before?
Is there a difference if you hide the map in the camera?
Tried restarting the phone?

(for testing purposes, if needed, just choose walking auto, set it at the shortest interval, and just let it take pictures of something, but don't upload them)

**Comment by Virtakuono** [comment] 2016-01-27 16:04
iPhone 5 32G, iOS 9.2.1 (13D15), around 17 GB free space, i Did restart, I've seen crashes with the camera view and the map view and first time this happened was January 22. I don't exactly remember if this was after or before updating the app (is there even a log to check this?), but I generally update all my apps in the same day I get a notification. Hope this helps.

**Comment by Virtakuono** [comment] 2016-01-27 16:05
And, in case this is of relevance, I've witnessed this with both riding and walking mode.

**Comment by Virtakuono** [comment] 2016-01-29 10:04
I took it out for a spin today and witnessed three crashes more, it seems that I get beyond 150 photos at a time, but not consistently. Also the camera focus bug seems to pester me, but I guess I'll post more about that in a separate issue...

**Comment by richlv** [comment] 2016-01-29 18:24
some crashes seem to happen more often with the interval set to 1 second and when it's a bit darker. @nicolas17 suggested it could be caused by the camera taking longer to focus/take the photo

**Comment by Virtakuono** [comment] 2016-01-30 17:29
The photos I took yesterday were in bright sunlight, I doubt that those crashes have much to do with it being too dark. I can try out later if it changes anything to have 2 second intervals.

**Comment by millenbop** [comment] 2016-01-30 17:35
could you try setting it at like 4 second intervals and just leave it running for a while if you are not using the phone? to see if has to do with the capture rate or the number of photos taken.

**Comment by Virtakuono** [comment] 2016-01-30 17:39
Well that was easy, took the phone out and it crashed after the first photo when set to 4 seconds :)

**Comment by Virtakuono** [comment] 2016-01-30 17:40
Oh, correction: before the first photo.

**Comment by millenbop** [comment] 2016-01-30 17:41
lol ok :) I get crash logs sometimes, but the latest ones have mostly been complete gibberish, trying to figure out which ones are yours (they are anonymous). Is your phone jailbroken?

**Comment by Virtakuono** [comment] 2016-01-30 17:41
Nope.

**Comment by Virtakuono** [comment] 2016-01-30 17:47
Does this help you any?
--
Juho Häppölä
juho.happola@iki.fi

Sent from my phone,
Sorry for brevity, typos and top posting.

**Comment by Virtakuono** [comment] 2016-01-30 17:50
![2016-01-30 20 45 57](https://cloud.githubusercontent.com/assets/3048065/12697405/22498ec8-c793-11e5-8fda-18ca02a870ac.png)

Does this help you any?

**Comment by millenbop** [comment] 2016-01-30 17:51
No, sorry, they are completely anonymous. another thing to try, can you test with airplane mode on? so it doesn't use any network and can't load the map. grasping at straws here :)

**Comment by Virtakuono** [comment] 2016-01-30 17:52
IIRC the airplane mode switches off the GPS as well and the "start" button goes inactive...

**Comment by millenbop** [comment] 2016-01-30 17:52
Looks like something goes wrong either when it tries to create the jpeg from the data buffer or when trying to write it to a file. But that code hasn't changed in 6+ months :/

**Comment by millenbop** [comment] 2016-01-30 17:52
Ah maybe your right, but it doesn't look like it's map related

**Comment by nicolas17** [comment] 2016-01-30 18:02
To get your own crash logs on a non-jailbroken device:

1. Make it crash
2. Sync device with iTunes on a computer
3. Get the log from `~/Library/Logs/CrashReporter/MobileDevice/` on Mac or `C:\Users\[Your User Name]\AppData\Roaming\Apple Computer\Logs\CrashReporter\MobileDevice\` on Windows.

**Comment by Virtakuono** [comment] 2016-01-30 18:27
[Mapillary-crash-reports.zip](https://github.com/mapillary/mapillary_issues/files/110927/Mapillary-crash-reports.zip)

It turned out I have a few files in said folder. I hope nobody can buy crap from app store on my tab or something else malicious using these logs...

**Comment by nicolas17** [comment] 2016-01-30 22:05
Looking at Virtakuono's crash logs, I see some completely different crashes. Some (like all from 2016-01-29) are related to the map, as there is OpenGL stuff. Many of the crashes are related to the upload error handler. There is one (2016-01-22 18:10:19) coming from the thumbnail creation.

None seems to match the photo-saving crashes that I have gotten myself. I haven't yet seen @richlv's crash logs, so I don't know which one he's getting. Maybe it's a 5th different cause :)

**Comment by Virtakuono** [comment] 2016-01-31 05:32
Yes, the older crashes probably have nothing to do with this current issue, but I included them just for the heck of it...

**Comment by richlv** [comment] 2016-02-01 04:03
has a crash in the manual walking mode, taking one photo.
is there a way to get crash logs w/o itunes ?
i found https://www.quora.com/Is-there-way-to-get-or-send-crash-logs-from-my-iPhone-or-iPad-wirelessly-without-syncing-with-iTunes-first , but that's so messed up and inconvenient...

**Comment by Virtakuono** [comment] 2016-02-02 05:24
I took the phone out for a spin before the sun was up this morning, dark or not, it seems to crash pretty much constantly.

[Mapillary crashes.zip](https://github.com/mapillary/mapillary_issues/files/113434/Mapillary.crashes.zip)

I noticed a funny thing that might, or might not be relevant for the crashes. Each time the app crashes, it seems to change the way the map is being drawn. If it draws coloured balls and crashes, the next time it draws a black line, and if the app is drawing a black line, it goes back to drawing coloured balls after the next crash.
![img_8471](https://cloud.githubusercontent.com/assets/3048065/12740664/6457ff12-c986-11e5-87bc-528932a43e7a.PNG)
![img_8472](https://cloud.githubusercontent.com/assets/3048065/12740663/645809d0-c986-11e5-8fa0-4027b4b61732.PNG)

**Comment by millenbop** [comment] 2016-02-02 19:17
Thanks for the crash logs guys, looking into it now.

**Comment by millenbop** [comment] 2016-02-02 22:15
Would you guys email me with your email addresses? You can email me at anders@mappy. I wanna do a TestFlight release that you can check out and see if you still get crashes. It does two things:

- when map is hidden, it is destroyed and freed, there should be no map code running at all. when it is displayed again, it is recreated.
- I've downgraded Mapbox to 2.1.2 from 3.0.1 as 3.0.1 has a severe memory leak it seems

So, when you get the build, please first try with map enabled. If it crashes, please try with the map hidden. If it still crashes then, it's probably not the map causing it.

**Comment by talllguy** [comment] 2016-02-02 22:32
@millenbop I suspected Mapbox might be at issue, because when I switch from the full map view (while recording via GoPro), to mini-map view, the crashes become much less frequent.

**Comment by Virtakuono** [comment] 2016-02-04 06:50
I had a chance to try out your test build this morning for a brief while. At least it did not crash in the brief time it took me to walk to work. I'll give it another spin on the weekend...

**Comment by Virtakuono** [comment] 2016-02-05 11:26
Ookay, I took the test build out and crashed it four times now. Whatever @millenbop did, it did not fix the issue. Furthermore, the app sporadically left gaps on the map, not drawing yellow and green balls here and there, and drawing black line instead. I wonder if this is related.

**Comment by millenbop** [comment] 2016-02-08 17:05
Did you try it with the map completely hidden?

**Comment by Virtakuono** [comment] 2016-02-09 07:05
Yes, but it did not crash in that mode.

**Comment by richlv** [comment] 2016-02-09 20:27
while definitely not map-related, i have had the app also crash a few times during the uploads. i still don't know of a sane way to get the crashlogs off the device w/o installing things on the computer :)

**Comment by Virtakuono** [comment] 2016-02-10 06:58
I took the app out for another spin yesterday evening. Still no crash in map hidden mode.

**Comment by talllguy** [comment] 2016-02-11 01:17
Just went out and shot 1,729 photos with the dev release on Testflight. Crashed a bunch. Here is the report.

* Camera: External, GoPro Hero4 Silver
* Phone: iPhone 6+
* Map Mode: off

The app would crash intermittently in the following way. The current picture would simply get "stuck" on screen. No buttons on the app respond at this point. I'd go to Apple launch pad home screen and relaunch app. Still on the stuck part, then it'd crash. Restarting the app seems to have fixed it.

Another couple time the camera would simply lose connection with app. The app would go back to the regular iPhone camera view. I'd go to the app home screen and then back to the camera and then it would reconnect.

Finally, when I was transferring photos to the computer, I received this error about four times, halting the transfer. I was able to recover the transfer but this was disturbing at first. :sweat: 
![2016-02-10 18 03 40](https://cloud.githubusercontent.com/assets/1827881/12967277/3a5906b2-d033-11e5-84b7-39b59dd03f64.png)

**Comment by Virtakuono** [comment] 2016-02-11 18:48
Tonight I got a plethora of crashes, every time I tried to take a photo, the app crashed before it could save it. @millenbop did you get the logs?

**Comment by millenbop** [comment] 2016-02-11 19:22
Sorry for not replying sooner, I have been at home with fever and a cold.

@Virtakuono 

>> Did you try it with the map completely hidden?
>> Yes, but it did not crash in that mode.

That's excellent news actually, it means that it is map related. Only got one log, I could see some traces of MBGL there (which is MapboxGL).

I'm going to upgrade to the latest beta release of MapboxGL and see if that makes any difference.


@talllguy 

Did you have map enabled? Which GoPro speed were you using? The 1.5s vs 0.5/1.0s are using different implementations.

**Comment by Virtakuono** [comment] 2016-02-11 19:27
@millenbop That _was_ excellent news. But in fact, tonight I ran it without map and it still crashed...

**Comment by talllguy** [comment] 2016-02-11 22:01
@millenbop no map enabled, 1.5s.

It often felt like the wireless data connection couldn't keep up. I would be fine with a "no view" view where it just gave me a status that the thing was taking pictures, if that could lower the throughput.

**Comment by nicolas17** [comment] 2016-02-11 22:03
I think there are several totally unrelated crashes going on here. Ideally we'd have different issues for each, but it's hard for y'all to know which one you're getting...

**Comment by Virtakuono** [comment] 2016-02-11 22:06
@nicolas17 Agreed. Figuring out what is going on is not too easy, even figuring out which version of the app I have took me considerable time...

**Comment by talllguy** [comment] 2016-02-11 22:12
OK I suspect my GoPro issues are unrelated and will fork out of this conversation. :)

**Comment by millenbop** [comment] 2016-02-14 23:23
@talllguy If you use 0.5s or 1s it will use much less network traffic. You will not get a preview picture but you will still get number of photos left and battery status, and the screen will flash as usual. Please give it a try if possible.

**Comment by talllguy** [comment] 2016-02-15 01:42
@millenbop excellent I'll try that next time I go out!

**Comment by talllguy** [comment] 2016-02-22 13:27
@millenbop Finally had some good weather :sun_with_face: for a run. Used the 0.5 sec mode on the GoPro and got through an entire sequence with nearly 1,000 photos and no crashes or freezing! :grinning: 

:arrow_up: Uploading now, we'll see how it looks.

**Comment by talllguy** [comment] 2016-02-22 15:00
[Here it is](http://mapillary.com/map/im/gwy3I3kmd_hzthY2bY33ew?autoplay=true)

**Comment by millenbop** [comment] 2016-02-23 11:23
Good to hear!

**Comment by Virtakuono** [comment] 2016-03-28 06:43
I now tried it with the most recent update and it still crashes. Apparently the update did not do the job :(

**Comment by millenbop** [comment] 2016-03-29 12:17
There were no updates that tried to remedy any crashes in this release. I'm now back at the office and have access to older iPhones (5 and 5s). If I can get it to crash, I can fix it, otherwise I have no idea where to start looking as it appears to only affect a handful of users and seems random.

**Comment by millenbop** [comment] 2016-03-29 12:56
Great news, it crashes on my iPhone 5. Investigating...

**Comment by Virtakuono** [comment] 2016-04-29 14:26
I purchased a GoPro recently and tried with it. Still crashing, with the most recent testflight version. One instance where I can make the app crash _consistently_ is that whenever the gopro app says "there was a problem connecting to your GoPro" the mapillary app seems to be guaranteed to crash.

**Comment by millenbop** [comment] 2016-04-29 14:39
I'm in the process of rewriting the whole image/EXIF/sync implementation which I hope will pretty much end up 100% crash free. The crashing on iPhone 5 is reproducible and known.

**Comment by millenbop** [comment] 2016-06-15 09:32
The new camera implementation (V2) should fix these issues as we don't write any EXIF data into the images at capture time anymore but instead when images are uploaded, which the system is under a lot less stress. Closing for now, if problem persists, please let me know.

Update should be out in a few days.

**Closed by millenbop** 2016-06-15 09:32 UTC
Labels: bug, in progress, iOS

**Comment by kaitu** [comment] 2016-06-16 19:06
@millenbop 
not having EXIF GPSLatitude, GPSLongitude, GPSAltitude tags written anymore is a major drawback for any pre-upload processing of the photos, and for many collateral uses as well. 
Are you going to release an external tool or an option within the app to bulk add EXIF tags from the mapillary tag after shooting time? 

I currently use correlation to a gpx track, but it's a chore to remember to record the track every time, and still I must rely on GPSImgDirection Exif tag (which thankfully is still there).

**Comment by millenbop** [comment] 2016-06-16 19:32
There will be a button for adding it post capture.

**Comment by kaitu** [comment] 2016-06-16 19:51
Excellent, thanks!

**Comment by millenbop** [comment] 2016-06-17 07:06
It looks like this:

![slack for ios upload](https://cloud.githubusercontent.com/assets/12835674/16143016/5f93a05e-346a-11e6-832a-6bea74378ffc.jpg)

So the top left button adds our tags to all the photos that needs it, and the top right button both add our tags and uploads photos.

**Comment by nicolas17** [comment] 2016-06-18 00:49
I remain skeptical about this approach (writing metadata in a separate file and adding it to the photos later). Adding the EXIF metadata should take a negligible proportion of the time needed to save each picture...

**Comment by millenbop** [comment] 2016-06-22 12:31
It does take some time (and resources) as image buffers unfortunately has to be copied when adding EXIF data and writing it. We have also seen crashes here in some cases which I haven't been able to solve. By separating the files it should be more stable, and on an iPhone 6 I have managed to get up to 4 fps, or in other words, twice as fast as the current implementation.
