### ISSUE TITLE
make email links make more sense

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1990] opened 2016-07-02 06:26 UTC
the links in emails are very obscure - they're all some "sendgrid" stuff.
blur emails, photo comment emails and others - as i'm not displaying remote images, it is quite hard to guess what's what. it is quite annoying to open a few links until hitting the interesting one.

please make these links meaningful so that i would know what i get when i click on them - i have a few times given up and just deleted the email :/

**Comment by richlv** [comment] 2016-07-02 06:32
...and having 'text' format emails as a preference would be just aaaawesome :)
checked my settings and couldn't find anything like that.

**Comment by gyllen** [comment] 2016-07-05 18:01
@richlv I agree, we will do a rework of notifications were we will gte this crap out of the way. Thanks for reporting though.

**Comment by HolgerJeromin** [comment] 2016-07-07 18:16
related to #612

**Comment by richlv** [comment] 2018-01-09 13:23
argh. the link situation does not seem to be getting any better. it would be awesome if links could be normal, plain links. links people actually want to click and share.
in the website, for sharing you provide links like https://www.mapillary.com/map/im/waCOHJnn6rfHLRFPVk_xEQ - why are the ones in email terrible and almost designed to make people not click them ?

even worse, for some time email links were using links.mapillary.com .
i tried to open some older links i had... and they fail now. "You have clicked on a disabled link."

please, please, please - remove ugly links with tracking that look like phishing emails. make them stable and not break a few months later. give users links to images, sequences and edits directly, and people will click them more - i have been avoiding many mapillary links because of this issue.

**Comment by richlv** [comment] 2018-01-09 13:25
...like this link where i wanted to check whether i have responded to a comment from @gyllen - http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUjqwGzW6ZEJHVfD8Z5FjsvxY8-2FA7TKjtUqlGLRR-2Bay-2FdKlGDfVhaybUhylPXVALpSY-3D_yA8CAIS1iNKB8pwHbu3cJ5XZOpHl2oVi5DMi1DRMn3d30-2BDvWl8GnFvPjlkZQmWK2IF4rfN-2BdjCiQmC98f6FNBvHNwYYhviySbcxOGnNuRArrf1Ij-2FlXbJY1nio0wixScX8JmFI9bib0MKXNGF8GqVnKA32FcPzMVMfEa-2FG3pYqWNjqEAh-2BQ1L8hs3EDIB-2Blr-2FFY0mGrFAEgEkbqh0Sh7SC1XtUyy5q1Twvej8DM1pIhoQRoQxVzIEPcTSRjk3XmhruWD5ZWVWPYQqNxWe0nLRMtIUdoCNfkKEzDKsRfQDqtDDt6qK7blf0iwkBijzwy

**Comment by gyllen** [comment] 2018-01-09 14:56
@richlv How old is this link and when did you get it?

Reason I am asking is that we had a couple of days last year when the links were disabled.

**Comment by richlv** [comment] 2018-01-09 15:11
that specific one seems to be received at 2017.09.25. 03:59

nevertheless, the main desire is to have links for humans :)

**Comment by sandrauddback** [comment] 2018-01-17 12:25
Hi @richlv ! jumping in as I set up the email program - thanks for the feedback. As you write, the links look like they do because of the email provider (Sendgrid) and there is tracking added for us to learn if the content we put in the email is interesting to people or not. I do understand the contradiction that some people do not want to click on links that make no sense to them.  For now, we will keep the links as they are but I do acknowledge your request and will give this some thought.

Closing this issue for now as no instant fix.

**Closed by sandrauddback** 2018-01-17 12:25 UTC
Labels: affects-backend-notifications, feature

**Comment by richlv** [comment] 2018-01-17 12:34
thank you for the update. the wish to do some tracking is understandable, but a less destructive (for the links) way would be appreciated - for example, https://www.mapillary.com/map/im/fnjS4rYYFsVVEv_YlMckDQ?tracking=cvzsbankkpow200 instead of the incomprehensive lengthy thing :)

**Comment by sandrauddback** [comment] 2018-01-17 13:05
Yes - I completely agree. They are terrible.

**Comment by GITNE** [comment] 2018-01-17 15:22
> As you write, the links look like they do because of the email
> provider (Sendgrid) and there is tracking added for us to learn if the content
> we put in the email is interesting to people or not. I do understand the
> contradiction that some people do not want to click on links that make no
> sense to them.

@sandrauddback The problem is further reaching than this.

* The reasoning here is logically a bit flawed and therefor Sendgrid does not actually work for Mapillary here really well either. You cannot get any reliable or useful information about people's true interests or intentions based solely on the fact that people have either clicked or have not clicked a link. For example, I have been using the links in emails mainly to quickly navigate to a comment instead of doing it manually. Have I been interested in the link? Well, yes, sort of but neither because of the notification email's content nor necessarily because of the content the link referred to. I have been using those links because of usability issues and for historic reasons. Hence, just counting or not counting (probably the majority of cases) clicks on links does not really provide any valuable information except for generating a lot of *noise* data. I do admit that this may be different with advertising clicks/data.

* I do not know how exactly Sendgrid works but if you have to share the user's email address with Sendgrid in order to make this sort of telemetry work then you may be violating either the law or the terms of service. Why? Because in this case you would be handing over personal information to a third party without the user's consent, of course unless the terms of service have a provision which covers that.
