### ISSUE TITLE
webpage edit track and edit blur will loose changed postions

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#756] opened 2015-02-28 17:41 UTC
While editing a track I move some pictures around on the map. I found a picture to edit the blur, I clicked on edit blur, and could edit the blur. But after editing the blurring, the changes of the moved pictures are gone.
Maybe a local cache or uploading changes every 5 min (or less) in a temp cache on server can help?

aceini

**Comment by de-vries** [comment] 2015-03-01 11:42
Duplicate of https://github.com/mapillary/mapillary_issues/issues/366

Work around: open edit blur in new tab

**Comment by knikel** [comment] 2016-06-01 08:59
This will be fixed in the upcoming editor update.

**Closed** 2016-07-21 09:56 UTC
Labels: editor, fe-editor
