### ISSUE TITLE
shooting and turn off display

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1082] opened 2015-06-14 18:46 UTC
Using the app on my bicycle the battery last about 2 hours. Is there a way using the app in background with black display? 
In the settings there is "Process images in background" but this seams to be someting different, I don't know what, your explanation or my english is too bad.

**Comment by de-vries** [comment] 2015-06-15 19:10
Duplicate of #1001

**Comment by jesolem** [comment] 2015-06-17 12:18
Let's track in #1001 - closing

**Closed by jesolem** 2015-06-17 12:18 UTC
Labels: android
