### ISSUE TITLE
Consider moved locations when doing sequence angle correct

### ISSUE THREAD

**Issue by pbb72** [mapillary/mapillary_issues#777] opened 2015-03-04 15:32 UTC
When doing an angle correction for a whole sequence, Mapillary looks at the stored locations of the photos. Instead, it should look at the new positions in the current editing window.

An extreme example: if I have a sequence that goes from north to south, and I do a sequence correction to 0 degrees, all photos will face south. But if I have repositioned all photos so that the sequence goes from east to west, and then do a sequence correction to 0 degrees, the photos will still face south.

**Comment by de-vries** [comment] 2015-03-04 16:36
duplicate of #576

**Comment by gyllen** [comment] 2015-03-04 18:18
closing since duplicate

**Closed by gyllen** 2015-03-04 18:18 UTC
