### ISSUE TITLE
There is no way to check the version of the app

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#689] opened 2015-02-20 15:10 UTC
Since 1.0 there is no way to check the version of the app. Also the [requested] (https://github.com/mapillary/mapillary_issues/issues/602#issuecomment-73485400) version number in the file name of the direct .apk download is not implemented yet. So for people like me, who don't want to infect their device with google services there is no possibility to check if the app is up to date.
Also, IMO it's quite necessary for bug reporting to know the version.

**Comment by floscher** [comment] 2015-02-20 15:33
Duplicate of #683.

**Comment by peterneubauer** [comment] 2015-02-20 20:23
Added to the settings screen in the next version.

**Closed by peterneubauer** 2015-02-20 20:23 UTC
Labels: android, enhancement
