### ISSUE TITLE
Orientation of phone not respected in Capture mode

### ISSUE THREAD

**Issue by mikini** [mapillary/mapillary_issues#2878] opened 2018-03-21 18:14 UTC
### Basic information
* Platform: `Android` 
* Version: `3.121` 
* System/Browser: `Samsung Galaxy S7, Android 7.0`

### Steps to reproduce behavior

 1.Start application
 2.Go to Capture
 3.Turn phone clockwise

### Expected behavior
UI is shown with respect to the users assumed position on the surface of the earth/in metal cage on rubber wheels..
...

### Actual behavior
UI is shown upside/down as if user is a trapeez artist hanging by the legs/has a serious neck problem which would probably impeed ability to operate heavy machinery.
...

### Additional information

... 

![img_0748](https://user-images.githubusercontent.com/1330166/37729146-7794c83c-2d3c-11e8-97de-825aac5a2ec2.jpg)

**Comment by katrinhumal** [comment] 2018-03-23 10:44
Hi @mikini! Thanks for reporting this. Unfortunately, the answer here is that this is intended behaviour for now. Although somewhat inconvenient, it doesn't prevent capture. But it does offer a workaround for the issue that a number of phone models had lots of trouble with images been captured in the wrong orientation. That's why we've fixed the UI for the time being. It's possible that we'll be able to make it "normal" again sometime along the way. It's definitely our hope - but we won't fix it right now so I'm closing this issue.

**Closed by katrinhumal** 2018-03-23 10:44 UTC

**Comment by mikini** [comment] 2018-03-23 13:19
Ok, that might be a sensible trade-off. Thought after 8 months of absence and a new phone that I had left all that rotation mess with previous phones in the dreaded #1892. But we'll roll from here then ;).
