### ISSUE TITLE
Uploader in strange unusable state

### ISSUE THREAD

**Issue by s-tikhomirov** [mapillary/mapillary_issues#2379] opened 2016-11-26 22:52 UTC
### Basic information
* Platform: `Web`
* System/Browser: `Chromium 53.0.2785.143`, `Ubuntu 16.04`

### Steps to reproduce behavior

 1. Go to https://www.mapillary.com/app/uploader
 2. Upload files without location information
 3. Drag some photos onto the map
 4. Make a drag-n-drop-like movement with the mouse (not sure how exactly to reproduce it) 

### Expected behavior

A photo gets moved or nothing happens.

### Actual behavior

The page turns green and does not respond to mouse clicks. The only way out is to reload the page, losing position information submitted so far.

### Additional information

![screenshot from 2016-11-26 23-43-47](https://cloud.githubusercontent.com/assets/7126627/20644404/3dfeb76e-b433-11e6-838e-336a710435d3.png)

**Comment by nickplesha** [comment] 2016-12-09 13:46
@s-tikhomirov Hi, thanks for reporting this issue. Looking at the screenshot, the green background is the visual effect that is shown when you drag-and-drop an image file from a folder on to the browser tab. Can you try reproducing this behavior again? I'm unable to reproduce this issue by just dragging the markers normally on the map. (did you drag off the screen, or switch window focus during it?)

**Comment by s-tikhomirov** [comment] 2016-12-09 14:26
@nickplesha It happens in the following situation: I dragged some photos onto the map, not I want to change the positions of some of them slightly, and instead of drag-and-dropping the image I accidentally double-click on it and then drag-and-drop. I tried to reproduce it, successfully at times. Not sure what is the trigger for such behavior.

**Comment by nickplesha** [comment] 2017-03-22 15:22
@s-tikhomirov I've still been unable to reproduce this issue. I'll close this issue for now and feel free to reopen this if you notice it happening frequently and impeding your interaction with the uploader.

**Closed by nickplesha** 2017-03-22 15:22 UTC
Labels: affects-web-uploader, bug
