### ISSUE TITLE
iOS viewer doesn't stop playing if I navigate manually

### ISSUE THREAD

**Issue by nicolas17** [mapillary/mapillary_issues#1769] opened 2016-03-24 23:13 UTC
In the new MapillaryJS-powered sequence viewer in the iOS app, if a sequence is playing (by pressing the :arrow_forward: icon) and I press an arrow to manually navigate between images, the app properly navigates in the direction I clicked, but doesn't stop playing. For example if I click the arrow to walk one step back, it walks one step back, but immediately continues forwards.

**Comment by millenbop** [comment] 2016-03-25 09:16
@oscarlorentzon I think this is a view issue?

**Comment by nicolas17** [comment] 2016-03-25 13:00
Oh, it's probably in the viewer. I didn't test this on the web because while mjs has the sequence playing functionality, it doesn't have a play button by default, at least not in any of the demos I found.

**Comment by oscarlorentzon** [comment] 2016-03-29 06:35
@nicolas17 @millenbop This behavior is intended. On mapillary.com playing does stop when navigating in any direction. In `mapillary-js` we decided to change this. Now when playing, you can navigate wherever you want by clicking the navigation arrows. Playing will then continue forward in the sequence of the image you navigated to. To stop playing in `mapillary-js` you need to actually press the stop button (call the stop method on the PlayerComponent). In the `mapillary-js` way you can play through multiple sequences by navigating whenever you want.

**Comment by millenbop** [comment] 2016-03-29 10:06
Ok, thanks @oscarlorentzon, since this is by design and we want to keep the web and the apps the same for as many features as we can, closing this for now. Perhaps the design will change in the future :)

**Closed by millenbop** 2016-03-29 10:06 UTC
Labels: bug
