### ISSUE TITLE
Web Uploader consumes too much memory

### ISSUE THREAD

**Issue by james2432** [mapillary/mapillary_issues#2455] opened 2017-02-10 13:51 UTC
### Basic information
* Platform: `Web`
* Version: `Current` 
* System/Browser: `Windows/Firefox`

### Steps to reproduce behavior

 1. Upload a sequence via the browser
 2.  (More than a 1000 photos)
 3. Will cause an out of memory exception as it just consumes more and more memory

![image](https://cloud.githubusercontent.com/assets/498547/22828933/e1d1898c-ef6d-11e6-9c9b-2e4988b8a50f.png)

### Expected behavior
Unused variables are nullified and can be sent for garbage collection

### Actual behavior
Memory used keeps growing and will crash the browser

**Comment by jidanni** [comment] 2017-02-21 00:02
Even just browsing it while not logged in cannot be attempted on anything other than a Cray.

**Comment by james2432** [comment] 2017-02-21 13:57
Seems the more zoomed out you are when you are uploading(took photos over great distance) it loads stuff in the background(I'm assuming tracks in that region) as I zoomed in really close to a node and doesnt cause that issue. Why is the uploader preloading/loading tracks?

**Comment by polarbearing** [comment] 2017-12-27 14:55
Any action on this issue? Just reported in #2616 how my upload failed when consuming 1.2 Gigabytes after a few uploads. 
Just starting www.mapillary.com/app/uploader with showing the "Browse Files" request costs 346 MB. 
Preparing 283 images, we are at 550 MB. The process consumes 55% CPU power, just for transferring a few bytes  over a thin upload line, and having the icons on the webpage flicker.

**Comment by polarbearing** [comment] 2017-12-27 17:47
Unable to upload the chunk of 283, always stuck after 1...3 images.

**Comment by nickplesha** [comment] 2017-12-27 20:54
@polarbearing Can you upload a screenshot of the browser error console when this happens? There could be an error message that would help us diagnose the issue.

**Comment by polarbearing** [comment] 2017-12-28 13:05
Memory grew from 500 MB to 1.3 GB during the attempted upload of 223 pictures, stuck after 58 pictures as in #2839. 
Error console appears to be unrelated to memory consumption:
```
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (this-is-inlined-already.css, line 0) https://www.mapillary.com/this-is-inlined-already.css
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (undefined, line 0) https://www.mapillary.com/undefined
```

**Comment by nickplesha** [comment] 2017-12-28 16:26
@polarbearing Thanks for the extra investigation! The second error message is concerning, can you attach some of the images that you're trying to upload so I can try to reproduce this?

**Comment by polarbearing** [comment] 2017-12-28 23:45
The stuck upload as in #2839 appears to be unrelated to the memory consumption in the browser. It does not happen with a particular image. As @katrinhumal said there are problems with the backend. I switched to OSM layer now which consumes less in the browser, but it does not help with the stuck uploads.

**Comment by katrinhumal** [comment] 2017-12-29 10:26
The backend problems that I suspected should be resolved now so if it still gets stuck, it's likely something else. @nickplesha surely has a better guess than me.

**Comment by polarbearing** [comment] 2017-12-29 22:36
It is certainly not a particular image, since all images can be uploaded eventually.

**Comment by gyllen** [comment] 2018-07-20 07:24
@nickplesha Moving to you for decision

**Comment by nickplesha** [comment] 2018-07-20 08:47
We're continually improving the performance and memory usage of the uploader. This is an issue we're tracking internally and we will be working on it in the future.

**Closed by nickplesha** 2018-07-20 08:47 UTC
