### ISSUE TITLE
Weekly mails too competitive: quantity vs. quality?

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1241] opened 2015-08-04 07:30 UTC
I have several issues with these weekly mails, encouraging users to focus on quantity instead of quality. 

> Your most popular photo was viewed 23 times!

I try to map the streets in my area systematically, even if they are boring. 
We are not creating fine art here, though I look for technical quality. 

> 3439 meters mapped last week 

So what? I am not competing for mileage. I am trying to deliver quality. 
I don't upload a sequence that has bad reflections in the windscreen, or road features not recognisable due to strong contrast. 
I also go for a walk, thus less meters, providing high-quality frames of areas no G***** car has ever been. 

> You are only 103 mapping minutes (3 114 photos) away from reaching k*5000 photos!

I am not hunting for milestones. 
I enjoy, however, that the roads in my area fill up with the effort of my fellow mappers and myself. 

> You can do it! 

Yes, I could upload all sorts of rubbish, or doing the same main road every day, 
but I don't give a penny on being cheered by a python script!

**Comment by filipca** [comment] 2015-08-04 07:53
There is also a sense of urgency.  Better something than nothing.
I made 300.000 pictures with a 50 degrees angle of view and a time interval of 2 seconds.
This means that I can start all over again.

**Comment by filipca** [comment] 2015-08-05 07:40
Be happy that they don't start a badge merit system as some folks suggest.
There is a Google discussion forum for these rather emotional issues, but I don't use it because it notifies me with SMS messages.

**Comment by AllenGraetz** [comment] 2015-08-05 14:23
While I agree with your sentiments Polarbearing, as you know, it's all dependent on an assumption ---> quality IS always better than quantity.   But better for what?

If you're trying to systematically detect road signs, pavement quality, some fancy thing like auto detecting where food trucks are located or whatever, fresh data is much more important than perfect data.

**Comment by AllenGraetz** [comment] 2015-08-05 14:24
That said, what could be done to celebrate the good stuff?   Allow users to showcase their favorite images on their profile?   A traffic sign-esque game that allows people to rate the most interesting photos?   

Or maybe some means of pointing out "congrats users, the entire village of St. Mary's Point, MN has been mapped"?

**Comment by richlv** [comment] 2015-08-06 03:19
this is not the best place for long discussions, but i'd guess that from mapillary's perspective currently quantity > quality.
coverage is very spotty or missing in many countries/cities, and getting something in place is useful - one could see how some place looked like a year, two or ten ago. then it all could be improved by adding higher resolution photos at better angles and lighting.

if the desire is to have better motivational tools, that would probably be best split out in individual issues with specific suggestions that mapillary could implement or shoot down (i like the idea about users showcasing their best photos/sequences on the profile page) - other than that, maybe an option not to receive the weekly stats email ? :)

**Comment by jesolem** [comment] 2015-08-06 06:28
@polarbearing raises an important issue here.

What is more important, taking 80 carefully framed photos walking down a street or 1000 photos from a cheap camera phone mounted on a vehicle? The answer is that both are important. And we want to encourage both.

The problem is that we can only encourage what we can measure. Number of photos, distance mapped, etc are easy to measure and explain. Conversely, “you took x beautiful photos” is very difficult to measure and a machine generated quality score will be a soft measure, not a hard number. These quality ratings are something that humans do very well though and we should look at introducing that. 

Right now the only way for someone to give kudos for quality is by writing a comment. I like the suggestion of @Andblue in #1246

Now for some specific comments:
* @filipca we’re not going for urgency, but to give people milestones of goals to work towards. A lot of people are inspired by these things (compare any fitness app e.g.)
* @AllenGraetz yes, some users of the data, including the OSM editors, prefer the latest photo to the prettiest. 
* @AllenGraetz about measuring coverage, yes, we want to do that too. So people can track the completeness of areas they care about. Requires us to write some tools first though (map matching, and route planning is in the works) 
* @richlv yes, coverage is spotty but we’re taking a long-game approach to this. It will take a years to get to the coverage levels we all want.  
* @richlv you can always turn on/off any notifications on your [settings page](https://www.mapillary.com/map/settings/notifications).

Hope that answers all the comments above. Will keep this issue open for a while longer in case there are others who want to chime in. 

Thanks everyone.

**Comment by moenk** [comment] 2015-08-06 08:14
I'd really like a bit gamefication: User Levels, Badges in the profile for different aspects like milage, mapping time, picture count, rating of pictures, traffcis signs detected, connections, Blur ratio - have a look at games like Geocaching, Munzee or Ingress how they do it.

**Comment by filipca** [comment] 2015-08-06 08:19
The lines on the map are my reward.  
I am in the OSM spirit.

**Comment by filipca** [comment] 2015-08-06 08:21
That daily Instagram tweet, does it have a link to the mly picture, or am I missing something ?

**Comment by mprins** [comment] 2015-08-06 12:01
I think the auto-generation should be a enhanced; the message says: 
 - "38 794 photos uploaded last week"
 - "1521.2 km mapped last week"

 (but only 220 photos or so in NL, most others in France) the message then states 
 - "This week you're number 15 top contributor in Netherlands" 

which is based on the 220 the rest (the large number of other pictures) seem ignored in that report. I think it would make more sense to report on the largest cluster(country) of pics

**Comment by moenk** [comment] 2015-08-06 12:11
@filipca For me the lines on the map are also quite fine (due to some bug they dont show up at the moment?) and I use them for plan where I can ride to.
@mprins I don't need this by mail, some statistics on the profile would be nice. I also think for some people it might be motivating of they know they can achieve badges for visited countries or numbers of pictures, miles, whatever in the profile, example from munzee: http://www.munzee.com/m/moenk/badges/

**Comment by richlv** [comment] 2015-08-06 12:16
mapillary lines not showing up is issue #1196

**Comment by Peatsmoke** [comment] 2015-08-06 19:04
It's seems I'm back on elementary school...
Ik do this job for two reasons:
1) I like it
2) For OSM

Therefore I try to map all kind of roads that aren't visible in Streetview and so far as possible different roads that aren't mapped yet. That's why I prefer to take my bike or make a hike and that this makes me (until now) nr 1 mapper in The Netherlands. nice but I don't take care about that. I do this job to improve OSM!

**Comment by filipca** [comment] 2015-08-07 09:14
I had another look at Munzee and Ingress and I am even more convinced now to say : "no, no, no".
Luckily the folk at mly have enough serious work for the coming years.

**Comment by Hjart** [comment] 2015-08-07 18:24
I find myself annoyed at the gamification and it's focus on quantity. I tried mapping a bit using some sequences made by some of the top Mapillary contributors in Denmark, but found that there was often far too many pics per km and at such a low quality, that I could only stand traversing them for a few minutes before giving up.
If you can somehow shift focus of the gamification more onto quality I would appreciate it. Otherwise I would like to be left out of it. Honestly so far I think I've actually contributed less photos because of it. I just plain do not want to compete on quantity in photos.

**Comment by jesolem** [comment] 2015-08-07 19:53
@Hjart See my comment above. As soon as we can measure quality we will give kudos, encouragement and report on it, but it is a non-trivial problem. We're working on it though. If you don't want the email, you can just deselect the tick-box on your [settings page](https://www.mapillary.com/map/settings/notifications).

**Comment by filipca** [comment] 2015-08-08 09:42
If mly goes that slippery slope, I want a cudos first streak.
But I prefer to have area coverage aid first.

**Comment by Peatsmoke** [comment] 2015-08-10 07:44
@Hjart : That a nice theorem, but what are too many pictures per km? I don't no, maybe @jesolem can  give a answer to clear that?

If there should come kudos or something like that, it would be a good idea to give more kudos for roads and paths which where not mapped before. 
I see some users, daily add the same route (over highway) from home to work and although there isn't a maximum for adding those routes, imo there is no added value for doing this day in day out.
In my opinion Mapillary once startet to go on, where Google Streetview ends. For mapping every day the same way from home to work you shouldn't get kudos, imo.

**Comment by Hjart** [comment] 2015-08-10 08:00
@Peatsmoke , Try using something like the sequences in http://www.openstreetmap.org/#map=15/55.9236/11.9309 for mapping. It's just plain painful. Load the area in JOSM and you'll see that this is little more than a waste of server space and processing time.

**Comment by moenk** [comment] 2015-08-10 08:03
@Peatsmoke I second this, parameters for giving points and badges may be: 
* Making photos on tracks where no one have taken any before
* Rating on the terrain perhaps, off-road-tracks higher than motorways
* Rating on the technical quality as far software can do that (brightness/contrast/blurred)
* Making the first sequence in an administrative border (L8, L9, whichever it might be)
* Rating pictures by hand higher than automatic ones (from variance of timestamp diffs)
There will be more I am sure, just some ideas.

**Comment by filipca** [comment] 2015-08-10 08:47
In a 50 km/h urban area
with my car
with angle of view 50 degrees and 2 seconds interval,
I passed three times in one direction and three times in the other direction.

Still I could not be sure if there was a traffic sign in the sidestreet.

A interval of 1 seconds has the disadvantage that it takes too long to replay the sequences.

There will be a time that cars will continuously capture and transmit pictures.
Mly can prepare for that time.

**Comment by de-vries** [comment] 2015-08-10 08:51
with my bike
with angle of view 175 degrees and 1 seconds interval,
it's still possible to miss things

**Comment by filipca** [comment] 2015-08-10 08:56
I should finally receive my Garmin Virb XE this week.

**Comment by richlv** [comment] 2015-08-20 08:35
i'm a bit less concerned about those emails and more about contributor tools having a bit too many issues. if i'm taking the time to take lots of photos, i'd like the tools to be as helpful as possible. i can only hope that the time is spent on making internal tools more efficient (like blur review software) and algorithms better (like the blurring one :) ).

there are a lot of issues with scripts and the website that make it seem like the focus is somewhere between contributors and viewers - maybe hoping that more viewers will mean more contributors ? but those have their own reports, so i'm not repeating them here.

as for the image quality, i have some sequences that i think are very good, some are worse and some have plain terrible images. why did i upload them ? in most cases. those were the regions where nobody else was uploading much, and was not that likely to cover that segment in near future. i would strive to get better images for more populated regions, usually.

but keep in mind that seeing how things changed can be important, too. when was that construction completed ? when was that building demolished ? these questions can't be answered with mapillary dataset now, but they might be possible in the future. for that to be more useful, i'd expect them to strive for images in un-imaged (not mapped. that's osm, remember ;) ) areas, even if the images are not perfect. i have uploaded very dark and blurry images for some regions where you can barely see "oh, there's a bridge"... because i'm still the top (or second. toplists broken right now :) ) contributor in that country after spending a week there half a year ago.

as for images being useful for mapping - yes, that is very good if they are useful for mapping. but that is not the only goal. just seeing how a place looks like could attract a viewer, who could turn into a contributor later. regarding the area @Hjart mentioned, i would not denigrate the contributor there. first, i was no there. i did not take images. i did not take time to upload them. how could i criticise them ? the images being there do not seem to do any harm, but actually do show how the place looked some time ago. if somebody comes later and adds new, better images, great - we will be able to compare how some areas developed. and, actually, the images can be used for mapping - roads, surfaces etc :)

mapillary probably could add lots more statistics for contributors - like how many and which countries one has submitted images for (encourage travel :) ), how many days in row max one has submitted, longest trace, most obscure place (most distant from all other traces or map data) and so on. as in, less ratings, more statistics that could still motivate contributors. maybe they could even throw the stat code on github and allow others to create all kinds of interesting views.

but all that probably needs a bit more community guidance planning behind the scenes with target audiences, goals and paths plotted before spending too much time on it :)

(and i'm sorry for such a long post. if you read it all, i'll buy you a beer if i meet you).

**Comment by jesolem** [comment] 2015-08-20 08:47
@richlv I read the whole thing!

Agree on your points here and we are working hard on making the tools and apps better to increase quality (and reward it, as was the original point of this issue). 

We're taking all your feedback into account when we're prioritizing work and we're cranking out updates/fixes as fast as we can. Stay tuned.

**Comment by richlv** [comment] 2015-08-21 10:52
@jesolem the beer will come, one day :)
btw, one issue might be that the contributors don't see the work behind scenes - it all is silent, then some changes appear. it might soothe some minds if there were more status updates (pure PR) - the recent twitter image with traffic signs seems to show somebody else thinking the same :)

**Comment by jfburke3** [comment] 2015-08-24 03:40
+1 to all of this. 

I *know* some of my images suck. But they're better than nothing, which is what was imaged before. If I get the chance to go back through some of these rural, out-of-the- way areas, I'll try to remember to hide my bad sequences. 

@jesolem, y'all are doing a great job. Just keep up the good work.

**Comment by jesolem** [comment] 2015-08-26 12:31
Closing this thread. Please continue the discussion on the newly created forum, http://forum.mapillary.com/t/your-mapillary-week-in-numbers-emails/52

**Closed by jesolem** 2015-08-26 12:31 UTC
