### ISSUE TITLE
Blur doesn't work correctly on 16/9 pictures

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_issues#1163] opened 2015-07-19 07:57 UTC
See this one, and try to blur the car number on the left : 
http://www.mapillary.com/map/b/SjSkz2o3rgIj6st2VJDsbA

**Comment by richlv** [comment] 2015-07-19 16:29
isn't this the same as issue #787 (and all the issues referenced in there) ?

**Comment by domdomegg** [comment] 2015-07-19 18:48
Another duplicate of:
#157 #232 #389 #494 #553 #787 #1063

**Comment by knikel** [comment] 2015-07-20 07:35
This one and all the referenced issues will be fixed in the new viewer. Bear with us :wink:

**Comment by knikel** [comment] 2015-07-30 15:04
The viewer is out, this is addressed now. Thanks @Stefal!

**Closed by knikel** 2015-07-30 15:04 UTC
Labels: bug, new_viewer, web
