### ISSUE TITLE
iOS "TrueHeading" identical 89 degree on all images

### ISSUE THREAD

**Issue by geowOSM** [mapillary/mapillary_issues#2465] opened 2017-02-19 18:44 UTC
### Basic information
* Platform: `iOS` 10.2.1
* Version:  4.6.6
* device: iPhone8,4 (SE)

### Expected behavior
Captured images should contain valid heading information.

### Actual behavior
Checking images before uploading on my phone I noticed that all images seems to have the same heading (directional arrow to the East), regardless of which direction I was traveling.

Photos taken by the photo app always has valid heading data.

So I saved several images from Mapillary to my Mac and realized that all images appears to have identical TrueHeading of 89. Here is an extract from the caption field, which is written by Mapillary:
 "{"MAPCompassHeading":{"TrueHeading":89,"MagneticHeading":330.2007,"AccuracyDegrees":20},"MAPVersionString":"4.6.6"

MagneticHeading varies from image to image, but appears to be incorrect as well.

_Addition: Images were taken from a car, traveling at 30-80 km/h. I would have expected that heading information is primarily extracted from the magnometer compass at low speeds and gps data is used at higher speeds._

Best regards
geowOSM

**Comment by millenbop** [comment] 2017-02-20 10:55
If you are using the camera in the phone we always use the compass. However, it will mostly be wrong in a car due to being inside a metal cage and that messes up the compass. So in a car it would always be better to just use the GPS values and smooth them out over time.

We are reworking the camera UI and we have this in mind while doing so. I'll get back to you.

**Comment by geowOSM** [comment] 2017-02-20 21:00
Thanks! Just to put it clearly, _all images_, even the ones I took while walking outside, _carry the fixed TrueHeading=8_9. I know I could adjust this manually before uploading, but that would be kind of annoying with hundreds of photos. 

Should I wait for a fix before uploading images with invalid heading data or will this issue be resolved on the server side by deriving heading from GPS coordinates and time stamps?

**Comment by millenbop** [comment] 2017-02-21 10:48
You can try calibrating the compass. The easiest way to do this is top open the native Compass app.

If your headings are wrong and they all should be pointing in the direction you are traveling, it's easy to fix in the editor:

<img width="1429" alt="screen shot 2017-02-21 at 11 46 16" src="https://cloud.githubusercontent.com/assets/12835674/23161719/77cafade-f82b-11e6-9fd3-932c640cebea.png">

Just press "Normalize Sequence". If they are supposed to point to some other direction, like 90 degrees to the right, you can use the "Set Offset" feature.

**Comment by geowOSM** [comment] 2017-02-21 21:36
> You can try calibrating the compass.

It's already well-calibrated. Photos taken by the native photo app always has valid heading data. I just checked the compass app against my old Ainsworth geodetic compass and the accuracy is on par within1-2° ;)

> If your headings are wrong and they all should be pointing in the direction you are traveling...just press "Normalize Sequence". 

Oh thanks, that makes sense. I'm a newby to Mapillary without any clue what to do.

**Comment by geowOSM** [comment] 2017-03-04 21:18
Just a minor addition: As v 4.6.8 added image direction to the Exif data, the saved direction on all images is - you guessed it - 89° again.

**Comment by millenbop** [comment] 2017-04-04 15:02
Hey just checking in, is this still a problem for you? I'm on a bug spring cleanup, so if you still have this bug I'll try to sort it out this week.

**Comment by geowOSM** [comment] 2017-04-04 20:25
Thanks for follow-up. I must confirm here that the bug remains unchanged in v 4.6.11. All images I took with an iPhone SE, regardless if walking, bicycle riding or driving a car and whatsoever direction I travel, do carry the fixed TrueHeading=89. As mentioned the internal compass of the phone is well-calibrated and images taken by the photo app have valid heading data.

**Comment by millenbop** [comment] 2017-04-05 12:26
I cannot reproduce this error, tried both an iPhone 5s and a 7, iOS 9.x and 10.x. I don't have access to a SE. The values pretty much come directly from the values from the hardware.

What's your username on Mapillary btw? And if you open up the photo in the app, does it display correctly there?

**Comment by millenbop** [comment] 2017-04-05 12:28
![img_5436](https://cloud.githubusercontent.com/assets/12835674/24705426/29029e2c-1a0c-11e7-95e5-89e36a5f8634.PNG)

**Comment by millenbop** [comment] 2017-04-05 12:31
Hmm just thought of something. 89 = -1+90. We normalize the angle to 0-360 degrees so for some reason the API returns -1 on your device, which usually means an error.

**Comment by millenbop** [comment] 2017-04-05 12:35
From the docs:

```This property contains a valid value only if location updates are also enabled for the corresponding location manager object. Because the position of true north is different from the position of magnetic north on the Earth’s surface, Core Location needs the current location of the device to compute the value of this property.```

So maybe it's wrong in the beginning and gets set later on. If you check the end of your sequence, what's the value there?

**Comment by geowOSM** [comment] 2017-04-05 18:44
Check this sequence from today: qvX9S4oTKEIsZuIHYfD0Aw
According to the website all images are displayed with the 89 compass angle

![mapillary_ios](https://cloud.githubusercontent.com/assets/13821303/24720786/8a64e2ec-1a3e-11e7-8a8e-067053f5336a.png)

In contrast a screenshot from the app: Surprise - Heading is correctly indicated as I travelled from NNE -> SSW

![3-img_4167](https://cloud.githubusercontent.com/assets/13821303/24720688/3bb810d8-1a3e-11e7-9941-b78933bdf034.jpg)

Before uploading all images are signaled in the app with the 89 degree direction arrow

![2-img_4166](https://cloud.githubusercontent.com/assets/13821303/24720863/ccdbca3c-1a3e-11e7-8558-84277d3a5ad8.jpg)

**Comment by millenbop** [comment] 2017-04-06 08:10
We do a bunch of stuff behind the scenes to improve positioning and compass direction using other photos available in the area and the way stuff moves between different photos (which we call Structure from Motion, or SfM, more info here: https://github.com/mapillary/OpenSfM).

The viewer uses this corrected direction, that's why it's correct there.

As you can see your compass for some reason returns -1 all the time. This is straight from the API so I cannot understand if other apps don't get -1.

**Comment by millenbop** [comment] 2017-04-06 09:15
Could you try the following please:

- Turn location permissions for the app off, wait a little, turn it back on. See if that helps. If not:
- Turn off Flight Mode, wait a little, turn it back on. See if that helps. If not:
- Uninstall and install the app. Make sure you upload any pending photos first!

No need to upload, just take some photos where you currently are and check the direction in the app.

**Comment by geowOSM** [comment] 2017-04-06 19:11
Thanks, I tried everything what you suggested but unfortunately without success. Even restarted the phone before installing the app again.

I wonder if I'm the only iPhone SE user with this issue. 😉
You might search the image db for an IPTC-caption tag containing "iPhone8,4" and check the heading info there.

**Comment by millenbop** [comment] 2017-04-07 07:14
Thanks for testing!

Good idea, I'll check out some other SE users.

**Comment by millenbop** [comment] 2017-04-07 08:32
I have checked some SE users now and some of them have the same problem as you do. Not all of them though. Our designer has a SE but he's on vacation right now, but I'll debug using that one when he's back in a few weeks.

**Comment by geowOSM** [comment] 2017-04-07 21:51
> some of them have the same problem as you do.

Thanks, gives me peace of mind. ☺️

> Not all of them though.
 
Would you consider it possible  that there is some dependency or interference with other apps using the compass or is this unlikely due to sandboxing?

**Comment by millenbop** [comment] 2017-04-10 11:44
It's _possible_ that other apps can hog the hardware (seen it happen with the camera where it failed to initialize), but I would say it's very unlikely and a restart should def fix that.

**Comment by millenbop** [comment] 2017-06-02 11:30
Finally got hold of a 5C. It has problems with the compass, it's always stuck at 0 degrees. I also checked the compass app, and it's also stuck at 0 degrees. It's running the latest version of iOS.

**Comment by millenbop** [comment] 2017-06-02 11:33
Also checked the map application, doesn't work there either. I don't think there is much we can do about it unfortunately. I think the phone needs to be serviced or there is a bug in iOS.

**Comment by millenbop** [comment] 2017-06-02 11:34
I managed to get it working a short while after toggling location services on/off a few times in different places, but then it stopped working again after a short while.

**Comment by millenbop** [comment] 2017-06-12 12:44
I don't think there's anything we can do apart from waiting for a fix from Apple. Closing.

**Closed by millenbop** 2017-06-12 12:44 UTC
Labels: affects-ios, bug

**Comment by geowOSM** [comment] 2017-06-12 18:43
Hi Anders, as I'm currently on a hiking trip with limited resources I would to ask for a favor. Could you or someone else normalize all my (geow) sequences I uploaded since June, 1? That would be great!

Thanks
Klaus

**Comment by millenbop** [comment] 2017-06-13 09:01
Hey!

Yes, no problem, I fix!

**Comment by millenbop** [comment] 2017-06-14 09:34
I think I've fixed all of them now, might have missed one or two.

Anyway, in the app you can normalize while you capture. Instead of using the compass, select the forward pointing arrow. Each photo will then look at the next photo.

BUT! It doesn't seem to work as it should. I'll file a bug report and fix as soon as possible.

**Comment by geowOSM** [comment] 2017-06-14 21:38
Anders, thanks for your support! 

I actually checked out the new manual selection of shooting angle, but find there was actually no difference compared to magnetic heading. 

Another bug I noticed was the red gps flag didn't disappear, albeit there was a valid fix. Will try tomorow with 4.7.1 Thanks for the quick fix.

Bye
Klaus

**Comment by millenbop** [comment] 2017-06-15 08:55
Yes, those two are known issues and will be fixed as soon as possible. 4.7.1 doesn't fix those though.

**Comment by geowOSM** [comment] 2017-09-18 19:14
Hi Anders, remember me? I have finally managed to get to the root of the strange 89 degree problem (or 269 degree if the camera lens is on the bottom right corner). Luckily the solution is simple 😊 

Tap Settings > Privacy > Location Services > System Services and make sure that Compass Calibration is turned on.

That's all, I confirmed this on an iPad air and two different iPhone SE. Happy again 🍻

**Comment by millenbop** [comment] 2017-09-25 08:24
I remember you! Sorry for the late reply, I have been recovering from surgery.

AWESOME that you found the problem! Wonder why it was turned off though, should be on by default.

Oh well, happy either way that it works!

**Comment by geowOSM** [comment] 2017-09-27 17:16
Compass Calibration is on by default, but some folks (like me 😉) might have disabled it for battery drain concerns. So maybe this setting could be checked in shooting mode and if necessary app should asked for permission to enable it.

Bye and get well soon!
Klaus

**Comment by millenbop** [comment] 2017-10-02 08:32
Good idea!
