### ISSUE TITLE
If mapillary_issues is no longer an active repository, please clearly note that in the README

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2959] opened 2018-07-08 16:04 UTC
In https://github.com/mapillary/mapillary_issues/issues/2884, @ovivoda commented:

> mapillary_issues is no longer an active repository.
> 
> This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

If that is the case for this entire repository and not just for the old issue this was used for, please document that clearly in the repository README and make sure users can read that before submitting new issues.

**Comment by drkludge** [comment] 2018-07-08 16:53
I agree.  Does this mean there is hope that the issue will get fixed or is this a nice way to say that the issue has been killed.

I clearly want to know when the issue is fixed and what release the fix is in. It would be nice if you would just update these tickets with the news.

It does not sound like a very lean process.

**Comment by ulikoehler** [comment] 2018-07-08 19:32
@drkludge As far as I understand the message (I mean "moved to internal tasks list") it might be part of an internal effort on consolidating all the different bugtrackers they have. Which I totally understand based on my own corporate experience. I assume it 

However, this has the (unintended / partially intended) side-effect on making some things way less transparent, especially in the long run.

**Comment by habi** [comment] 2018-07-09 13:20
The [README](https://github.com/mapillary/mapillary_issues/blob/master/README.md) has been updated three days ago.

(Nonetheless I also think the process is not ideal)

**Comment by ulikoehler** [comment] 2018-07-09 14:12
@habi As far as I can see, they only added "mapillary_issues is no longer an active repository."
which is, as far as I am concerned, a) not clear enough and not visible enough to actually keep users from submitting reports here, especially users that are already familiary to the repository.

Proposal: Add it to the issue template: https://github.com/mapillary/mapillary_issues/blob/master/ISSUE_TEMPLATE.md

Relevant commit: https://github.com/mapillary/mapillary_issues/commit/ca39ae454b98366c0814684cfa17b99a84335db0#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by katrinhumal** [comment] 2018-07-09 17:15
We appreciate your input and understanding! The aim is to optimise time use for the Mapillary team so that communication is faster and more dev time is assigned for _working_ on issues. We have not been doing a great job on this using this repo, so we're going to try an alternative.

The issue template has now been updated as well: https://github.com/mapillary/mapillary_issues/commit/c39120e2abefec99a0afd7f65aea17e55cd2b385

**Closed by katrinhumal** 2018-07-09 17:15 UTC

**Comment by ulikoehler** [comment] 2018-07-09 19:39
@katrinhumal Thanks, that works for me. Is the new route to communicating issues just to report it to support@mapillary.com ? (Not that I'm having a lot of issues with the latest versions of the app, it works really well ;-) )

**Comment by katrinhumal** [comment] 2018-07-10 18:07
@ulikoehler Glad to hear it's working well! 💪 
You're correct, all issue reports should go to support@mapillary.com, while discussions, feature requests, and feedback we hope to see on the forum.
