### ISSUE TITLE
Manual upload page shows picture direction rotated by 180 degrees

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1491] opened 2015-11-08 06:52 UTC
I just uploaded the sequence starting with this image:
http://www.mapillary.com/map/im/GRfAWNt_CuxjvqYkeI0upQ/photo

On the upload page the picture direction arrows were pointing backwards towards the west. The EXIF tag in the picture said it was facing at about 87 degrees but the UI indicated about 270 degrees. I tried deliberately flipping the pictures 180 degrees and then the upload page showed them facing the right direction.

After uploading and viewing the sequence in edit mode, the direction was correctly processed and stored so it is just the map on the upload page that is flipping them.

**Comment by de-vries** [comment] 2015-11-08 08:24
duplicate of #1458

**Comment by peterneubauer** [comment] 2015-11-08 15:31
Bug found, will be out soon. Thanks!

**Comment by ToeBee** [comment] 2016-07-27 02:38
Yeah I think this was fixed a while ago.

**Closed** 2016-07-27 07:38 UTC
Labels: affects-web-uploader, bug
