### ISSUE TITLE
Incorrect deletion in preview if user swipes back

### ISSUE THREAD

**Issue by s-tikhomirov** [mapillary/mapillary_issues#1130] opened 2015-06-30 00:18 UTC
(talking about Android app here)

Suppose I have photos in sequence: A-B-C-D. I want to delete B and press "delete", B is deleted, C is shown. If then I swipe back, I see B again! Now it's easy to asume that something went wrong with deletion and press "delete" again - but then C will be deleted. Undesired behavior :(

Only if I switch back to grid view and to single photo view again, photos are reorded according to deletion.

**Comment by jesolem** [comment] 2015-06-30 06:59
Sounds like a bug, @peterneubauer will take a look after vacation

**Comment by nighto** [comment] 2015-11-11 12:45
Did someone looked this bug? I can confirm it is still present on current version on Play Market.

**Comment by nighto** [comment] 2015-11-11 12:46
Seems to be related with #680

**Comment by peterneubauer** [comment] 2015-11-11 14:50
Will look into it, sorry for the delay.

**Comment by nighto** [comment] 2015-11-11 15:37
By the way (don't know if related, just found out that) regardless of swiping back, after pressing either arrow to go backwards or forwards on the photos opened on review list, after fifteen or twenty (no hard number) the app crashes.

I'd like to help sending a log. How do I do it?

Thanks.

**Comment by peterneubauer** [comment] 2015-11-11 16:11
You can choose t send a log from the main view in the drawer on the left
side. also, feel free to join the tester program to test the new build
regarding this, https://play.google.com/apps/testing/app.mapillary

**Comment by nighto** [comment] 2015-11-11 16:38
Ok, I'll do that. Thanks.

**Comment by pbb72** [comment] 2015-11-11 19:52
I've noticed this behavior also, but if I go back 2-3 photos (not sure exactly how many it was, but it was not much) after deleting one, and then go forwards again, then the deleted one is really gone. So it seems to me to be a problem with caching.

**Comment by ToeBee** [comment] 2015-12-22 04:32
Oh, so I'm not crazy after all. I actually used the app for once yesterday. (I do most of my pictures with a GoPro) While reviewing I had to delete a good number of them because of focus problems but sometimes when I hit delete, the current picture wasn't deleted but the total number of pictures in the sequence went down. I ended up with several large gaps in my sequences because I didn't know what had actually been deleted. And I also had it crash on me every 5-10 pictures while reviewing. I just sent debug logs your way.

**Comment by ToeBee** [comment] 2015-12-22 04:58
Hmm I think the logs only include stuff after I got done reviewing. I'll have to try to capture this behavior again.

**Comment by ToeBee** [comment] 2015-12-23 00:48
The app crashing is covered in #1555.

As for the wrong picture being deleted, I believe this is actually just a problem with the image being displayed on the screen. The app is correctly tracking which picture you are viewing and which one you want to delete, it's just that sometimes it stops updating the image displayed to the user so you **think** it is deleting the wrong one or just not deleting anything.

I managed to get a screen capture of it happening and uploaded it to youtube:
https://www.youtube.com/watch?v=j1n0PaEFDXo

The first time it happens is at about 20 seconds. Notice that I had been going forward in the sequence and then went backwards and then the bug hit. This is a fairly reliable way of reproducing it for me. But notice that the number of pictures in the sequence is decreasing and the timestamp at the top of the screen is changing. It's just the picture that is shown to the user that is not updating correctly.

At 25 seconds it briefly fixes itself but then when I try to go to the next picture, the picture display breaks again, this time just displaying nothing. Again, once I start tapping buttons again you can see the timestamp updating but the displayed image just isn't updating. Then at 1:12 it starts deleting the wrong pictures again.

I am about to send over the debug log of this recorded session as well.

**Comment by ovivoda** [comment] 2017-07-24 08:13
@s-tikhomirov @pbb72 @ToeBee Is this still a problem with latest app version in GooglePlay?

If not I would like to close this issue down.

**Comment by s-tikhomirov** [comment] 2017-08-07 15:43
@ovivoda I no longer experience the issue.

**Comment by ovivoda** [comment] 2017-08-07 16:01
thanks @s-tikhomirov 

@pbb72 @ToeBee Any updates on this? Is this one still an issue for you?

**Comment by pbb72** [comment] 2017-08-09 07:51
I'm not using the Mapillary app anymore (since having the screen always on causes numerous problems), so I can't say.

**Comment by ovivoda** [comment] 2018-07-06 08:35
This issue should be fixed in the latest version of Mappillary Android application

**Closed by ovivoda** 2018-07-06 08:35 UTC
Labels: affects-android, bug
