### ISSUE TITLE
Map doesn't show in any browser

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1725] opened 2016-02-28 10:02 UTC
Hi!
I'm running Win7 with Latest Chrome,Latest Firefox and Latest Opera...and map is blank.
I tried cleaning caches, with new portable navigators...and nothing happen.I tried also reinstall flash and java, and nothing happens :(

**Comment by knikel** [comment] 2016-02-28 10:11
Hi @yopaseopor, do you have latest graphics card drivers installed? Do you see _Yay_ when you go to that site http://www.doesmybrowsersupportwebgl.com ?

**Comment by yopaseopor** [comment] 2016-02-28 10:16
Yes, I see Yay.And Yes , my graphic card is running latest drivers.

**Comment by knikel** [comment] 2016-02-28 10:31
Can you see the map here: https://www.mapbox.com/mapbox-gl-js/examples or does it crash your browser?

**Comment by yopaseopor** [comment] 2016-02-28 10:33
My browser does not crash but it is blank, What can I do?

**Comment by knikel** [comment] 2016-02-28 10:39
I'm trying figure out what might have caused this behavior, if the map has been working correctly before. Only thing that has changed on mapillary.com with regards to the `mapbox-gl-js` map was that I updated to latest version (~2 weeks ago). However, if we detect that you have incomplete support for WebGL, you should see a fallback (Leaflet.js) map. Would be great if you could paste your the report that you see in Chrome when you get to that site: http://webglreport.com/ It would help me a lot! Thanks a lot for the feedback, and sorry about these issues.

**Comment by yopaseopor** [comment] 2016-02-28 10:41
✓ This browser supports WebGL 1
Platform: Win32
Browser User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Context Name: webgl
GL Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit
Renderer: WebKit WebGL
Unmasked Vendor: Google Inc.
Unmasked Renderer: ANGLE (NVIDIA GeForce 210 Direct3D9Ex vs_3_0 ps_3_0)
Antialiasing: Available
ANGLE: Yes, D3D9
Major Performance Caveat: No

Vertex Shader
Max Vertex Attributes: 16
Max Vertex Uniform Vectors: 253
Max Vertex Texture Image Units: 4
Max Varying Vectors: 9
Best float precision: [-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2 <https://www.khronos.org/registry/webgl/specs/latest/2.0/>
Rasterizer
Aliased Line Width Range: [1, 1]
Aliased Point Size Range: [1, 8192]
Fragment Shader
Max Fragment Uniform Vectors: 221
Max Texture Image Units: 16
float/int precision: highp/highp
Best float precision: [-2127, 2127] (23)
Framebuffer
Max Color Buffers: 1
RGBA Bits: [8, 8, 8, 8]
Depth / Stencil Bits: [24, 8]
Max Render Buffer Size: 8192
Max Viewport Dimensions: [8192, 8192]
Textures
Max Texture Size: 8192
Max Cube Map Texture Size: 8192
Max Combined Texture Image Units: 20
Max Anisotropy: 16
Uniform Buffers
Coming in WebGL 2 <https://www.khronos.org/registry/webgl/specs/latest/2.0/>
Supported Extensions:
ANGLE_instanced_arrays
<https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays>
EXT_blend_minmax
<https://www.khronos.org/registry/webgl/extensions/EXT_blend_minmax>
EXT_frag_depth
<https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth>
EXT_shader_texture_lod
<https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod>
EXT_texture_filter_anisotropic
<https://www.khronos.org/registry/webgl/extensions/EXT_texture_filter_anisotropic>
WEBKIT_EXT_texture_filter_anisotropic
<https://www.khronos.org/registry/webgl/extensions/EXT_texture_filter_anisotropic>
OES_element_index_uint
<https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint>
OES_standard_derivatives
<https://www.khronos.org/registry/webgl/extensions/OES_standard_derivatives>
OES_texture_float
<https://www.khronos.org/registry/webgl/extensions/OES_texture_float>
OES_texture_float_linear
<https://www.khronos.org/registry/webgl/extensions/OES_texture_float_linear>
OES_texture_half_float
<https://www.khronos.org/registry/webgl/extensions/OES_texture_half_float>
OES_texture_half_float_linear
<https://www.khronos.org/registry/webgl/extensions/OES_texture_half_float_linear>
OES_vertex_array_object
<https://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object>
WEBGL_compressed_texture_s3tc
<https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc>
WEBKIT_WEBGL_compressed_texture_s3tc
<https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc>
WEBGL_debug_renderer_info
<https://www.khronos.org/registry/webgl/extensions/WEBGL_debug_renderer_info>
WEBGL_debug_shaders
<https://www.khronos.org/registry/webgl/extensions/WEBGL_debug_shaders>
WEBGL_depth_texture
<https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture>
WEBKIT_WEBGL_depth_texture
<https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture>
WEBGL_lose_context
<https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context>
WEBKIT_WEBGL_lose_context
<https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context>

**Comment by domdomegg** [comment] 2016-02-28 19:46
Don't know if this is related, but I am unable to interactive with the map except for the zoom buttons (no scrolling zoom/dragging the map or clicking on sequences). Started happening today as well. If you think it's unrelated I'll start a new bug.

My WebGL (Chrome Version 48.0.2564.116 (64-bit), Ubuntu 15.10):

```
Yay

Context Name	webgl
Platform	Linux x86_64
Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Vendor	WebKit
Version	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Renderer	WebKit WebGL
Shading Language Version	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)

Max Vertex Attribs	16
Max Vertex Texture Image Units	32
Max Varying Vectors	31
Max Uniform Vectors	1024

RGBA Bits	8, 8, 8, 8
Depth Bits	24

Max Combined Texture Image Units	192
Max Texture Size	16384
Max Cube Map Texture Size	16384
Num. Compressed Texture Formats	null

Max Render Buffer Size	16384
Max Viewport Dimensions	16384, 16384
Aliased Line Width Range	1, 10
Aliased Point Size Range	1, 2047
Supported Extensions	ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
```

**Comment by mxa** [comment] 2016-02-29 05:13
I had blank maps too, fixed it by allowing cookies from 3rd party domains.

**Comment by Olestas** [comment] 2016-03-08 09:19
Allow 3rd party is allowed...

Still have blank map...
See YAY here
http://www.doesmybrowsersupportwebgl.com/

Blank here too
https://www.mapbox.com/mapbox-gl-js/examples/

http://webglreport.com/
✓ This browser supports WebGL 1
× This browser does not support WebGL 2

Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc.
Unmasked Renderer:	ANGLE (NVIDIA Quadro FX 580 Direct3D11 vs_4_0 ps_4_0)
Antialiasing:	Available
ANGLE:	Yes, D3D11
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	1024
Max Vertex Texture Image Units:	16
Max Varying Vectors:	14
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 1024]
Fragment Shader
Max Fragment Uniform Vectors:	1024
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	8192
Max Viewport Dimensions:	[8192, 8192]
Textures
Max Texture Size:	8192
Max Cube Map Texture Size:	8192
Max Combined Texture Image Units:	32
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

**Comment by knikel** [comment] 2016-03-08 09:40
Thanks @Olestas! Looking further into that

**Comment by Olestas** [comment] 2016-03-08 09:44
Errors from Firefox console

Error: Key already registered
RegistrationHandler</RegistrationHandler.prototype.register@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:27417:23
KeyHandler</KeyHandler.prototype.register@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:27328:13
.controller/setupInteraction@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:12279:35
.controller@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:12443:18
invoke@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:21015:14
$ControllerProvider/this.$get</</instantiate<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:25384:24
nodeLinkFn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:24516:36
delayedNodeLinkFn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:24800:1
compositeLinkFn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:23955:13
publicLinkFn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:23829:30
createBoundTranscludeFn/boundTranscludeFn@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:23974:1
controllersBoundTransclude@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:24579:18
ngIfWatchAction@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:39603:15
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:31832:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:32096:13
done@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26602:36
completeRequest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26792:7
requestLoaded@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26733:1
 lib-6584f42b.js:28553:18

Error: Style is not done loading
styleBatch@https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js:92:59
[45]</Style.prototype<.batch@https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js:90:3956
[83]</<.batch@https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js:166:4039
[83]</<.setLayoutProperty@https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js:166:6520
.link/setActiveMarker@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:16960:13
.link/<@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-0f4a1afc.js:16992:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:31832:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:32096:13
done@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26602:36
completeRequest@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26792:7
requestLoaded@http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-6584f42b.js:26733:1
 lib-6584f42b.js:28553:18

Error in parsing value for 'width'.  Declaration dropped. map
Error in parsing value for 'height'.  Declaration dropped. map
Error in parsing value for 'width'.  Declaration dropped. map
Error in parsing value for 'height'.  Declaration dropped. map
unreachable code after return statement

**Comment by yopaseopor** [comment] 2016-03-12 09:25
I tried a Ubuntu USB distro with Firefox...and it works (mapbox and mapillary), but the problem persists on my normal Win7 x64 , with any latest browser, and latest graphic drivers.I cannot navigate by Mapillary in any map you have in the web. Is there any "legacy mode" ? (at first days with new maps it worked.)

**Comment by Olestas** [comment] 2016-03-22 07:37
Any news? :(

**Comment by yopaseopor** [comment] 2016-03-25 08:12
Please, I need a "legacy" map. I understand my hardware is obsolete and "is my PC fault" but I cannot operate anything with a map here (and big part of Mapillary is map) with my pc with Win7 latest Chrome, latest Firefox,latest Nvidia geforce 250 drivers.
In Ubuntu 15.10 it works... but Ubuntu is not my default system and I used only in emergencies. And I don't want to use Mapillary's web via Android. Please , make a legacy "emergency" map for obsolete machines as mine.

**Comment by SanderH** [comment] 2016-04-14 18:04
Also getting a blank map here on my older PC.

Seeing the following in the Chrome console:
THREE.WebGLRenderer 70

GET https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer/tile/14/8439/5396.pbf 403 (Forbidden) <multiple times>

Error: Key already registered

Error: Style is not done loading

===
And the reports from the WebGL checks:
Yay

Context Name	webgl
Platform	Win32
Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Vendor	WebKit
Version	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Renderer	WebKit WebGL
Shading Language Version	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)

Max Vertex Attribs	16
Max Vertex Texture Image Units	16
Max Varying Vectors	14
Max Uniform Vectors	1024

RGBA Bits	8, 8, 8, 8
Depth Bits	24

Max Combined Texture Image Units	32
Max Texture Size	8192
Max Cube Map Texture Size	8192
Num. Compressed Texture Formats	null

Max Render Buffer Size	8192
Max Viewport Dimensions	8192, 8192
Aliased Line Width Range	1, 1
Aliased Point Size Range	1, 1024
Supported Extensions	ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

===
✓ This browser supports WebGL 1
Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc.
Unmasked Renderer:	ANGLE (NVIDIA GeForce 8600 GT Direct3D11 vs_4_0 ps_4_0)
Antialiasing:	Available
ANGLE:	Yes, D3D11
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	1024
Max Vertex Texture Image Units:	16
Max Varying Vectors:	14
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 1024]
Fragment Shader
Max Fragment Uniform Vectors:	1024
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	8192
Max Viewport Dimensions:	[8192, 8192]
Textures
Max Texture Size:	8192
Max Cube Map Texture Size:	8192
Max Combined Texture Image Units:	32
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context

===
× This browser does not support WebGL 2
which links me to: http://get.webgl.org/ where I see the spinning cube

**Comment by SanderH** [comment] 2016-04-14 19:02
On the same machine using the Edge browser I get the following:
Temporarily switching to software rendering to display WebGL content.

And is able to show the content, but painfully slow. When zooming in, it uses 100% cpu on all 4 cores for many seconds.

It also gives the following error although it doesn't seem to hurt too much:
Error: There is already a source with this ID

===
Firefox shows an empty map just like Chrome, but does show 3 small images in the left bottom corner and mentions the following in the console:
Error: There is already a source with this ID
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://d2munx5tg0hw47.cloudfront.net/tiles/9/262/168.mapbox. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by geolife** [comment] 2016-05-10 09:48
It's steel the same, any news? :(

**Comment by Olestas** [comment] 2016-05-19 11:07
Thanks a lot for ignoring this issue and destroying mapillary experience. Unfortunately as I cannot see map in browser, I am not mapping anything anymore, as I cannot use it.

**Comment by knikel** [comment] 2016-05-19 12:09
@Olestas I'm sorry about that issue, but as you've seen it's pretty difficult for me to track what this might be. The `already a source with this ID` issues has been solved and they should be gone for @SanderH. But I'm totally unable to find the cause for you issue. What worries me especially is that your browser seems to support WebGL, but you can't see the map even mapbox's examples. We're using mapbox's WebGL check with custom checks for properties needed by mapillary viewer. If the browser claims that it has them, but in reality they're not supported, well, there is not much more we can do. I hope one of the following workarounds could work for you. I'm sorry I can only offer you that little help with the issue.

The only way to get a fallback map on *mapillary.com* is to explicitly disable WebGL in your browser.

Chrome
- impossible to do in latest versions, older versions had a `Disable WebGL` flag after visiting `chrome://flags`

Firefox
- it's possible to disable it through going to `about:config`, you need to flip the `disable.webgl` flag to `true`

Safari
- Depending on the version `WebGL` is disabled by default. To change the settings you need to to `Preferences > Security > Allow WebGL`

**Comment by Olestas** [comment] 2016-05-19 12:32
Thanks @knikel ...
At least will be using it on Firefox. Works with webgl disabled.

**Comment by yopaseopor** [comment] 2016-05-19 16:29
with lastest Chrome


   1. access to chrome://flags/
   2. Search #enable-unsafe-es3-apis
   <chrome://flags/#enable-unsafe-es3-apis>
   3. Activate
   4. Reboot Chrome

It is not the best map or the best way...but now you can continue
contribuiting to Mapillary  while they will fix that.
yopaseopor

**Comment by Najsztub** [comment] 2016-05-20 14:21
Hi!

FYI I had the same issue with Firefox and Chrome on Windows 8 computer with a GeForce 210 video card. I followed the advice in #2131 of turning `webgl.disable-angle` to `true` in `about:config`.

After this both Mapbox GL maps and Styles work.

Hope this helps somehow.

**Comment by Olestas** [comment] 2016-05-20 14:25
@Najsztub what about Chrome? Version 50.0.2661.102 m does not have it.

**Comment by Najsztub** [comment] 2016-05-20 16:31
@Olestas I have found how to do it in Chrome [here](http://www.geeks3d.com/20130611/webgl-how-to-enable-native-opengl-in-your-browser-windows/).

Haven't checked it though.

**Comment by yopaseopor** [comment] 2016-05-20 17:47
I have tested that...and it works correctly, not like the Chrome setting I
had tested yesterday

**Comment by knikel** [comment] 2016-06-02 09:12
Thanks @Najsztub for the link.

**Comment by Olestas** [comment] 2016-07-21 13:33
Any new solutions here? With new look mapillary is not loading on any of my browsers. Even on windows 10.

**Comment by yopaseopor** [comment] 2016-07-21 13:39
With https://github.com/mapillary/mapillary_issues/issues/1725#issuecomment-220305657 I can see new Mapillary new site in Firefox . Old Chrome solution does not work.

**Comment by Olestas** [comment] 2016-07-22 06:33
webgl.disable-angle helps for firefox yes..
But what is the problem in? Wrong video card?

**Comment by RafalR** [comment] 2016-09-10 07:14
I do not know I have to change this setting in Google Chrome but I noticed that in my case it helps to add a "pitch: 0.01", as in this case: https://jsfiddle.net/kngpteyj/

At the moment do not see map. The problem may involve a greater number of users.

**Comment by aborruso** [comment] 2016-10-03 14:15
I do not see the map in chrome 54.0.2840.41 beta-m in win 10 :(
I have tried with all chrome webgl related settings.

![image](https://cloud.githubusercontent.com/assets/30607/19040443/5df41980-8984-11e6-951b-5a04a4be32dd.png)

I see it in Firefox 48.02, in the same PC.

Thank you

**Comment by gyllen** [comment] 2016-10-03 16:26
@knikel Is this something we have seen lately?

**Comment by knikel** [comment] 2017-04-04 15:13
I've added a hack to set map pitch to something else than `0`at the time. We're running `mapbox-gl-js@0.34.0` these days.

I'm going to close this issue since the OP raised it almost a year ago and I've added the pitch hack after aburroso's comment. If this happens again, let's create a new issue.

**Closed by knikel** 2017-04-04 15:13 UTC
Labels: affects-web-viewer, bug
