### ISSUE TITLE
phone capture upside down pictures

### ISSUE THREAD

**Issue by hakuchi** [mapillary/mapillary_issues#1553] opened 2015-11-22 15:13 UTC
If I capture images with my pone in normal landscape view, the review and upload working fine.
If I rotate my phone to the right, the captured pictures are upside down.
This upside down pictures i cant upload(tested on a 2km recording). And I dont have time to rotate all pictures 180° on my PC.

Left rotated phone.
![capturin correct](http://fs5.directupload.net/images/user/151122/6s8utsvc.png)

Right rotated position of my phone, the images are captured upside down.
And you can see the statusbar upside down, but start button in normal view.
![upload not working](http://fs5.directupload.net/images/user/151122/4belh5qn.png)

I used app 1.59 from playstore on my 5.0.2 Android Phone

**Comment by de-vries** [comment] 2015-11-22 18:09
If you're looking for a tool to rotate a lot of pics, take a look at [Phatch](http://photobatch.wikidot.com/)

**Comment by hakuchi** [comment] 2015-11-22 19:38
I not searching a tool. This is a bug in the app.
I dont think, that all user will/can use the phone rotated to the left.
If I take a picture with the camera it not matter if left, right or upside down. All pictures are saved correct.

**Comment by peterneubauer** [comment] 2015-12-01 12:32
So,
this is actually not a bug but a feature, so you can use the application for left-handed users, and still get correct images. closing this.

**Closed by peterneubauer** 2015-12-01 12:32 UTC
Labels: android, bug

**Comment by hakuchi** [comment] 2015-12-01 16:44
>So,
>this is actually not a bug but a feature,
>

of course is this a bug.
I dont receive correct images if I rotate the phone to the right.
If I make a ride with phone rotated to the right, all pictures will saved upside down and in review all pictures are upside down.
What the hell is the feature here?

**Comment by polarbearing** [comment] 2015-12-02 00:04
I took some testshots, first in normal landscape mode, then 180 deg turned. The User Interface nicely turned into the left-handed position (except for the phone's status bar).

The pictures from the normal shot are in normal orientation, carrying the EXIF flag Orientation=Horizontal (normal).

The pictures from the rotated shot are physically upside down, and carry the EXIF tag Orientation=Rotate 180.

The app review shows all pictures correctly. Any picture viewer respecting EXIF orientation tags will rotate the pictures while viewing, and I would assume the Mapillary server to do the same. 

If @hakuchi's picture viewer does not evaluate the EXIF tag, the pictures would look upside down. Modern image tools would contain a function that losslessly rotates pictures physically, based on the EXIF values, if necessary, but as long as the Mapillary server is happy with them just correctly tagged, that would not be needed before upload. 

So everything looks as intended. If the situation for some reason is different for you, @hakuchi, please stop cursing, calm down and analyse.

**Comment by hakuchi** [comment] 2015-12-02 20:02
Hi again,
sry for my last post.

I tested now with 1.61
I made some pictures in the dark so I cant test if this will accepted to upload in normal and rotated position.


In review the pictures are upside down but wen i click on these, the images showing correct.
In the preview of the file explorer I use, the pictures are also upside down.
If in my next test the upload works, I can live with this upside down review in the app.

Picture made in normal view:
![image 1](http://fs5.directupload.net/images/user/151202/4u73vd5n.png)

Picture made with rotated to the right:
![image 2](http://fs5.directupload.net/images/user/151202/cx4ryzua.png)


I will made some test this weekend on day, with rotated phone.
In the past, the upload failed with this position. Hope it works with 1.61

**Comment by peterneubauer** [comment] 2015-12-03 08:51
Ok, cool, let me know how the photos show up in Mapillary! Maybe the rotation in the camera EXIF is correct and for some reason your preview is not showing the right rotation.

**Comment by hakuchi** [comment] 2015-12-13 09:19
with 1.67 the problem with upside down pictures is solved for me.
Also the preview showing the pictures correct.

there is some freezing/crash bug, but I commented this in .[#1603] (https://github.com/mapillary/mapillary_issues/issues/1603)
