### ISSUE TITLE
Better random order in sign game

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_issues#995] opened 2015-05-09 13:13 UTC
I would like to see the random order in the sign game improved. I am constantly getting images where I was the last to edit, or images I already have confirmed, meaning I constantly have to *skip this image* to continue the game. This is kind of strange when there are more than 3million (US) images and less than 0.5% confirmed. I suggest filtering so that images one cannot confirm (last edited by user or already confirmed by user) are ignored from the random order.

**Comment by de-vries** [comment] 2015-05-09 13:51
duplicate of #840

**Comment by pyrog** [comment] 2015-05-10 04:36
> I constantly have to skip this image to continue the game. 

:+1: It happened very frequently

**Comment by Skippern** [comment] 2015-05-10 11:21
For my part, with less than 0.5% confirmed, not more than every 200 image should (statistically) be confirmed, and I have the impression I have to skip 2 out of 3 images, that is too steep.

**Comment by gyllen** [comment] 2015-06-26 19:20
Is this still a problem @Skippern ?

**Comment by Skippern** [comment] 2015-06-26 21:39
@gyllen I haven't played in a while, probably time to check again

**Comment by Skippern** [comment] 2015-06-27 00:08
@gyllen I have played a little around with it just now, and it seems much better. There are still some that should have been skipped, but now more like 1/10 or 1/20

**Comment by gyllen** [comment] 2015-06-27 00:25
Yeah this still needs fixing then, not closing yet

**Comment by gyllen** [comment] 2016-07-22 00:05
Sign game is closed. Something better is around the corner. Closing.

**Closed by gyllen** 2016-07-22 00:05 UTC
