### ISSUE TITLE
images flipped 180° on one track

### ISSUE THREAD

**Issue by echeloni2p** [mapillary/mapillary_issues#1892] opened 2016-05-27 07:11 UTC
Hi!
Yesterday I was on my bike and made a few tracks, one (only one) is flipped 180° horizontal for the whole track, every image:
http://www.mapillary.com/map/im/JHfJaTLHkGc0bQSkPsC9UA
Should I hide it, how can I/you flip them back?
Or hide it and redo it?

**Comment by ybkuang** [comment] 2016-05-27 07:22
@echeloni2p keep the images. We will rotate the photos for you.

**Comment by rausk** [comment] 2016-06-02 14:37
Today I had the same experience. One series completely turned upside down. I wonder how this can be explained?

Nevertheless I will upload the sequence hoping that Mapillary will do the job.

**Comment by ybkuang** [comment] 2016-06-02 14:39
@rausk it is mostly because of the sensors got affected by vibration. Were you on a bike?

**Comment by rausk** [comment] 2016-06-02 14:42
Yes! 
Is there any adjustment besides pause on shake? Because if I tick pause on shake I get no picture at all

**Comment by ybkuang** [comment] 2016-06-02 14:53
@rausk Since you got the whole sequence upside-down, it feels like the device does not re-calibrate its orientation tag after the initial vibration. What device are you using?

**Comment by rausk** [comment] 2016-06-02 15:08
I am using Samsung S4mini (GT-I9195) with Android 4.4.2

**Comment by ybkuang** [comment] 2016-06-03 07:32
@rausk Thanks! You can just upload the images for now. We are working on adding orientation changeset so that you can request rotation of the images (We can also fix the sequence manually for you before that is done if you share the link to the upside-down sequence here)  

In the meantime, we will see what we can do in the app. Maybe adding a preview after the capture so users can tell if the photos are upside-down and re-calibrate the camera. 

In the future, we will look into auto-detection of upside-down photos as well.

**Comment by rausk** [comment] 2016-06-03 10:53
Thank you very much, the sequence key is

http://www.mapillary.com/map/s/8ymcapwQTMG8uDsyTXqndA

I'm waiting for further improvements of the Mapillary Software.

**Comment by ybkuang** [comment] 2016-06-09 08:47
Rotate https://www.mapillary.com/map/im/OIgsB6RjIQ3Qgsy7pZMJmg/photo for @beer119

**Comment by rsahlin** [comment] 2016-06-09 09:13
Hi @rausk & @echeloni2p 

I am looking for the root cause of this.
Could you please make sure you are using the latest version, at least 2.20, and also enable saving of logs by opening 'Feed' - 'Settings' and enable 'Write trace logs'
This will save the debug logs.
If the problem happens again, please go into 'Feed' and select 'Send debug logs'
If the problem did not happen in a sequence you can check 'Feed' - 'Settings' - 'Start new logs' to clear logs.
Otherwise they will become very large :-)

Thanks for your help!

Best regards
/Richard

**Comment by katrinhumal** [comment] 2016-06-14 11:06
Another one to rotate http://www.mapillary.com/map/im/WVPyKJ2wfe6esCPFgIMzNA

**Comment by andyclegg** [comment] 2016-06-14 11:41
And this one: http://www.mapillary.com/map/im/OkcAVOwbyio2iqxiU3IBmg/photo

**Comment by katrinhumal** [comment] 2016-06-14 12:09
http://www.mapillary.com/map/im/GOumlNBHdRpQw8gQ8kVzZQ/photo

**Comment by katrinhumal** [comment] 2016-06-14 12:22
http://www.mapillary.com/map/im/972DP-4AqyMI4x9T695vXw/photo

**Comment by katrinhumal** [comment] 2016-06-16 09:27
http://www.mapillary.com/map/im/IAK6REbyxwPk-ZLc3PsG1g/photo
http://www.mapillary.com/map/im/xg4cYu5ew6sL_BLtWjYmZQ/photo

**Comment by rausk** [comment] 2016-06-17 09:32
"
http://www.mapillary.com/map/s/8ymcapwQTMG8uDsyTXqndA
"

When do you think will the above sequence be rotated?

Thank you in advance.

P.S. I would do it myself if I could find a suitable key in the edit menu, but there is'nt any...

**Comment by rausk** [comment] 2016-06-30 07:58
After having updated to the newest Mapillary Version 2.31, I have again  experienced sequences with upside down pictures. I will upload the corresponding log file first and then wait for your advice.
Note: not all sequences are wrong, some are OK.

**Comment by rsahlin** [comment] 2016-06-30 08:12
Hi @rausk - sorry to hear :-(

Yes, please send the logfile, thanks.
Could you please also upload a sequence with flipped pictures so I can examine the data in them?

Thanks
/Richard

**Comment by rausk** [comment] 2016-06-30 09:40
data is being uploaded

**Comment by grinapo** [comment] 2016-07-05 18:43
If you feel like you can also rotate these (samsung s7, car, by the way the tilt sensor lies pretty hard: for sideways acceleration it says 20+ degrees while it's not tilted at all; isn't it possible that there's a wrong sensor reading used?):
http://www.mapillary.com/map/im/hquQ4JDUScA8IUNW3VHobA
http://www.mapillary.com/map/im/lB28nb0yk2yV8Ba2yrub-w
http://www.mapillary.com/map/im/NI1ubVMu0qZlqhyYrq_aHg

**Comment by rsahlin** [comment] 2016-07-05 19:13
Hi @grinapo 

It seems your photos are taken with version 2.24 of the app - could you please update to version 2.31 that is out on Google Play?

Could you please explain when the app display >20 degrees rotation?
There was an error in earlier version that did not enable tilt sensor when the mode was locked in forward driving mode.

Thanks
Best regards
/Richard

**Comment by grinapo** [comment] 2016-07-05 19:27
@rsahlin unfortunately I cannot upgrade it -- since it's at v2.31 :-) Those sequences were created earlier, I just realised they're turned.

As for tilt: The phone is firmly put on the windshield (using an extremely stable holder which was incidentally offered to me by a company called "mapillary" :-)) so it's not tilted more than 3-4 degrees ever (unless I capsize my car :-]). I have seen that the phone stops recording by "tilted phone" when the sideways acceleration is significant (I don't have it measured, probably ~1-2 g left or right, eg. in a high speed turn). I have seen it in this version, too, but today I hav driven more carefully, so not too often.

Should I enable the trace log?

**Comment by grinapo** [comment] 2016-07-06 05:32
seems v2.31 wasn't much better, finished uploading...
http://www.mapillary.com/map/im/9tt_2x0DZWa6IZR-vnULVQ
http://www.mapillary.com/map/im/eu_xrcDQJJ-dXG-swmIFug
http://www.mapillary.com/map/im/O4KRPYB7L52bT0qNWSwBrA

**Comment by rsahlin** [comment] 2016-07-06 07:34
Hi @grinapo and thanks for the information

The function to stop on tilt will be disabled by default from version 2.33 - you can disable it by going into 'Feed' - 'Settings' and unchecking 'Pause on tilt'
In 2.33 you will also be able to set specify the angle if you want to.

Could you please send debug logs, by going into 'Feed' and select 'Send debug logs'

- Are the images rotated when viewed on the device?
- Does this rotation happen to all sequences?

Thanks!
Best regards
/Richard

**Comment by grinapo** [comment] 2016-07-06 12:23
@rsahlin I didn't disable tilt detection because I want to see if anything's faulty or not, otherwise I have no way to nag you about fixing it. :-)

I have sent trace log to logs@mapillary, it seems to say jpeg orientation 180... something fishy's going on...

The images are upside down on the phone, and not all sequences are rotated, but recently almost all of them are.  I believe sequence P-50J7HV0rpoSDGGXOF_WQ  was created by the same phone (can't be sure as mapillary website neglects to show exif info and download gives an exifless thumb only).

**Comment by rsahlin** [comment] 2016-07-06 12:42
Ok, thanks for letting me know

I will have to look into the sensor usage very soon as I am doing some other changes related to compass.
Ideally we should not use the accelerometer for tilt sensor since it will have the effect you are mentioning - ie movement may be reported as tilt.

Thanks for sending the logs I will look into them shortly.

/Richard

**Comment by rsahlin** [comment] 2016-07-06 14:09
@grinapo You mentioned in the other issue #1925 that you hade your phone rotated 180 degrees - was this the case in the above sequences?

Best regards
/Richard

**Comment by grinapo** [comment] 2016-07-06 16:14
The phone(s) is (are) _always_ 90 degrees clockwise rotated, landscape format. What I mentioned is that the phone OS (android) puts the "top" bar at the bottom, upside-down, which suggest that the OS considers the phone "upside-down", which may or may not cause problems. At the same time, however, Mapillary uses the right orientation for GUI elements (like the start button or onscreen debug info).

Hmm. Now that I mention.... I have checked, and indeed this is caused by Mapillary, more specifically camera mode. When I hold the phone with Mapillary in the feed menu everything's allright, but when I select camera the top notification bar jumps to the bottom and turns upside-down, while the mapillary gui stays properly oriented. I believe this always have been the case (or at least for the last months), and both of my phones (the S7 and a oneplus1) does this.

But it seems the app tries to confuse us, finished uploading todays data, and half of it is _properly_ oriented:
http://www.mapillary.com/map/im/1B0OSotS3yk7dYmn6fG2pg   -- bad
http://www.mapillary.com/map/im/bEX8f3pmJ3zpsFvLqP8PoQ    --  good

Also I believe I have seen http://www.mapillary.com/map/im/5xk4F9bsz-G73EM9AAE9tA/photo upside down on the device but now it's properly oriented, but I am not entierly sure.

**Comment by mikini** [comment] 2016-07-12 09:38
I also got a bunch of inverted sequences, among mostly correct ones. Out of 51 captured sequences, 4 are inverted. They are all captured using the Android app, and all done while mounted in a static mount on the car windshield. The first appeared on June 25. and last one is my most recent sequence from July 10. Current app version is 2.31.

It would be nice if somebody could rotate them;
http://www.mapillary.com/map/s/fh4NAXyC_w_nqKyYdWXpbw
http://www.mapillary.com/map/s/mm7qkPrvhkw38imvdWpt8A
http://www.mapillary.com/map/s/y4QFeBpjYExIpcIQZ7DIuQ
http://www.mapillary.com/map/s/Bj9bTc-6TKjO36jkWquPgQ

**Comment by blobgo** [comment] 2016-07-31 12:39
Please rotate http://mapillary.com/map/im/S1yj-bxVtJ3lpMIVRBRVEg

**Comment by mikini** [comment] 2016-08-01 06:39
@ybkuang 
> We can also fix the sequence manually for you before that is done if you share the link to the upside-down sequence here

Could your please specify further instructions on how to properly request a manual rotation of sequences? Only the first two sequences mentioned here have actually been rotated while all others are still upside down.

Should we file a separate issue for each sequence? Or email somebody?

**Comment by ybkuang** [comment] 2016-08-01 07:03
@mikini Sorry about the delay. We will rotate the sequences for you now.

**Comment by rausk** [comment] 2016-08-01 08:55
Thank you for rotating the following sequences, too:
8ymcapwQTMG8uDsyTXqndA (open action since June 3)
YObV3vLdhMhxTcbbkqRbnA
gBOQ08QHvDs-YjmQOtIFDw

**Comment by ybkuang** [comment] 2016-08-01 08:56
@rausk will do. Sorry about the delay!

**Comment by rausk** [comment] 2016-08-02 10:36
Thank you so far, but it seems you have missed some photos from the sequence key 8ymcapwQTMG8uDsyTXqndA 
(sorry):
 
U1MWKW9rxdlME2CkioAT0w
NDJeIfTkgot3UMErvSKS0g
eB_TZhQShxVRrCF7nhiHXA
GaKRIDF_3AQ1XkDSLflG9g
eYZBUtYoPTM_tl9EdkbqKQ
IJasHuSBbJH847ZBrHyLvg
f-MkK499i8E3kYtkiheYzw
wJ-d5WCVF0iuXBIv8Mtorg
ZWYm_8qFQ96neneWavZzJg
EpLcdt7haqPJEBgj37iiKg
IihtG4VuWboEx-AUfC7Ikg

I will check the other sequences later.
Regards rausk

**Comment by gyllen** [comment] 2016-08-02 14:14
@ybkuang Some rotation requests

**Comment by rsahlin** [comment] 2016-08-09 06:55
Hi, back from vacation with renewed energy to tackle this issue.

I have a feeling that this problem happens due to a change that I did in the phone rotation check.

As it is now the phone needs to be rotated at least 180 degrees in order for the UI to rotate.
I suspect that there are sequences captured where the UI is actually upside down, the only visible difference will be that the 'Start' text will be upside down.

In the long term it needs to be more visible what orientation the phone is expected to have, a short-term fix will be to alter the angle where the UI is rotated, maybe at 135 degrees.

I will start working on an updated.

Best regards
/Richard

**Comment by mikini** [comment] 2016-08-09 08:11
Hi @rsahlin. Welcome back, hope to see this fixed soon too.

To add my experiences to your rotated UI hypothesis, I am fairly certain that most rotated sequences I have captured has not had the UI rotated. I see routinely when fixing my phone to the windshield mount and controlling the current settings that it takes a few seconds to get the orientation and align the UI correctly, so I guess I would have noticed if it was upside down in any of the captures.

I have a 40MiB+ trace file on my phone with a couple of sequences recently being rotated that I can contribute. Is that still relevant?

**Comment by echeloni2p** [comment] 2016-08-11 19:45
Hi

got a few rotated tracks today out of nothing, too.
Username: aceini
https://www.mapillary.com/app/user/aceini?lat=52.13261517168452&lng=10.057396337356778&z=17&pKey=wUDYI11BFNfGAim1WMoxdg&focus=photo
https://www.mapillary.com/app/user/aceini?lat=52.15011181339808&lng=9.972387336426062&z=17&pKey=GkdJ6DSWJm0SwdCNUtK7BA&focus=photo
https://www.mapillary.com/app/user/aceini?lat=52.1349257606041&lng=10.062270005516723&z=17&pKey=QN-2vT8-8Xg_bd18EIUFug&focus=photo

It maybe associated with rotated UI, but I do not think so.
I did have had some issues with SD Card usage on my mobile before and mapillary app hung.

echelon

**Comment by gyllen** [comment] 2016-08-12 17:12
@echeloni2p Good news is that we have started to detect all of these with computer vision. We are going to need an interface though where people will approve if its a rotation or now.

Results looks promising though right @ybkuang @paulinus ?

**Comment by iav** [comment] 2016-08-13 02:58
I found one completely rotated up-down panorama sequence https://www.mapillary.com/app/?lat=56.9493822&lng=24.1262171&z=17&pKey=5vfaySh709N8kVNDnctMZw&focus=photo
I am sure I perform a review before upload, and photos was showed normal on phone (Galaxy Note 4).

**Comment by katrinhumal** [comment] 2016-08-30 08:42
This is still a recurring problem. Feedback from voschix:
amongst the sequences being uploaded, there are a high number of rotated ones (all photos upside down). They were all taken with the same settings and the same mechanical arrangement as the upright ones. These are all from a new phone (Sony Z5 compact) and the ratio of upside-down sequences vs normal ones is about 1:1, i.e. much higher than with the previous phone (Sony Z3 compact).

**Comment by voschix** [comment] 2016-08-30 16:36
I see the rotated sequences frequently in my car with Mapillary car mount.
I looked into the EXIF data and found that they consisent with the problem:
The smartphone (Sony Xperia Z5 Compact) is used upside down (lens bottom right, looking in the direction of the camera). The photos that are OK have the _correct_ EXIF tag "Orientation=Bottom Right"); the upside-down ones do have the _wrong_ EXIF tag "Orientation=Top Left".
I took some photographs with the built-in camera app of the phone and found that it reliably set the Orientation tag correctly when I rotated the camera.
I have a possible culprit in my case: In order to not see the suction foot of the mount in the photos I turn the camera upside down and clamp it far away from the lens (left side of the phone looking in the direction of the camera). In doing so the clamp presses two buttons of the camera: the (smaller) normal Shutter Release button and the (longer) Volume control bar. See the attached photo, which shows the camera (on a table) in the car mount, looking at the "bottom" of the camera. I also noted that I had enabled, in the Mapillary settings, the option to operate the camera with the volume keys (which in my phone are combined in a Volume bar). That Volume bar may be the real culprit. I will go out and take some shots with the clamp not touching the Volume bar, to test my suspicion, and will report back here.

![mapillary clamp](https://cloud.githubusercontent.com/assets/11076112/18097898/31fadc2e-6ee0-11e6-86e5-162b9af59a3d.jpg)

**Comment by voschix** [comment] 2016-08-31 07:54
Please rotate by 180 degrees the following sequences:

lzL2suNu6a_-t_sxnZjoBw
YwtwQ3esRau52t2WRkn3rQ
J-O-a6PNnpIaHWLsKePlAw
dnwcAgO5MNO5V5Wck9OuGg
lNGvCsgJHvngkI5YtZCjRQ
kpZQaBtEqI4I61eOsNwfLA
-Mdj1qyz7H7AbptK13CojQ
hn5FSl1y2IhblK1cVLutcQ
DmynyZqLthevtgsUtykYhg
bDXPoiZaKSF_-hvcQcnlLQ
ml5zt5fHcFEWjLUQ3TGTMQ
udOG4qKIfBAWyV5YulmX_w
4XYdnfdt7TGN8tk8Z80vJg
189q58lfJgZE2gYcxUH5Cw
HUaT4owipU2XcUGjwd7BiA
G0FI7HN9FdskuyboFcWUtQ
zkicA-1RjxQOfDE-2uMUxQ
y7P35jAGe6EEWoXdhMTOxQ
u5--TH0Ns7jvkXETuDabpw
-H8rCa2GiR9Zj8Qrcl5IKw
-56mZGg6AQ8UH-_emN1nmA
J8wx82sfQiEgGRRy-UqYGw
XTIUl6x7Koa8kYWPOFENBQ
lOebErLnRVLg_xCu1rD7kg

Thank you

**Comment by grinapo** [comment] 2016-09-14 14:32
Have I mentioned that mapillary actually _changes_ the phone (android) orientation [to upside down] upon entering the camera view? It's visibly due to the "top" menu bar going down upside-down.

**Comment by jfburke3** [comment] 2016-10-10 21:16
I have a sequence that is upside-down, too.  I decided to do simultaneous forward and side sequences yesterday.

In my case, the upside down sequence was shot to my right as I was driving, using my Galaxy S5 running Android 5.0, Mapillary 2.40.  Due to power cable length, I had to rotate my phone to the right instead of my usual left to take the sequence.  

S5 upside down sequence:
https://www.mapillary.com/app/?focus=photo&lat=33.9192717&lng=-84.465225&z=17&pKey=jG21C3RX73GjQHz_KzeWAg

I changed out the S5 with my S7 (which had been doing my forward sequences), not because I noticed a rotation problem (it looked fine on screen) but because the S7 focuses much faster, and so was a better phone to use for the sideways shots.  Every sequence shot with the S7 (that I've checked out so far) has the correct orientation, and it, too, was rotated right instead of left.  The S7 is running Android 6.0.1, also Mapillary 2.40.

S7 right-side-up sequence:
https://www.mapillary.com/app/?focus=photo&lat=33.9296677&lng=-84.4608838&z=17&pKey=B6_1wH1FoNZr5J1d_Np86Q

I don't know if it's an app problem, an OS problem, or a hardware issue, and since I didn't realize what was going on, I didn't try to get trace logs.  I can try to do that later if you want.

**Comment by mikini** [comment] 2016-10-22 18:37
@gyllen, did the solution using computer vision run into problems? Would users be notified of suspected rotations on upload? I have recorded some more rotated sequences since. Could they please be flipped?

bOfotEzEaRsRy1-p8lOmHQ
jnP2QtIzCZxz2sHMQwZ6mw
TY0kUgl9qMHvWwxb2uES1g
EQzzpoG4TjZYo_nv-sKP5g
v-y4ENpM39EiUtmSDZApNQ
dDHu_2HdfdI-HY6A4Wwhyg
0Mk9Dhnzv5gBAY2zk954kw
HBTIG4O_9n-_yI4jlmcOVA
ilEh8LYIDeN2AirSre_4FQ

**Comment by mikini** [comment] 2017-03-10 14:13
After recent update of Android application to Mapillary v3.32 with major changes to the capture screen the first sequence I recorded was again rotated (sigh...).

Sequence key: [nT1ytytRWs4_s-DdOgZr_Q](https://www.mapillary.com/app/user/mikini?sKey=nT1ytytRWs4_s-DdOgZr_QpKey=D0LT6QLYr9fE_mu8j420HQ)

This is on [Samsung SIII LTE (GT-I9305)](http://www.gsmarena.com/samsung_i9305_galaxy_s_iii-5001.php), using stock Android 4.4.4.

**Comment by grinapo** [comment] 2017-03-11 09:01
I am thinking about sacrificing a black rooster on a full moon, maybe that's the only possible thing fixing this. ;-)

**Comment by rausk** [comment] 2017-03-11 11:28
The next opportunity to do this would be during next night...

**Comment by grinapo** [comment] 2017-04-02 10:48
1) I cannot seem to be able to find the sequence id easily now. "Where issss it?" -- Gollum
2) There seem to be an awful lot of issues related: #466, #531, #722, #811,  #2327, #2365 
3) I haven't got upside-down recently, but the latest non-beta even started the camera live picture upside-down 3 out of 5, and when had the good _visible_ orientation the result became flipped.

Please rotate:
https://www.mapillary.com/map/im/sptbmPESuO0lKvH_cS7C6g and its sequence
https://www.mapillary.com/map/im/L3yr91UhmRxia_RUQy-Cig and its sequence

**Comment by katrinhumal** [comment] 2017-04-03 15:08
@grinapo I requested rotation of these for you. Do you mean version number 3.41 when you say the "latest non-beta"?

**Comment by mikini** [comment] 2017-04-03 15:37
@katrinhumal Could you please look at the last couple of hundred of my sequences too?
https://www.mapillary.com/app/user/mikini

As mentioned on March 10th above after the Capture screen rework I get rotated sequences. And now it is 100% consistent. As @grinapo mentions the whole UI (notification bar and all) is flipped when entering capture mode.

Honestly, I have given up on Mapillary, it seems like your have a different agenda than me, not caring about a pressing issue like this scares me off. Hopefully the alternatives will be usable at some point.

**Comment by grinapo** [comment] 2017-04-04 08:46
@katrinhumal When I shot the sequence I had the latest PlayStore version installed (at that particular point in time), but when I have realised that they're flipped I updated it to the PlayStore beta, which is v3.41 right now according to the menu. I cannot tell you what it's been before, I know no update history log on android. Maybe the images contain the version.

**Comment by grinapo** [comment] 2017-04-04 08:55
@mikini Wow, you have covered half of Danmark... upside down. Don't give up. Mapillary folks have pretty hard time since they have to handle wide range of Android APIs and various bugs in firmware and phone hardware. There are also several issue tickets about this problem and some of them see some progress, I don't know why github neglcted them to crossreference when I included the numbers in one of them. :-(

@katrinhumal Would it make you progress faster if people like @mimkini would submit their debug logs? This flippin' flippin' issue is really disturbing and it's going on for quite a time now. I also seem to recall that someone's mentioned putting "flip sequence" or "flip images" out on the GUI, is this correct?

**Comment by ybkuang** [comment] 2017-04-04 09:12
@mikini Sorry to see that the problem re-appears. We have been keep track of the problem and have been looking into solutions in the Android app, backend and computer vision.  

- Android: @peterneubauer has been looking into the issues regarding camera APIs

- Backend: We implemented the processing flow for manual rotations requests. 

- Computer Vision: We have developed an algorithm for detecting erroneous rotations. This algorithm will proposal candidate for further human validations. This way, we can correct the rotations of the photos that have already uploaded in our system much more efficiently.

Again, sorry about delay in resolving the issue, but we are working hard on it.

**Comment by peterneubauer** [comment] 2017-04-04 11:37
Hi there,
I just fixed a bug around this - for older camera implementations the image rotation was not correctly set for the camera. 3.43 (out in a few hours) contains this fix. Please test and report back!

**Comment by mikini** [comment] 2017-04-05 10:38
Hi @peterneubauer. 

For reference, Peter and I had a discussion about this at https://www.mapillary.com/app?pKey=uIvybCt4f700GK94GpgadQ.

In the above photo comment thread I reported that I managed to capture a correctly oriented sequence using Mapillary for Android v3.43 on my older Android 4.4.4 Samsung PIII (my understanding is that it was a problem only on older Android API's). That is so nice, thanks to Peter and whoever at Mapillary finally decided to give this attention.

However, when starting the application in the routine this morning after placing the phone in its mount, I noticed incorrect orientation in the UI. Luckily this is a different issue as the rotation is limited to the Capture UI, the orientation of captured photos is correct.

After some experimentation, I can now consistently recreate this as follows.

1. Start Mapillary while the phone is in any orientation
2. Tilt the phone to the right more than 90 degrees (bottom pointing towards left, top pointing towards right) and go the Capture tab
3. The camera feed is now rotated (see screenshot 1)
4. Photos **are** recorded with correct orientation however (see screenshot 2)

The incorrect feed rotation is persistent when restarting capture when returning rotation back to below 90 degress rotation (with capture off!). It persist until the phone has been rotated back to portrait and to the left (below 0 degress).

The sequence captured while taking the screenshots and log is [gd-37zMjF41tmPha_oxk_g](https://www.mapillary.com/map/im/B1bePdyORCymvskTibb_xg).

mapillary_trace.txt:
Subject: Mapillary Android logs, user=mikini, version=343(3.43)
Procedure: cleared logs, restart app, perform above procedure, send logs

Wed Apr 05 11:01:33 CEST 2017 : app.mapillary.android.activity.SettingsRootFragment  - onCreateView()
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onResume()
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - upload is null.
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.feed.HomeFragment  - onResume()
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.account.MapillaryAccountManager  - Got 1 accounts:
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.account.MapillaryAccountManager  - censored@email.com
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.feed.HomeFragment  - onCreateView()
Wed Apr 05 11:01:36 CEST 2017 : app.mapillary.android.feed.HomeFragment  - onResume()
Wed Apr 05 11:01:37 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onDrawerStateChange() 1
Wed Apr 05 11:01:37 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onDrawerStateChange() 2
Wed Apr 05 11:01:38 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onDrawerClosed()
Wed Apr 05 11:01:38 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onDrawerStateChange() 0
Wed Apr 05 11:01:48 CEST 2017 : app.mapillary.android.activity.TabbedMainActivity  - onDestroy()

Screenshot 1, rotated camera feed: 
![screenshot_2017-04-05-11-02-49](https://cloud.githubusercontent.com/assets/1330166/24699223/8bc0c836-19f3-11e7-9e5f-e0c7958f1346.png)

Screenshot 2, non-rotated sequence:
![screenshot_2017-04-05-11-03-14](https://cloud.githubusercontent.com/assets/1330166/24699601/dcc49ec8-19f4-11e7-8d20-b44507201d47.png)

**Comment by grinapo** [comment] 2017-04-05 13:35
I have the beta (3.43) installed and it's doing real weird stuff with orientation.

I hold it landscape, up is at the right. Android is set to change orientation (no fixed), but it doesn't seem to matter at all.

Menu misoriented right-top (portrait, up).
Capture screen orientation is good and android top bar is at the top. I press the orientation arrow and the screen appears upside down, android top bar at the bottom. Sucks. Back. Good. Then settings cog and the menu comes up 180° flipped, android topbar at the bottom again. Going back the main menu results sideways menu again (90°).
The captured images now properly oriented, but the apparent mis-orientation everywhere is alarming.

**Comment by grinapo** [comment] 2017-04-06 06:49
Checked on a different phone (Oneplus1 instead of SamsungS7) and the behaviour is the same. Also there's a state when the capture screen is properly oriented but the image is flipped.

**Comment by peterneubauer** [comment] 2017-04-06 10:49
Ok,
on it, will try to recreate this with the devices over here. Thanks for all the reports - seems the offset settings screen needs to auto-rotate in order not to mess up camera preview orientation upside-down mode. On it ...

**Comment by peterneubauer** [comment] 2017-04-06 13:53
So, the problem sits in rotating legacy camera previews in the Offset activity. I now have enabled devices with only partly Camera2 support to run the more modern implementation that should have less problems. Can you please test http://android-releases.mapillary.io/Mapillary_Android_3.45-SNAPSHOT.apk and report back?

Meanwhile, I will work on getting even the legacy camera implementation to behave correctly.

**Comment by grinapo** [comment] 2017-04-06 21:12
- however I rotate the capture screen it orients right and the captured images are oriented properly
- the direction arrow on the cap scn leads totop-right oriented page (it's been upside down)
- the setup cog leads to upside-down menu
- on 2nd - 3rd entering the capture screen the camera freezes on black picture, leaving and entering again fixes it
- forcing legacy api switch is there but seemingly does nothing at all (images are crap like using api2)

**Comment by mikini** [comment] 2017-04-06 21:37
@peterneubauer 
3.45-SNAPSHOT still exhibits the flipped camera feed described above on Samsung SIII (legacy I guess?) when tilted more than 90 degrees right/CW.

Is the "offset settings screen/activity" you refer to something internal? Doesn't ring a bell to me and can't find anything like that in the application.
You could upload the code to a git repository somewhere and I would gladly take a look ;).

**Comment by zlavergne** [comment] 2017-04-20 16:07
I have a few photos in my sequences that are flipped. Could you flip them? 
https://www.mapillary.com/map/im/MypBwoI1MuxfW8Cb28psOA
https://www.mapillary.com/map/im/jZQynzhkzQKS_7jobU21cw
https://www.mapillary.com/map/im/wmslqO-NgszBPgmvN7Q0sA
https://www.mapillary.com/map/im/e1JYEWNmSDYUY5uG320wWg
https://www.mapillary.com/map/im/aSd6EC5ncQeRnlqLx4fctA

Thanks

**Comment by rigoucr** [comment] 2017-04-23 16:54
I got the exactly same issue.
When I take new sequences all the pictures are always flipped 180°.

- Device:
  Brand : LG.
  Model: Nexus 5x.
  Android version: 7.1.2.

- App version: 3.50
I also tried to force the use of the legacy Camera API but only  make issue worse, when I open the capture mode, the camera are completely flipped  180°.

**Comment by katrinhumal** [comment] 2017-04-27 12:04
@zlavergne I can help fix the rotated images, but will wait for now since @peterneubauer perhaps wants to take a look first. Peter, in this case there are just some odd images upside down among a bunch of correct ones in the same sequence. In most cases we have seen the complete sequence being upside down...

**Comment by katrinhumal** [comment] 2017-05-04 07:48
Same case here: https://github.com/mapillary/mapillary_issues/issues/2558

**Comment by ovivoda** [comment] 2017-05-21 16:29
fix for this coming out in the next release.

**Comment by ovivoda** [comment] 2017-07-17 05:16
this issue should be fixed now

**Closed by ovivoda** 2017-07-17 05:16 UTC
Labels: affects-android, affects-vision-ip, bug

**Comment by gthrepwood** [comment] 2017-08-23 10:03
Not fixed

**Comment by ovivoda** [comment] 2017-08-25 04:55
@gthrepwood Have you used v3.89 and still have upside down images? How many are them? an entire sequence? Was that a bumpy road you were capturing on?

**Comment by gthrepwood** [comment] 2017-08-25 10:29
@3.89 yes
Entire sequence
No bumpy road. Other apps do not have (ever) issue detecting 90 or 180
degree turn.

**Comment by rausk** [comment] 2017-08-29 17:20
For a while I did not have this nasty issue, but since some time more and more pictures are again upside down. My impression is, that the reason has something to do with shocks on the capturing device.

The process to flip the pictures before upload is very time consuming! Since we have this error for so long a time, I urgently ask Mapillary to fix it now or provide a button for manual flipping the corresponding picture by the user himself.

**Comment by gthrepwood** [comment] 2017-08-30 08:32
I would personally prefer to have an option to manually specify the
orientation.

**Comment by gyllen** [comment] 2017-08-31 16:38
Another way would to have a verificaiton step of rotation and then lock it.

**Comment by urkud** [comment] 2017-11-09 04:32
Rotate FWOI2gPiXqIgVx-KnP6IRQ, please.

**Comment by katrinhumal** [comment] 2017-11-09 08:38
Hi @urkud - could you please submit your rotation request via this form: https://goo.gl/forms/o2nCZrC2KKiezQJz1

**Comment by richlv** [comment] 2018-04-19 11:40
Please see this area, notice how sequences are seriously broken (also more of these to the north).
https://www.mapillary.com/app/?focus=map&pKey=OsQJlxl96l7UXNbUwjBbIw&lat=56.934970457841416&lng=24.180239819780468&z=15.408224037272783

How should that be reported ?
