### ISSUE TITLE
People Have Uploaded Pictures In... Fails

### ISSUE THREAD

**Issue by AllenGraetz** [mapillary/mapillary_issues#1393] opened 2015-09-17 03:38 UTC
The email that lets me know someone has uploaded pictures in Rochester fails.   Clinking on the link brings to a general map.

Link from email:
https://u1074742.ct.sendgrid.net/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUi-2FXJSndBCCKmUkmSUFbMM2_JmO20RkNpY-2BEdw9-2FwzrGywwV0WC2wcxPLgE0gsHzYgeIUZR8VeEtEzyyFK-2FQIUErOj-2FRbsVf66IydJfQhzEEbXGSSKCvjMEf31Fi4tXar6W4u0aI3nF1gerYMvnzljHkUi1bXa2fTdPwsjr0EIBuz25AVfov9dM-2Fj7HAPL066N-2BvpANE8Kud3n8z4zuapz0IjxSpMaza2iMcgjwYVQonCiVU58zM9dBiSCmxdL8st4Yd07WoZ3pnEE-2Bm5SaovvrjmCZ-2FLxCfqwPi-2BqfGCAnfOw-3D-3D

What I see even after refreshing:

![image](https://cloud.githubusercontent.com/assets/11722025/9924280/e4d5a11c-5ccb-11e5-9854-cf9c6df15dd5.png)

**Comment by shlublu** [comment] 2015-09-17 06:30
Same here, I received a notification for Laos, and the link behaves as above.

**Comment by de-vries** [comment] 2015-09-17 15:51
I don't think the problem is in the email, the bookmark in my browser that should show me my home town also behaves as above.

**Comment by knikel** [comment] 2015-11-27 09:28
We had a faulty redirect, this has been now fixed.

**Closed by knikel** 2015-11-27 09:28 UTC
Labels: bug
