### ISSUE TITLE
GPS Fix issue

### ISSUE THREAD

**Issue by bitboy85** [mapillary/mapillary_issues#2597] opened 2017-06-14 05:42 UTC
Hi,

i tried mapillary but i noticed it seems to have problems getting a GPS fix when driving faster than 80-100kmh.
So i end up with lots lots of 1 picture sequences. Is there a way to delete them all? Removing all of them one by one would be a bit annoying.

**Comment by echeloni2p** [comment] 2017-06-14 06:53
HI!
it is a issue with your mobile gps, mapillary just uses the mobile GPS system.
You can delete all the folders in mapillary folder on your mobile with a file manager (or with a PC connected to it).
Usually under data/android/mapillary/files or alike...

echelon

**Comment by bitboy85** [comment] 2017-06-14 09:55
Hi thanks for reply. I use the same device with osmand and never had issues with gps.
As a suggestion it might be possible to build a "session" container around the sequences. A session is defined as the time between the user presses start and stop. So afterwards you can choose to upload (or delete) the whole session, or single sequences within. There should be an info how many Pictures are taken and how many have no gps info. This could be useful if the pictures are taken based on time, with only 2 or 3 missing in a row it should be easy to interpolate the position.

**Comment by gappleto97** [comment] 2017-06-14 20:36
OpenStreetCam also does not have this problem. And when I load up SatStat, the error never gets more than ~10m. Whereas in your app it frequently reports (on the same route, same speed) that the error is >15m, and then splits the sequence.

**Comment by aligitor** [comment] 2017-06-19 12:20
Isn't this issue related to #2573 ?

**Comment by gyllen** [comment] 2017-06-19 15:26
What platform are we seeing this problem on guys, both iOS and Android?

**Comment by gappleto97** [comment] 2017-06-19 15:57
I'm on Android. Given that he mentioned OsmAnd, I'm guessing the other user is as well.

**Comment by voschix** [comment] 2017-06-19 16:01
Just to be sure: you are not trying to get a GPS fix at 80km/h. GPS devices normally have problems getting a fix when moving at any significant speed. You need to have a GPS fix and then start moving.

**Comment by gappleto97** [comment] 2017-06-19 16:08
No. I'm getting a fix beforehand, then when I move with any significant speed (even as low as 30mph/50kph) it will flash that the GPS accuracy is low.

Doesn't happen all the time, though, so its difficult to reproduce.

**Comment by gyllen** [comment] 2017-06-19 16:22
@peterneubauer Seems like this is on Android, Im reassigns this to you.

**Comment by bitboy85** [comment] 2017-06-20 09:35
I'm on android and i had a fix beforehand. it just looses often Position during driving, than it comes back, takes one picture and loose fix again.

**Comment by gyllen** [comment] 2017-06-20 15:41
@ovivoda ^^^

**Comment by ovivoda** [comment] 2017-06-20 16:14
@bitboy85 Can you please send us some logs when this happens again?

**Comment by stev391** [comment] 2017-07-26 03:03
I have a the same issue.  It even reports at time that no GPS available, takes a photo with good fix then complains no GPS available.
I submitted a log to the mapillary log email address about 5 mins ago, referencing ticket 2598.  You may also find relevant information in there.  It is quite fustrating to be driving in quite open areas and then find that the Android App (3.72-BETA) has stopped taking photos for most of it, when other GPS based apps have my location spot on.

**Comment by eneerhut** [comment] 2017-08-29 02:24
Update 3.89 should have faster GPS fix. Has anyone been able to test and see if the issues are still occurring. Thanks!

**Comment by RussNelson** [comment] 2018-06-08 15:21
I'm still having this issue, but it's unrelated to speed. It happens on my bicycle as well as my car. Happens even if I sit there and wait for a fix before I start moving. My Google Pixel works fine with Ingress or OSMAnd. Doesn't work well with Mapillary.

**Comment by gyllen** [comment] 2018-06-08 15:43
@millenbop Reassigned to you

**Comment by RussNelson** [comment] 2018-06-11 16:31
GMS is enabled.

**Comment by ovivoda** [comment] 2018-06-12 08:46
@RussNelson please enable `Show detailed stats` and `Relaxed accuracy limits` from `Settings->Developer` and send me a screenshot of camera view and also let me know if you manage to capture.

**Comment by RussNelson** [comment] 2018-06-12 20:40
I covered over the camera so all the text would be visible. This is in my car. The "GPS Ok" was green nearly the whole time, except for a few moments where it sent gray for "Locating".
I think I captured. At least, I saw the screen go black. There might have been an issue with the temperature causing the phone to "shut down some activities" because it was too hot.
https://www.mapillary.com/app/user/russnelson will tell us how it worked.

![screenshot_20180612-154555](https://user-images.githubusercontent.com/1156994/41315940-ed1454de-6e5e-11e8-9b12-c4c351f19e35.png)

**Comment by RussNelson** [comment] 2018-06-13 22:31
It doesn't look good. In spite of the "GPS good", it didn't capture many photos, just 72. That might have been an issue with my phone's temperature: 43C, rising to 48C later. Maybe I could try it again first thing in the morning when it's cool.

**Comment by ovivoda** [comment] 2018-06-14 08:14
@RussNelson Indeed high temperatures will slow down the OS but it should still capture. What type of capture are you using? Time based/distance based, etc...?

**Comment by RussNelson** [comment] 2018-06-14 12:39
Distance based. I'll try it again.

**Comment by ovivoda** [comment] 2018-07-06 09:57
_mapillary_issues is no longer an active repository._

_This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!_

**Closed by ovivoda** 2018-07-06 09:57 UTC
