### ISSUE TITLE
web site: picture position temporarily wrong on the map

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2436] opened 2017-02-01 11:10 UTC
### Basic information
* Platform: ``Web`
* Version: `latest` 
* System/Browser: `Windows 10 with Firefox or Chrome or edge`

### Steps to reproduce behavior

1, Load
https://www.mapillary.com/app/?lat=35.20525584176042&lng=-100.78269589721933&z=15&focus=map&mapStyle=mapbox_satellite&pKey=w7E-UmWDDh9vpn0nzOqA5A&menu=false
2, switch to photo mode
3. go back to map mode; the centre has moved to a different, nearby location
4, select Mapbox Streets (or OpenStreetMap or ESRI)  layer and the picture pointer appears at that location on the map; switching between map layers, does not move it back to its correct position.
5. when you now use the move  arrows in the small photo window, the position indicator in the big map or satellite view wiggles a bit. After exactly 10 forward moves the position indicator jumps to the correct position again and the map window centre returns to its correct location

### Additional information

This works in the same way in Firefox, Chrome and edge on my Windows 10 computer

I have seen this frequently, but had not investigated its reproducibility. The number of "move" clicks to get the position indicator back to the correct position seems to be constant for a specific start location, but varies with the start location

... 

Screenshots can be supplied on request

**Comment by katrinhumal** [comment] 2017-03-29 13:40
@voschix Sorry about not getting back about this. I am not able to reproduce the problems in your example on Chrome. And in Firefox I actually get a different problem, namely that the position indicator just doesn't move, although with every "step" the map centres to the dot representing the image that is currently viewed (as it should). But it doesn't go yellow... But nothing like what you mentioned in 3. Does it still behave the same as described above for you?

**Comment by voschix** [comment] 2017-03-29 13:53
I have just gone to the example, and for me the problem has disappeared in Firefox (including the behaviour you mention) and Chrome.

**Comment by katrinhumal** [comment] 2017-03-30 08:07
That's nice. Closing this for now, but please let me know if you notice something like this again.

**Closed by katrinhumal** 2017-03-30 08:07 UTC
