### ISSUE TITLE
Please don't adjust the zoom when recentering on a marker

### ISSUE THREAD

**Issue by bhousel** [mapillary/mapillary_issues#2233] opened 2016-08-31 12:55 UTC
### Basic information
- Platform: `Web`
- System/Browser: `Chrome 52`
### Steps to reproduce behavior
1.  Zoom to z20
2.  Click a marker or use the navigation buttons
### Expected behavior

Map stays at z20
### Actual behavior

Map eases to z17
### Additional information

If I'm looking in detail at something, I'd prefer to keep the zoom where it is, rather than easing back to z17.

![mapillary_rezoom](https://cloud.githubusercontent.com/assets/38784/18129374/7966c8a2-6f58-11e6-924b-f5399decafea.gif)

**Comment by peterneubauer** [comment] 2016-08-31 15:09
+1 on this.

**Comment by de-vries** [comment] 2016-08-31 16:12
duplicate of #2079

**Comment by gyllen** [comment] 2016-08-31 16:32
Agree, we are tracking this issue and will report back when fixed.

**Comment by jfburke3** [comment] 2016-08-31 19:27
+1 from me, too.

**Comment by angelday** [comment] 2018-07-26 13:12
We addressed this actually, closing. https://github.com/mapillary/mapillary_issues/issues/2079#issuecomment-405846585

**Closed by angelday** 2018-07-26 13:12 UTC
Labels: affects-web-map, feature, info-tracked
