### ISSUE TITLE
Do not start a new sequence on GPS problems 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2136] opened 2016-07-29 20:54 UTC
### Basic information
- Platform:  `Android` 
- Version: `237` 
### Steps to reproduce behavior
1. Walk with weak GPS status (I had manual shooting) 
2. Make images 
3. loose GPS fix for a second or so 
### Expected behavior

After recover from the GPS problem the next images should be in the same sequence 
### Actual behavior

The jumping or invalid GPS fix started a new sequence

**Comment by echeloni2p** [comment] 2016-08-01 08:03
HI

sounds a bit like "start a new tack after 300m" in the settings, try to change that one.

echelon

**Comment by HolgerJeromin** [comment] 2016-08-01 12:55
My walk was 600 meters in total and were split into three sequences. I pushed the camera button every 5 to 10 meters

**Comment by katrinhumal** [comment] 2017-03-29 13:29
A little update here - so if the distance between two images is above a certain threshold (300m by default as @echeloni2p noted, can be adjusted in Settings->Capture), a new sequence will be started both in automatic and manual mode.

**Comment by HolgerJeromin** [comment] 2017-03-29 21:01
If the phone has bad position it will not make an images and should only start a new sequence while taking images.

**Comment by katrinhumal** [comment] 2017-03-30 08:05
Yes. If your setting is 300 m and you lose GPS for 200 m then there should not be a new sequence started. It's hard to troubleshoot the particular case you reported since it was a while ago, but if you experience this again, we need to look into why it's not behaving as intended. @HolgerJeromin Do you think you would be able to test the latest app version for this (by deliberately moving through an area where GPS might be bad, like around tall buildings or trees)?

**Comment by ovivoda** [comment] 2018-07-09 12:00
this issue should be fixed in the latest app version

**Closed by ovivoda** 2018-07-09 12:00 UTC
Labels: affects-android, bug
