### ISSUE TITLE
Weird interpolation kind of bug

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#2088] opened 2016-07-25 11:48 UTC
### Basic information
- Platform: iOS 9.3.3, iOS 5
- Version: 4.4.3
### Steps to reproduce behavior
1. I have no clue how to reproduce this
### Expected behavior

Having actual right coordinates on photos
### Actual behavior

See the photos starting from https://www.mapillary.com/app/user/virtakuono?lat=22.270722428555075&lng=39.089465242864435&z=17&pKey=K-ET32jKxceGGfLTcm-FvA I did a capture on my car, following the road on the map. For some reason, the app lost track of where it was, and next time it got back on the map, it interpolated the photos from the last-seen coordinate point to the current one, thus "cutting the corner".

**Comment by millenbop** [comment] 2016-07-25 14:18
The interpolation is correct. The problem is that the phone lost the GPS signal, but still reported it as OK and still took photos. As soon as the API reports bad GPS, capture is stopped. 

If you see this again, please let me know.

**Comment by Virtakuono** [comment] 2016-07-27 07:13
Here's another instance https://www.mapillary.com/app/user/virtakuono?lat=22.306418285655667&lng=39.12249658360301&z=16.44893205951124&pKey=kuWLjE_BmRpu8akU-6EgkQ

**Comment by Virtakuono** [comment] 2016-07-27 07:20
Yes. I the interpolation is correct in the sense that photos I have taken are interpolated between two points that I have been to. However, at the time the GPS signal was lost, I am pretty sure the phone did not know where exactly I was going and when it will get a good signal again. To me it seems from the amount of interpolation, that somehow the location information is being recorded dozens of seconds, even minutes after the photos were actually taken, when the app has two location points to interpolate between.

**Comment by millenbop** [comment] 2016-07-27 08:38
I was wrong about us interpolating, sorry. I checked the code and we only do that for action cameras, not the internal camera. So for every photo captured there is matching meta data file with the current GPS position reported by the API. If there is interpolation happening there is something wrong with the GPS or the phone in general.

I don't think the other example is not interpolated -- it looks like capture just have been paused.

On a related note, do you still have problems with lagging level?

**Comment by Virtakuono** [comment] 2016-07-27 08:41
I think there is some serious interpolation going on in this photo and the ones around it https://www.mapillary.com/app/?lat=22.310518200491202&lng=39.11755984834326&z=17&pKey=bYVCLRsA_2nlzmaALWtWpQ&focus=photo reportedly the location is in an area that is fenced off where I never was, and where there is certainly no road...

**Comment by Virtakuono** [comment] 2016-07-27 08:43
And what's this lagging level thing you mentioned? Perhaps I have problems that I haven't just paid attention to.

**Comment by millenbop** [comment] 2016-07-27 08:45
Ah sorry, this one here: #1657

**Comment by millenbop** [comment] 2016-07-27 08:48
Hmm the GPS behaves really oddly in your captures, don't know where to begin to troubleshoot to be honest.

**Comment by Virtakuono** [comment] 2016-07-27 11:38
This is of course an ugly "solution", but you could just see if the last 20 or so photos are perfectly aligned in a line, I think that should never happen thanks to instrumentation noise, even if you are capturing photos on a straight railway line...

**Comment by millenbop** [comment] 2016-07-27 11:45
I have just charged two iPhone 5 phones and is about to go testing. One uses iOS 8.1.2 and one 9.3.3. 

Which mode have you used? Driving? Do you have the map visible? Which capture rate? Wanna see if I can get the same errors as you so I can figure out what's going on.

**Comment by Virtakuono** [comment] 2016-07-27 11:48
I have done driving mode, with gopro and without, at various capture rates, around once or twice a second.

**Comment by millenbop** [comment] 2016-07-27 11:51
Oh you have been using GoPro, that changes things slightly. Which model?

**Comment by millenbop** [comment] 2016-07-27 11:57
Were all the above (1-3) sequences taken using a GoPro?

**Comment by Virtakuono** [comment] 2016-07-27 14:20
I think yes. With the not-so-officially-supported hero session 4...

**Comment by millenbop** [comment] 2016-07-29 09:29
We need to get one of those

**Comment by millenbop** [comment] 2017-04-05 11:24
Hey! Do you still experience this problem?

**Comment by Virtakuono** [comment] 2017-04-05 11:59
No. Unfortunately, the reason is that my iPhone got busted and I swapped to android. Sorry that I can't be of much help with this anymore :/

**Comment by millenbop** [comment] 2017-04-05 13:03
Oh ok. Did you erase all your photos btw?

**Comment by Virtakuono** [comment] 2017-04-05 13:15
Me? I think you're mistaking me for someone else...

Check with Madelen or Peter, they probably have the photos that you are looking for.

**Comment by millenbop** [comment] 2017-04-05 13:21
Ah ok, now I remember, sorry :) Anyway I'll close this issue for now. If the problems appear for you or someone else I'll reopen and start a new investigation.

**Closed by millenbop** 2017-04-05 13:21 UTC
Labels: affects-ios, bug
