### ISSUE TITLE
Cannot manually upload pictures taken with Mapillary Android App - "missing EXIF"

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#674] opened 2015-02-19 15:09 UTC
I was taking pictures with the Android App. I noticed that picture taking had stopped. The reason was that the microSD was full.
Uploading with the Mapillary App did not work: uploading indication cycled. Apparently it tried to upload unsuccessfully the first 23 of 239 pictures and then repeated the attempt cyclically.
I connected the phone via USB to a WIndows 8.1 computer. Found all 239 pictures ok (geolocalization worked fine with EXIF tool), but the manual upload does not work, the pictures are reported as having missing EXIF data, even though they have all the required fields (the pictures had been taken by the Mapillary App, so they should be ok)

![exif-screenshot](https://cloud.githubusercontent.com/assets/11076112/6269140/a0db1790-b851-11e4-8e24-4144a033af7e.png)

**Comment by gyllen** [comment] 2015-02-19 17:49
Yeah at the moment the manual upload does not work with phone images. We are working on it.

**Comment by polarbearing** [comment] 2015-02-19 18:50
Duplicate of #251 and #218

**Comment by lminko** [comment] 2015-06-29 18:55
Me too, cannot upload files manually.

**Comment by millenbop** [comment] 2015-11-18 09:46
Bumping this as more users have requested to be able to upload app photos via web.

**Comment by ybkuang** [comment] 2016-06-01 08:00
Uploading app photos through web uploader is enabled now.

**Closed by ybkuang** 2016-06-01 08:00 UTC

**Comment by kaitu** [comment] 2016-06-01 10:04
What happens when the geographic coordinates have been adjusted and Exif tags overwritten with the corrected values, but the mapillary tag still retains the original values? Are the adjusted or the original ones taken into account?
