### ISSUE TITLE
ios app does not always detect wifi state properly

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1949] opened 2016-06-13 20:15 UTC
quite often getting the following problem :
take photos, return to a location with wifi. the phone connects to the wifi, shows wifi indicator - but mapillary complains that it's a 3g/4g connection.

**Comment by millenbop** [comment] 2016-06-14 06:39
Thanks for reporting, will look into it! I haven't seen it myself though. Do you have any more details you can think of?

**Comment by richlv** [comment] 2016-06-14 09:09
not really. there's no more output, and it seems to happen ~20-40% of the time.in those cases, i just force-close the app (swipe up) and start it again, that always helps

**Comment by descilla** [comment] 2016-06-15 01:17
Hey,
I've this problem, too. But not as often as reported by @richlv (maybe ~ 5-10% of the time). It occurs since the last few versions of the iOS app (at least the both last ones).
For me it looks like it only happens if the app is active while the iPhone connects to a wifi network (and previously was not connected to a wifi network).

**Comment by millenbop** [comment] 2016-06-15 12:49
That's old code so wondering if an iOS update changed something. Nevertheless, a bug's a bug. I'll see if I can reproduce it and fix it.

**Comment by millenbop** [comment] 2016-06-15 13:20
It was indeed a bug in our code! Fixed now, available in next release.

**Closed by millenbop** 2016-06-15 13:20 UTC
Labels: bug, iOS

**Comment by richlv** [comment] 2016-06-15 13:38
mmmmmm, perfect, thank you. image collection getting a bit more pleasant by day :)
