### ISSUE TITLE
Better panorama symbolizer

### ISSUE THREAD

**Issue by Matthias84** [mapillary/mapillary_issues#1524] opened 2015-11-13 21:17 UTC
Panoramas have a special meaning (good overview, max. connectivity, ...) and users should be encouraged to add them. Currently there is just  a (mostly stupid) gps-track of this single panorama location. I recommend to use a icon instead.

**Comment by jesolem** [comment] 2015-11-13 22:34
Yes. We have a dupe of this. @knikel knows.

**Comment by knikel** [comment] 2015-11-20 12:55
Closing, as duplicate of https://github.com/mapillary/mapillary_issues/issues/1324 This will be added soon for both gl and non-gl map.

**Closed by knikel** 2015-11-20 12:55 UTC
