### ISSUE TITLE
Make rect draw not only topleft-bottom right

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary_issues#2048] opened 2016-07-22 09:01 UTC
It is IMHO a unnecessary limitation that blurs are only allowed to be
drawn from the left top corner to the right bottom corner.

**Comment by de-vries** [comment] 2016-07-22 09:27
duplicate of https://github.com/mapillary/mapillary-js/issues/163

**Comment by gyllen** [comment] 2016-07-22 22:29
Closing, known issue

**Closed by gyllen** 2016-07-22 22:29 UTC
Labels: elva, enhancement
