### ISSUE TITLE
Manual upload: Ask for angle wrt forward direction

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1111] opened 2015-06-22 08:37 UTC
When uploading pictures from a camera without compass using the "Manual Uploads" menu, a viewing direction of exactly northern is assumed. This almost always isn't correct. The usual step is then to go to the sequence settings and adjust the viewing direction with regard to the forward direction under e.g. http://www.mapillary.com/map/e/PbyfEVNvMq1zc2q3u22jNQ

When pictures without viewing direction meta-data are uploaded using "Manual Uploads", I would like to see either of the following implemented:

1. The uploader gets asked at which angle regarding forward direction the camera was placed.
2. An angle of 0 degree regarding forward direction is assumed. If it is not the case, the angle can be corrected later the same way as described above.

**Comment by jesolem** [comment] 2015-06-23 08:17
@ltog Thanks. Very valid request. My vote is for 2.

**Comment by de-vries** [comment] 2015-06-23 15:27
duplicate of #1066

**Comment by paulinus** [comment] 2016-06-01 14:03
I'm closing this so we can follow the progress on the duplicated issue #1066

**Closed by paulinus** 2016-06-01 14:03 UTC
