### ISSUE TITLE
Working Mapillary@android in background

### ISSUE THREAD

**Issue by zibik** [mapillary/mapillary_issues#908] opened 2015-04-08 21:54 UTC
I would like Mapillary app to be able to run the application in the background (or when display is turned off). Currently, this app works only when display is turned on. 
It will help saving the battery.
This function should be configurable.

**Comment by de-vries** [comment] 2015-04-08 22:31
Also useful when you need your phone for navigation.

**Comment by mprins** [comment] 2015-04-10 11:55
duplicate of #331 which was closed as "not going to happen"

**Closed** 2015-05-26 07:29 UTC

**Comment by iav** [comment] 2016-06-15 23:01
Now Mapillary official support capturing with action cameras without screens at all.
So, why I still should choose between mapillary capturing and navigation app?

Please, think again.
Hint: in my country capturing at public places is legal.

**Comment by gyllen** [comment] 2016-06-17 10:18
@jesolem This is a GREAT idea

**Comment by kaitu** [comment] 2016-06-17 12:31
related to #1001

**Comment by shlublu** [comment] 2016-06-17 12:45
Just a thought: using a notification or a LED pattern is probably sufficient to prevent the user from forgetting that the app is running background (re: https://github.com/mapillary/mapillary_issues/issues/331#issuecomment-56336085 ).
