### ISSUE TITLE
can't proceed in a sequence

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_issues#1468] opened 2015-10-27 06:18 UTC
see https://www.mapillary.com/map/im/1N8bGx5coL15y0k-WSV24g/photo and try to advance to the next image in the sequence - loading never finishes. this happens in other sequences, too

**Comment by de-vries** [comment] 2015-10-27 17:44
I'm getting the same problem with the sequences I uploaded last sunday. It also happens in other sequences, but there I can most of the time browse a lot of photos without any problem.
The symptoms for me: I try to go to the next photo and I get a spinner and nothing happens exept for a never ending high cpu usage.

**Comment by ybkuang** [comment] 2015-10-27 17:46
@de-vries can you give us links to some of those image when you hit spinner again? it will help us track the problem.

**Comment by de-vries** [comment] 2015-10-27 18:04
http://www.mapillary.com/map/im/dHrkgXSEs2qkGAcL4WG_gQ/photo
http://www.mapillary.com/map/im/mBF-_mcE_Qa_6E0Tdd83Aw/photo > lock to sequence > move forward.

btw: high cpu usage stops when I move t another tab, 
firefox 41 ubuntu

**Comment by de-vries** [comment] 2015-10-27 18:15
http://www.mapillary.com/map/im/vBCT0GiLKPygJe-oTyNWUw/photo > lock to sequence > move forward.

if you keep locked to sequence you can find a few more in the same sequence.

**Comment by de-vries** [comment] 2015-10-27 18:21
also it doesn't matter from where you approach a photo:
http://www.mapillary.com/map/im/fV_E902-LbOnVihFBlsWYA/photo > lock to sequence > move forward. 
and 
http://www.mapillary.com/map/im/9RUGJWf5y_j_fnyzfx85wg/photo > lock to sequence > move backward.
should lead to the same photo, both give a spinner.

**Comment by ybkuang** [comment] 2015-10-27 18:48
@de-vries Thanks for the details. At the first look, this is related to our database. We will investigate further and let you know when it is fixed.

**Comment by de-vries** [comment] 2015-10-27 18:53
another detail: 
http://www.mapillary.com/map/im/dHrkgXSEs2qkGAcL4WG_gQ/photo also doesn't load in the fallback-version (didn't try the others as I can't lock to sequence there)

**Comment by gyllen** [comment] 2015-10-27 20:15
@de-vries @richlv I am investigating this matter, we have all the image info but it seems like a replication component failed. Im trying to locate exactly when this error happened to try and pinpoint the error.

**Comment by richlv** [comment] 2015-12-09 06:04
just a small poke - this sequence still seems to be broken :)

**Comment by richlv** [comment] 2016-01-26 19:36
now it fails with "This image doesn’t exist, has been hidden or is part of a private project." :/

**Comment by richlv** [comment] 2016-03-12 09:04
this sequence is fixed now - thanks to whoever did that :)

**Comment by peterneubauer** [comment] 2016-03-17 15:17
I did :)

**Comment by voschix** [comment] 2016-03-26 14:59
This problem seems to be back since a couple of weeks. I get "This image doesn’t exist, has been hidden or is part of a private project" frequently in my recent sequences. 
E.g. sequence GiTxbTuXlcE4Qze4eUoZ7g
Try to go forward from http://www.mapillary.com/map/im/I-Xdt42O6U7QcKQI24f4UA/
Reproducible on Firefox and Chrome on a Windows 10 and on the Android app. Seems to be a problem of specific photos.

**Comment by richlv** [comment] 2016-03-27 16:26
could the effect @voschix is seeing actually be #1745 ?
do the problematic images go ok on their own a few days later ?

**Comment by voschix** [comment] 2016-03-27 18:18
Two observations:
1) the problem does not seem to go away with time
2) the photos that I cannot see using the web interface, seem to be
normally accessible in JOSM using the Mapillary plugin

**Comment by de-vries** [comment] 2016-03-28 08:02
@voschix, @jesolem, This issue was originally about some photos getting lost due to a server-side problem on 15 okt 2015. just like issues #1472 and #1507. So @voschix' problem is a different issue, most likely #1745, like @richlv said.

btw, I've checked all examples I gave above and they al seem to be fixed now.

**Comment by jesolem** [comment] 2016-03-28 13:18
Got it. Closing for #1745 instead. 

@voschix if #1745 is not the right issue for you, open a new one with your details. 

Thanks everyone

**Closed by jesolem** 2016-03-28 13:18 UTC
Labels: backend
