### ISSUE TITLE
Need a way to upload not all sequences

### ISSUE THREAD

**Issue by iav** [mapillary/mapillary_issues#851] opened 2015-03-23 17:03 UTC
Currently in android app on review section I can press upload button - and upload all data. I can't uload sequences one by one, by reviewing.
Will be useful to queue upload sequences one by one - with upload button inside sequence, or as option opened on long press on a sequence.

**Comment by HolgerJeromin** [comment] 2015-03-24 00:47
yes. Would love that. 
Or a way to mark a sequence (move to a special folder?) via preview on the laptop.
/mnt/sdcard/mapillary/new/2015-03-xxx...
/mnt/sdcard/mapillary/reviewed/2015-03-xxx...

would be very easy.

**Comment by jesolem** [comment] 2015-03-24 08:07
@iav Agree. This is how it works on iOS. We'll take a look at adding in upcoming Android version.

**Comment by vincentdephily** [comment] 2015-05-18 20:52
Duplicate of #964 ?

**Comment by iav** [comment] 2015-05-18 23:24
yes.

**Comment by HolgerJeromin** [comment] 2016-02-17 18:23
this is implemented in the meantime

**Closed** 2016-03-03 09:01 UTC
Labels: android, enhancement
