### ISSUE TITLE
Upload Needs WiFi error (when there is WiFi)

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1988] opened 2016-07-01 18:24 UTC
Device: iPhone 6S Plus
OS: iOS 9.3.2
Mapillary: 4.3.2

I've gotten this message a few times when attempting to upload. I've just finished taking some photos and now am looking to upload. The device is on WiFi.

The only workaround I've found is force quitting the app, and reopening. Then it will upload perfectly fine.

![2016-06-30 19 39 14](https://cloud.githubusercontent.com/assets/1827881/16530630/14a22c5e-3f97-11e6-91ce-f6332bcb3d2a.png)

**Comment by millenbop** [comment] 2016-07-04 11:20
Thanks for reporting! This is a duplicate of #1949 which already is fixed, but not out yet, so I'll keep this open until the fix i out so it won't get reported again.

**Comment by millenbop** [comment] 2016-07-12 08:20
Fixed in the current App Store version.

**Closed by millenbop** 2016-07-12 08:20 UTC
Labels: duplicate, iOS
