### ISSUE TITLE
Some sequences are uploaded only in Activity tab

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#1667] opened 2016-01-17 17:06 UTC
I don't know why but some sequences are uploaded correctly (by web or app) , are shown on activity/feed tab but these pics aren't shown on the other tabs, and not available on Map,Search and Profile.
When I clic from Activity /Feed these sets Mapillary is hungin' up.
Do I have to reupload these pics?

Example:

http://www.mapillary.com/map/s/DcU5cI4EaC8Rb8aNk9Hedw
http://www.mapillary.com/map/s/1aivnrfxyYV88WjLWrvByQ
http://www.mapillary.com/map/s/19M6bFAMaCRmCQtMq4hK2w

with latest chrome and firefox on win7

**Comment by echeloni2p** [comment] 2016-01-17 18:08
Hi!

Same happened to me, see #1654.

echeloni2p

**Comment by yopaseopor** [comment] 2016-01-17 21:55
Here it is all lost sequences:

done and geolocalized and upload via app android Xperia z3 compact:
http://www.mapillary.com/map/s/b4wuFnEYihq7HpGq_zpkVA
http://www.mapillary.com/map/s/DcU5cI4EaC8Rb8aNk9Hedw

done with app android Xperia z3 compact, geosetter localized upload via web win7 ,latest chrome and firefox:
http://www.mapillary.com/map/s/34Ovydp9_atUky4XPWoOnA
http://www.mapillary.com/map/s/19M6bFAMaCRmCQtMq4hK2w
http://www.mapillary.com/map/s/YdqVpOgRj_ckoqpVdpaTcQ
http://www.mapillary.com/map/s/XpzdR4WlxXoGYVimxuVExg
http://www.mapillary.com/map/s/1JbXDquujd-I_9nmvSap3Q
http://www.mapillary.com/map/s/1aivnrfxyYV88WjLWrvByQ
http://www.mapillary.com/map/s/sddy3KhmYgdrr7kubV0RgA
http://www.mapillary.com/map/s/YdqVpOgRj_ckoqpVdpaTcQ
http://www.mapillary.com/map/s/12lLy9ZKwNcB9_GHIwVL9g

**Comment by gyllen** [comment] 2016-01-17 23:10
@ybkuang This seems to be the same problem as in #1654 the images are there but lon/lat are 0 for all images in the sequence. Can you investigate EXIF for the following image Cp93v8HeIIG77nFUnqpdqQ ?

@yopaseopor The images in all of these sequences seems to be on null island, we are investigating.

**Comment by gyllen** [comment] 2016-01-21 01:31
After doing some testing here on the images it seems like they do not have any lon/lat set in the EXIF, can you guys doublecheck that @yopaseopor @echeloni2p 

ping @ybkuang

**Comment by echeloni2p** [comment] 2016-01-21 07:22
Hi
Sorry, cannot really check, made the pictures with the mapillary app and uploaded to mapillary, removed from mobile device after upload. So if they got no real gps data, the mapillary app is to blame and we cannot do much more except removing those pictures from the database, as I cannot view/edit/move them.

echeloni2p

**Comment by ybkuang** [comment] 2016-01-21 08:49
@echeloni2p @gyllen This is somewhat different from #1654. GPS info is not in EXIF ImageDescription but in the GPS Latitude/GPS Longitude. I will work on a patch in the backend to recover images of those cases. 

@peterneubauer in the meantime, can you check why GPS is not written to ImageDescription in the app?

**Comment by echeloni2p** [comment] 2016-01-21 12:55
Hi
@peterneubauer I did sent some mapillary logfiles from the app on last saturday to you, about some issues with the app not taking pictures while GPS was fine. Maybe related.

echeloni2p

**Comment by yopaseopor** [comment] 2016-01-22 19:20
-For the files of 2016_01_17 of Vilanova i la Geltrú (Tres tombs) original
pics has no geotag information :( .Done with app without any problem of
location and GPS range. I will try to geotag manually the pics .
For the pics of 2015_12_25 of Oviedo and Gijón they are geotagged later ,
manually but correctly.
Example of one pic:

---- ExifTool ----
ExifTool Version Number         : 9.56
---- File ----
File Name                       : 2015_12_25_10_38_56_054.jpg
Directory                       : .
File Size                       : 1134 kB
File Modification Date/Time     : 2015:12:30 15:04:58+01:00
File Access Date/Time           : 2016:01:02 01:11:32+01:00
File Creation Date/Time         : 2015:12:30 12:36:49+01:00
File Permissions                : rw-rw-rw-
File Type                       : JPEG
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Current IPTC Digest             : fd1d725a2e74a0e53b2528cf62b8dc4a
Image Width                     : 2048
Image Height                    : 1536
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
---- EXIF ----
Image Description               :
{"MAPCompassHeading":{"TrueHeading":3.3835959434509277,"MagneticHeading":0,"MAPCompassDirectionMode":1},"MAPVersionString":"1.69","MAPSettingsEmail":"
yopaseopor@gmail.com
","MAPSettingsUploadHash":"a82614580316c29dc58a66fa08d1d1febe25a176ae2eca8b4f0bf2ea7c4faafc","MAPPhotoUUID":"130774fb-8118-4566-b5de-2f16cbead400","MAPCaptureTime":"2015_12_25_10_38_56_054","MAPLocalTimeZone":"+0100","MAPCameraMode":1,"MAPSettingsProject":"","MAPSequenceCaptureUsed":"1","MAPSequenceUUID":"498f6805-b3a0-40ee-971c-e06b283d085f","MAPLightSensor":"221.0","MAPDeviceModel":"D5803","MAPDeviceMake":"Sony","MAPAccelerometerVector":{"x":0,"y":0,"z":0},"MAPCameraRotation":"0"}
Make                            : Sony
Camera Model Name               : D5803
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : CompeGPS
Modify Date                     : 2015:12:25 10:38:56
Y Cb Cr Positioning             : Centered
Orientation                     : Horizontal (normal)
Exposure Time                   : 1/500
F Number                        : 2.0
ISO                             : 50
Exif Version                    : 0220
Date/Time Original              : 2015:12:25 10:38:56
Create Date                     : 2015:12:25 10:38:56
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/498
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Light Source                    : Unknown
Flash                           : Off, Did not fire
Focal Length                    : 4.6 mm
Sub Sec Time                    : 261129
Sub Sec Time Original           : 261129
Sub Sec Time Digitized          : 261129
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 2048
Exif Image Height               : 1536
Custom Rendered                 : Normal
Exposure Mode                   : Auto
White Balance                   : Auto
Digital Zoom Ratio              : 1
Scene Capture Type              : Standard
Subject Distance Range          : Unknown
GPS Version ID                  : 2.0.0.0
GPS Latitude Ref                : North
GPS Latitude                    : 43.356778°
GPS Longitude Ref               : West
GPS Longitude                   : 5.855427°
GPS Altitude Ref                : Above Sea Level
GPS Altitude                    : 4294967295 m
GPS Img Direction               : 0
GPS Map Datum                   : WGS-84
Compression                     : JPEG (old-style)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Thumbnail Offset                : 7136
Thumbnail Length                : 4914
---- XMP ----
XMP Toolkit                     : Image::ExifTool 10.08
Description                     :
{"MAPCompassHeading":{"TrueHeading":3.3835959434509277,"MagneticHeading":0,"MAPCompassDirectionMode":1},"MAPVersionString":"1.69","MAPSettingsEmail":"
yopaseopor@gmail.com
","MAPSettingsUploadHash":"a82614580316c29dc58a66fa08d1d1febe25a176ae2eca8b4f0bf2ea7c4faafc","MAPPhotoUUID":"130774fb-8118-4566-b5de-2f16cbead400","MAPCaptureTime":"2015_12_25_10_38_56_054","MAPLocalTimeZone":"+0100","MAPCameraMode":1,"MAPSettingsProject":"","MAPSequenceCaptureUsed":"1","MAPSequenceUUID":"498f6805-b3a0-40ee-971c-e06b283d085f","MAPLightSensor":"221.0","MAPDeviceModel":"D5803","MAPDeviceMake":"Sony","MAPAccelerometerVector":{"x":0,"y":0,"z":0},"MAPCameraRotation":"0"}
Color Space                     : sRGB
Components Configuration        : Y*Cb*Cr*-
Custom Rendered                 : Normal
Date/Time Digitized             : 2015:12:25 10:38:56+00:00
Date/Time Original              : 2015:12:25 10:38:56+00:00
Digital Zoom Ratio              : 1
Exif Version                    : 0220
Exposure Compensation           : 0
Exposure Mode                   : Auto
Exposure Time                   : 1/500
F Number                        : 2.0
Flashpix Version                : 0100
Focal Length                    : 4.6 mm
GPS Img Direction               : 0
GPS Img Direction Ref           : Magnetic North
ISO                             : 50
Light Source                    : Unknown
Metering Mode                   : Multi-segment
Exif Image Width                : 2048
Exif Image Height               : 1536
Scene Capture Type              : Standard
Shutter Speed Value             : 1/498
Subject Distance Range          : Unknown
White Balance                   : Auto
Interoperability Index          : R98 - DCF basic file (sRGB)
Date Created                    : 2015:12:25 10:38:56.261129
Compression                     : JPEG (old-style)
Image Description               :
{"MAPCompassHeading":{"TrueHeading":3.3835959434509277,"MagneticHeading":0,"MAPCompassDirectionMode":1},"MAPVersionString":"1.69","MAPSettingsEmail":"
yopaseopor@gmail.com
","MAPSettingsUploadHash":"a82614580316c29dc58a66fa08d1d1febe25a176ae2eca8b4f0bf2ea7c4faafc","MAPPhotoUUID":"130774fb-8118-4566-b5de-2f16cbead400","MAPCaptureTime":"2015_12_25_10_38_56_054","MAPLocalTimeZone":"+0100","MAPCameraMode":1,"MAPSettingsProject":"","MAPSequenceCaptureUsed":"1","MAPSequenceUUID":"498f6805-b3a0-40ee-971c-e06b283d085f","MAPLightSensor":"221.0","MAPDeviceModel":"D5803","MAPDeviceMake":"Sony","MAPAccelerometerVector":{"x":0,"y":0,"z":0},"MAPCameraRotation":"0"}
Make                            : Sony
Camera Model Name               : D5803
Orientation                     : Horizontal (normal)
Resolution Unit                 : inches
Software                        : 23.4.A.1.264_6_f1000010
X Resolution                    : 72
Y Cb Cr Positioning             : Centered
Y Resolution                    : 72
Create Date                     : 2015:12:25 10:38:56.261129
Modify Date                     : 2015:12:25 10:38:56+00:00
---- IPTC ----
Caption-Abstract                :
{"MAPCompassHeading":{"TrueHeading":3.3835959434509277,"MagneticHeading":0,"MAPCompassDirectionMode":1},"MAPVersionString":"1.69","MAPSettingsEmail":"
yopaseopor@gmail.com
","MAPSettingsUploadHash":"a82614580316c29dc58a66fa08d1d1febe25a176ae2eca8b4f0bf2ea7c4faafc","MAPPhotoUUID":"130774fb-8118-4566-b5de-2f16cbead400","MAPCaptureTime":"2015_12_25_10_38_56_054","MAPLocalTimeZone":"+0100","MAPCameraMode":1,"MAPSettingsProject":"","MAPSequenceCaptureUsed":"1","MAPSequenceUUID":"498f6805-b3a0-40ee-971c-e06b283d085f","MAPLightSensor":"221.0","MAPDeviceModel":"D5803","MAPDeviceMake":"Sony","MAPAccelerometerVector":{"x":0,"y":0,"z":0},"MAPCameraRotation":"0"}
Application Record Version      : 4
---- Composite ----
Aperture                        : 2.0
GPS Altitude                    : 4294967295 m Above Sea Level
GPS Latitude                    : 43.356778° N
GPS Longitude                   : 5.855427° W
GPS Position                    : 43.356778° N, 5.855427° W
Image Size                      : 2048x1536
Shutter Speed                   : 1/500
Create Date                     : 2015:12:25 10:38:56.261129
Date/Time Original              : 2015:12:25 10:38:56.261129
Modify Date                     : 2015:12:25 10:38:56.261129
Thumbnail Image                 : (Binary data 4914 bytes, use -b option to
extract)
Focal Length                    : 4.6 mm
Light Value                     : 12.0

I attach the pic

**Comment by echeloni2p** [comment] 2016-01-24 10:27
Moin!

It did happen again on all 50 tracks from yesterday, nearly 4000 pictures I´ve taken for some talsk I plan to give.
Is there any chance to see them on map soon (tm) ?

All pictures taken with mapillary android app, all taken yesterday, some tracks with "ignore gps location", some not. 
Does the "skip GPS location" remove GPS from all pictures in the track or just take pictures and write GPS into it and server decides which GPS is too bad?

Also: could be the android app does not change settings while being active, e.g. even if I unmark that settings, the mapillary app will follow the new setting only after I killed it from memory and reload all settings again?

I got a tracelog from yesterday, 11MB in size:
https://helene.cgv.tugraz.at/owncloud/index.php/s/nuVRLGuJKyjlKAK
This one does look fine, with GPS information in it. 
So, please, check this, it is annoying to walk around some time in cold and get no results...

echeloni2p

**Comment by peterneubauer** [comment] 2016-01-24 11:23
Hi there,
Will check the files as soon as I get home. The ignore location setting is
not removing anything but it will take pictures even if there is no
location fix, which will lead for these images to end up on Null Island.
Will try to check what might be wrong. The images are uploaded and not
showing up on your profile?

**Comment by echeloni2p** [comment] 2016-01-24 17:59
Hi!

Yeah, images are on http://www.mapillary.com/profile/aceini/activity noted as uploads, but not on http://www.mapillary.com/profile/aceini/uploads - see the long list of 50 tracks uploaded yesterday, but last on uploads is from last weekend.
As "images processing" in my profile shows 52 (for some month already), I think those images are already processed, but did not reach the map.
I do know most of pictures did have had a green GPS state in mapillary app.

Hm. Todday I did >3k photos with good GPS, currently not on map, but still uploading. None of them is showing as "processing". Strange.

echeloni2p

**Comment by gyllen** [comment] 2016-01-24 20:00
@echeloni2p They should now be visible in your profile.

**Comment by echeloni2p** [comment] 2016-01-25 09:20
Hi

yeah, now the pictures from saturday are visible. Maybe the site had a hickup, maybe not.
But e.g. those http://www.mapillary.com/map/s/XybKjeT-S9qse2cULakPJQ are still missing.

echeloni2p

**Comment by gyllen** [comment] 2016-04-11 00:57
@peterneubauer Can you check why this sequence is still missing?

**Comment by peterneubauer** [comment] 2016-04-11 07:44
@gyllen http://www.mapillary.com/map/im/ql5KYUyqNz_F_qFs8hz_lg/photo is not loading, but the els image is there, with the right sequence. Can you check?

**Comment by gyllen** [comment] 2016-08-10 03:43
@echeloni2p @yopaseopor Im looking into some inconsistencies for some sequences, I would be happy if you could go through your images and see if it looks better.

For http://www.mapillary.com/map/im/ql5KYUyqNz_F_qFs8hz_lg/photo it seems like its on null island though.

**Comment by peterneubauer** [comment] 2018-08-28 13:49
Just checked - the NULL island image is not having any lat/lon info. Closing this for now as I think the issue is outdated by now.

**Closed by peterneubauer** 2018-08-28 13:49 UTC
