### ISSUE TITLE
Spurious wrong "photo details" pop-up wondow

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2464] opened 2017-02-19 15:15 UTC
### Basic information
* Platform: `Web`
* Version: `web browser version present on 19 Feb 2017` 
* System/Browser: `Windows 10 with Firefox or Chrome`

### Steps to reproduce behavior

 1. Open Mapillary Viewer 
 2. Open a photo in Photo View
 3. Click the three dots at the bottom right to open the "photo details" popup window

### Expected behavior
The normal photo details  window opens in the right hand side of the window.
To close this pop-up window it is sufficient to click anywhere on the Mapillary browser window outside the "photo detail" window
![correct photo details](https://cloud.githubusercontent.com/assets/11076112/23103598/9a978ac4-f6bd-11e6-88b1-f427d0670115.jpg)

### Actual behavior
_Sometimes_ a different type of "photo details" window pops up in the left hand part of the main window It is not functional (no working links in it) and it does not go away by clicking outside the pop-up window. To get rid of the fake "photo details" window you need to reload the browser page.
![fake photo details](https://cloud.githubusercontent.com/assets/11076112/23103597/95e16a2c-f6bd-11e6-96a2-6385d1e3a623.jpg)

### Additional information
The event is rare, but annoying, in particular if you are using filtering, which you need to reestablish every time you use the reload-pge mechanism to get out of the false pop-up window situation

**Comment by nickplesha** [comment] 2017-03-22 13:55
@voschix Thanks for reporting this. A situation like this would occur when there's an unexpected error while something is being loaded and the whole Javascript on the page breaks (thus the visual glitches). Can you reproduce this error at a specific location or in some situation? When this happens, the browser error console will show the error message that would help us pinpoint this bug.

**Comment by voschix** [comment] 2017-03-28 16:21
I attach a screenshot from a Chrome session that shows the last two errors in the log after such an event. As they show no date/time information, I have no idea if they are related o this event.
![ashampoo_snap_2017 03 28_18h19m18s_005](https://cloud.githubusercontent.com/assets/11076112/24415908/4a17c652-13e3-11e7-909d-285c4eedbf11.jpg)

**Comment by nickplesha** [comment] 2017-05-15 13:11
@voschix Thanks for your help. This error was due to an error with authenticating and should be fixed now.

**Closed by nickplesha** 2017-05-15 13:11 UTC
