### ISSUE TITLE
Optimize blur mode

### ISSUE THREAD

**Issue by GITNE** [mapillary/mapillary_issues#1748] opened 2016-03-13 13:43 UTC
Please optimize the blur mode on the website so that when editing a sequence the next and/or previous blurs and photos are pre-loaded to greatly improve responsiveness and reduce latency. Currently, almost half of the time is spent on waiting for a response from the server when sequentially editing/reviewing a sequence for blur requests. This time could go into reviewing and editing more photos in the same time.

**Comment by richlv** [comment] 2016-03-25 17:57
duplicate of #1268

**Comment by jesolem** [comment] 2016-03-25 21:20
Closing, tracking in #1268 instead.

**Closed by jesolem** 2016-03-25 21:20 UTC
