### ISSUE TITLE
[Traffic sign game] Possibility to add comments or codes to the unknown signs

### ISSUE THREAD

**Issue by yopaseopor** [mapillary/mapillary_issues#977] opened 2015-05-02 11:29 UTC
Playing and thinking about traffic game recognition of unknown signs what about the possibility of insert code or comment to classify the sign?

 Example: we can use the values of OSM to this:

http://mapillary.com/map/im/yNnrCNkKlJZ3pBvfEtpdtA

will be highway=milestone

**Comment by de-vries** [comment] 2015-05-02 15:43
duplicate of #945

**Comment by jesolem** [comment] 2015-05-03 05:35
Let's track this under #945 (closing)

**Closed by jesolem** 2015-05-03 05:35 UTC
