### ISSUE TITLE
Fix Uruguay borders

### ISSUE THREAD

**Issue by willemarcel** [mapillary/mapillary_issues#465] opened 2014-11-25 14:59 UTC
The Uruguay borders need to be fixed, because part of Montevideo and others cities are out of the polygon: http://www.mapillary.com/map/places/uruguay

**Comment by gyllen** [comment] 2015-02-18 21:12
We will fix that. We are getting better selection algorithms in place at the moment.

**Comment by de-vries** [comment] 2015-03-01 12:15
duplicate of https://github.com/mapillary/mapillary_issues/issues/739

**Comment by gyllen** [comment] 2015-06-26 18:36
See answer in #508 tagging this as border in the meantime

**Comment by richlv** [comment] 2017-12-01 14:15
the latvian border is still messed up, i assume the uruguayan (uff) one is the same ?

**Comment by peterneubauer** [comment] 2017-12-01 14:36
Uruguay is at https://www.mapillary.com/app/stats/85632511?lat=-32.564052001766&lng=-55.75852824749995&z=6.7764733435440885 and looks better than before to me?

**Closed** 2017-12-05 10:15 UTC
Labels: affects-backend, affects-backend-borders, bug
