### ISSUE TITLE
No lens correction on images from Rollei S5, uploaded via script

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1192] opened 2015-07-30 06:12 UTC
A while ago @ybkuang implemented a correction against the fish-eye lens distortion of pics taken with the Rollei S5. This works fine when uploading via the manual upload, but when using the upload.py script there is no correction done.

Photos that still need correction are those I've uploaded on june 10, 16 and 26.

**Comment by ybkuang** [comment] 2015-07-30 06:51
@de-vries can you give me a link to one of the sequences? thanks

**Comment by de-vries** [comment] 2015-07-30 07:26
here you go: http://www.mapillary.com/map/im/fThQLFgsVrltZwIvDjEn8g

**Comment by ybkuang** [comment] 2015-07-30 14:59
@de-vries This is because in the exif ImageDescription field: MAPCameraMake='none'. The image processing pipe is using MAPCameraMake='Bullet5s' to determine whether len-distortion should be applied. I think the problem is the in the upload script that it doesn't find Make/Model correctly. I will check on that. Let's wait a bit for your uploads before we fix that. Sorry about this.

**Comment by ybkuang** [comment] 2015-07-30 15:30
@de-vries I did a quick fix to mapillary_tools. For your next upload, try the latest version of mapillary_tools. Also can you give me the list of sequences (if there are not that many) that are missing len-correction? I will try to rerun the processing for you manually. Thanks!

**Comment by de-vries** [comment] 2015-08-01 09:22
@ybkuang I have to admit that I'm not sure any more that I've used the upload scripts correctly.
 I used `upload_each_folder_as_sequence.py`. From its name and documentation I expected it to upload the photos, but it didn't. It only added the exif-description tag. After  I used `upload_each_folder_as_sequence.py` I've uploaded the photos with `upload.py`.

 `upload.py`  and `upload_each_folder_as_sequence.py` are both in the same folder, the photos were in a different one.

anyway, here are the sequences in question:

http://www.mapillary.com/map/s/7Jhh2ubq0ZcdwjkB1tdgxA
http://www.mapillary.com/map/s/uj-urVyTneKeEJG49KNz5Q
http://www.mapillary.com/map/s/77i6Bml9Dmf68XkUEd9i5A
http://www.mapillary.com/map/s/WznuzthZj3WnLzjcxEANDw
http://www.mapillary.com/map/s/VE1ZIgiO6HGo8i2shke8sw
http://www.mapillary.com/map/s/G-0cF2atqYx1J0yMRoBOfg
http://www.mapillary.com/map/s/K5CP8MJTKMavSjGybWmGWQ
http://www.mapillary.com/map/s/kDaoKP9kUQPw3K9yFzw7YQ
http://www.mapillary.com/map/s/v0V7X6pSStvcyJV9aT-ZxA
http://www.mapillary.com/map/s/AXonyEtGG7ocK1BJ2u4VtA
http://www.mapillary.com/map/s/bk2oxGGZl7lxzc4QJTunKw
http://www.mapillary.com/map/s/cRefRmMnpHkjD0qzrDpxyA
http://www.mapillary.com/map/s/g88K1Gik8y3oBZhNrfe-ug
http://www.mapillary.com/map/s/262jVq37uE0Ca9yhbbaynA
http://www.mapillary.com/map/s/EM6ATMP8xkJnCLSYnUjQPA
http://www.mapillary.com/map/s/WEoabiG7tibBXCOjdSITVg
http://www.mapillary.com/map/s/eo8gDTiv0JPOmP3x0p8_tw
http://www.mapillary.com/map/s/o3R8dqHDhw43QKz0--Iugw

**Comment by ybkuang** [comment] 2018-07-19 21:54
@de-vries we no longer do undistorion on the images directly. We're working on enabling distortion in the viewer instead. Closing this.

**Closed by ybkuang** 2018-07-19 21:54 UTC
Labels: affects-vision-ip, bug
