### ISSUE TITLE
Compass locked direction/angel

### ISSUE THREAD

**Issue by VikDD** [mapillary/mapillary_issues#1313] opened 2015-08-25 06:26 UTC
My phone compass is lame and I use "compass locked forward" option in car, but some times I can't set phone to 0 degrees direction (the most frequent range -5 to 5), somebody use publick transport for shooting, and direction can be variety (most popular, I think, 90-180-270 +/- 5 degrees). May be you extend this option to set variable angel, not only 0 (forward).

**Comment by shlublu** [comment] 2015-08-25 06:34
There's a workaround: tyou can apply a fixed angle to the whole sequence after having uploaded the pictures in the "edit" page of the sequence. But it's true it would be nice to have a way to do it before.

**Comment by polarbearing** [comment] 2015-08-25 07:30
Duplicate of #219. Please correct title to 'angle' to make the issue better searchable.

**Comment by jesolem** [comment] 2015-08-25 07:54
Thanks @VikDD - we're tracking this one in #219 (thanks for connecting @polarbearing )

**Closed by jesolem** 2015-08-25 07:54 UTC
