### ISSUE TITLE
Blur request accepted with a big offset, blurred wrong area

### ISSUE THREAD

**Issue by vincentdephily** [mapillary/mapillary_issues#1445] opened 2015-10-12 13:33 UTC
Hi just got an email notifying that my photo http://www.mapillary.com/map/im/auRqZ_pkA456pFCDsUkz2g had been blured by another contributor. But when opening the photo, the blur areas is at the people's feet rather than on their faces. I don't know wether the issue happened during the blur request, during review, or afterwards.

**Comment by jesolem** [comment] 2015-10-13 05:04
We should investigate. Thanks for reporting @vincentdephily

**Comment by de-vries** [comment] 2015-10-13 06:41
I've got something similar: http://www.mapillary.com/map/im/YqQtNHh0-UHV3k1pi8vvxg/photo was blurred by @travel193 
I received a email about it at 06-10-15 11:18

**Comment by travel193** [comment] 2015-10-13 06:46
Thanks @de-vries . Will check if I misjudged it. Either way a fix for different aspect ratios is needed for blurring.

**Comment by nighto** [comment] 2015-11-06 18:46
I noticed it as well in some of my pictures a week ago.

**Comment by travel193** [comment] 2015-11-06 18:48
Hi @nighto ,
Do you know the blur date for this? Shouldn't be happening now.

**Comment by nighto** [comment] 2015-11-11 16:37
I'll give it a try checking for plates and faces on my pictures and will give a feedback asap here.

**Comment by nighto** [comment] 2015-11-11 18:05
Seems to be fixed. But I noticed that you can only draw a blur rectangle from top left to bottom right; if you try another way (such as top right to bottom left) it doesn't work. For instance:

![image](https://cloud.githubusercontent.com/assets/397851/11098720/eb5c060a-888d-11e5-9d33-af545f4728f8.png)

I drew for squares from the most away point to the center. Only the top left one (drawn from top left to bottom right) was accepted; the others are apparently with zero dimention.

**Comment by nighto** [comment] 2015-11-11 18:05
(Let me know if I should open another bug request for this.)

**Comment by nighto** [comment] 2015-11-11 18:09
Just to make it clearer, I made a quick and dirty Paint mock to better explain what I meant on the other post:

![image](https://cloud.githubusercontent.com/assets/397851/11098801/93f6bf4e-888e-11e5-91da-86a9d10b8f56.png)

**Comment by nighto** [comment] 2015-11-11 18:56
@travel193 just happened again. Don't really know why. Didn't change the browser window size or whatsover. I took a picture of the PC screen to show (because taking a screenshot wouldn't get the mouse cursor):

![photo140638738923501902](https://cloud.githubusercontent.com/assets/397851/11099885/1ddeb4f4-8895-11e5-85fe-c1d0cdbe5587.jpg)

**Comment by travel193** [comment] 2015-11-12 14:49
Thanks @nighto . Exactly the same issue.
Can include the blurring from right to left and bottom left upwards there as well unless @knikel wants a separate issues for it.

**Comment by nicolas17** [comment] 2015-11-13 11:18
This issue got messy; I see multiple problems here. The blur editor sometimes creates offset rectangles, the blur editor doesn't let you draw rectangles in directions other than down+right, and these wrong blur rectangles shouldn't have passed approval.

**Comment by ybkuang** [comment] 2015-11-13 11:23
@nighto @de-vries @vincentdephily Sorry about this. The rectangles with offsets are related to mis-alignment of edit layer and image layer of the viewer. We are working on a solution for this.

**Comment by nighto** [comment] 2015-11-13 11:44
@ybkuang that's ok. most of the times all I need to do is refresh the page. about the rectangle draw direction, should I open another issue?

**Comment by ybkuang** [comment] 2015-11-13 11:49
@nicolas17 Yes. Make a separate issue for drawing direction will be great. 

As for the alignment, so refreshing for the same image fixes the alignment?

**Comment by nighto** [comment] 2015-11-13 11:56
@ybkuang most of the time, yes. I tried to find out what could possibly trigger this, thought about the download bar on Chrome, but it seems it's not the case.

**Comment by richlv** [comment] 2015-11-14 17:13
this issue seems to be a duplicate of #1415 actually

**Comment by knikel** [comment] 2015-11-20 15:57
There have been numerous improvements rolled out to the blurring tool recently, this should be fixed too. To give you more context: we're using the actual photo for calculating the where the blurs should be placed on top of the viewer. If it happens again, we'll debug further. Closing for now. Thanks @paulinus and @oscarlorentzon!

**Closed by knikel** 2015-11-20 15:57 UTC
Labels: editor
