### ISSUE TITLE
Android: unable to login using openstreetmap login

### ISSUE THREAD

**Issue by agilob** [mapillary/mapillary_issues#2691] opened 2017-09-02 07:31 UTC
### Basic information
* Platform: `Android`
* Version: 6.0

### Steps to reproduce behavior

 1. Login using openstreetmap login form
 2. Log in and grant permission 
 3. Login succeeded
 4. Toast login failed shows
 5. Stuck on waiting for login

![screenshot_20170902-082539](https://user-images.githubusercontent.com/2544251/29993792-1b41dc3a-8fb9-11e7-9fb2-2b791dd83d5d.png)
![screenshot_20170902-082545](https://user-images.githubusercontent.com/2544251/29993794-2113c38a-8fb9-11e7-8a2c-7634687888b3.png)

**Comment by Alessandro-Barbieri** [comment] 2017-09-02 19:31
Confirm

**Comment by katrinhumal** [comment] 2017-09-05 09:08
@agilob and @Alessandro-Barbieri just to confirm - have you created a Mapillary account previously?

You can't use your OSM account on Mapillary. You can just use it to log into your Mapillary account. That means that you first need to create a Mapillary account and link it to your OSM account (can be done both during signup or later in your profile settings on the web), and then you can start using your OSM account to log in. In any case, you will need to choose a Mapillary username and a contact email first when you sign up with Mapillary.

**Comment by agilob** [comment] 2017-09-05 13:30
>have you created a Mapillary account previously?
>You can't use your OSM account on Mapillary. You can just use it to log into your Mapillary account

No, I assumed I can use oauth2 token from OSM to login to Mapillary. I'll try again later.

**Comment by Alessandro-Barbieri** [comment] 2017-09-05 14:26
I have an osm account linked to my mapillary account

**Comment by katrinhumal** [comment] 2017-09-06 13:50
@agilob great - looking forward to more feedback.

@Alessandro-Barbieri I am able to log in successfully right now... could you please give it another try, and if still failing, let me know which Mapillary version, device, and Android version you have?

**Comment by Alessandro-Barbieri** [comment] 2017-09-07 17:22
@katrinhumal now works

**Comment by agilob** [comment] 2017-09-08 09:13
1. I created account on Mapillary using webbrowser and registering using OSM.
2. Tried to login using OSM on mobile phone
3. Same result as in the top comment.

4. I registered on mobile phone using OSM
5. Login as successful.

**Comment by katrinhumal** [comment] 2017-09-10 16:36
@agilob Thanks for trying! So just to make sure I understood you correctly, it works when you've linked your OSM account for login on mobile signup, but not when you've done it on web signup?

**Comment by agilob** [comment] 2017-09-11 19:56
>it works when you've linked your OSM account for login on mobile signup, but not when you've done it on web signup?

It seems so. There was a difference in behaviour described in the top comment tho. Look at the second screenshot, in case 1. there was just no "Trying to log you in" it just failed and I got a white screen from OSM webpage (there was an update since I opened the issue).

**Comment by katrinhumal** [comment] 2017-09-12 17:15
@agilob Thanks for clarifying! We will look into this asap.

**Comment by mxa** [comment] 2017-09-16 21:47
more login woes here: https://forum.mapillary.com/t/im-locked-out-of-the-app/1192

**Comment by katrinhumal** [comment] 2017-09-19 11:38
@ovivoda will you please take a look?

**Comment by ovivoda** [comment] 2017-09-20 10:04
Alright I just created a new OSM account and tested this again:

This are the steps that need to be taken in order to use a OSM account with Mapillary app:

1. Create a OSM account(if you do not have one already)
2. Open Mapillary app and Signup with OSM account. Please make sure you signup and not login.
3. Enter OSM e-mail and password when asked in mapillary app
4. Press Signup

**Comment by katrinhumal** [comment] 2017-09-26 19:35
@agilob Would you please try and install http://android-releases.mapillary.io/Mapillary_Android_v3.100-SNAPSHOT2.apk and see if this fixes the issue?

**Comment by nereocystis** [comment] 2018-01-04 01:51
This apk fixed my problem.
Until recently, I had been able to log onto the Mapillary Android app using openstreetmap. This morning, I couldn't. Repeatedly tried, including deletion and reinstall of app. No luck.

Then I installed the above apk, and everything works again.

**Comment by nereocystis** [comment] 2018-01-04 01:54
I spoke too soon. Sometimes it works, sometimes it doesn't. I lost the ability to use Mapillary Android for a few days, trying various apks. Finally, I went back to the version above and managed to log in as openstreetmap, though not with Mapillary email. 

I lost the connection again today, and eventually got it back again.

Suggestion: It should be possible to capture without logging in. What if I am far away from a network connection and want to record images. I should be able to use the app anyway.

**Comment by ovivoda** [comment] 2018-01-04 12:12
@nereocystis Can you please install the latest APK from GooglePlay v3.117 that is and please send us the logs if this happens again so we can see what is wrong.

**Comment by mxa** [comment] 2018-01-04 17:06
I second the suggestion by @nereocystis . Would have liked to add some mapillary pictures on a North Korea trip but could not because I was logged out and there is obviously no internet.

**Comment by nereocystis** [comment] 2018-01-04 20:43
I did try 3.117 over the weekend also, and had the same problem with logging in using Mapillary. It is working right now, of course.

Full disclosure, my phone is older, and does have some memory issues. I don't believe this is relevant here, but I might be wrong.

**Comment by nereocystis** [comment] 2018-01-04 21:50
After rebooting the phone, I can't log in via openstreetmap again.

How do I send logs without logging in?

**Comment by nereocystis** [comment] 2018-01-05 01:21
BTW, I believe that I am logging on, but never see the standard mapillary screens.

If I enter an incorrect password, then I get a failure.

Instead, I just return to the login screen.

**Comment by nereocystis** [comment] 2018-01-05 01:30
@mxa 
I just added an issue to allow uploads without logging in:

https://github.com/mapillary/mapillary_issues/issues/2844

**Comment by mxa** [comment] 2018-01-05 12:25
@nereocystis capture you meant. Thanks.

**Comment by nereocystis** [comment] 2018-01-05 17:23
@ovivoda I can't install 3.102-SNAPSHOT2 above. Android complains that it appears to be corrupt.

**Comment by nereocystis** [comment] 2018-01-05 17:24
@mxa Yes, capture without logging in. Upload should require logging in

**Comment by nereocystis** [comment] 2018-01-05 17:24
After rebooting the phone, I can't log in via openstreetmap again.

How do I send logs without logging in?

**Comment by nereocystis** [comment] 2018-01-05 18:02
@ovivoda OK. Deleted mapillary, then installed 3.102-SNAPSHOT2 and there was success.

Log in via Mapillary email failed, openstreetmap succeeded. Attached trace.
[mapillary_trace.txt](https://github.com/mapillary/mapillary_issues/files/1607468/mapillary_trace.txt)

**Comment by ovivoda** [comment] 2018-01-09 10:24
@nereocystis Thanks! Can you please share your user name/e-mail

**Comment by mxa** [comment] 2018-01-14 14:26
Just got a notification on the phone that someone has blurred some pictures i had uploaded. (So obviously I am logged in), then selecting the notification I get presented the login screen as if I were logged out. At least the login works now, but this issue is still there.

**Comment by nereocystis** [comment] 2018-01-14 16:58
@ovivoda Forgot that part nereocystis and kevin@kelphead.org

**Comment by nereocystis** [comment] 2018-01-14 17:02
@mxa I have occasionally had notice that photos have been published, or that I had blurred photos, but could not see see the photos. That matches my feeling that the login succeeded, though the app seems to think otherwise.

**Comment by mxa** [comment] 2018-01-15 10:14
@nereocystis that's another issue and never worked for me (seeing the actual pictures where blurrs were made). I am talking about being presented with the login screen (and thus barred from using the app) while being logged in.

**Comment by nereocystis** [comment] 2018-01-15 17:27
@mxa, I see that also. I receive notifications, even though the app still wants me to log in.
It makes me think that the login succeeded, behind the scenes, though the app did not record the success.

**Comment by jfburke3** [comment] 2018-01-16 06:23
Have any of you moved the app to your SD card?

**Comment by nereocystis** [comment] 2018-01-16 06:48
Yes, I have moved the app to the SD card.

**Comment by mxa** [comment] 2018-01-16 06:54
@jfburke3 yes, me too.

**Comment by jfburke3** [comment] 2018-01-16 14:35
I wonder if what @peterneubauer said on #2515 applies here:  "When it comes to moving the app to the SDCard, that should be possible, but when you do this, the app doesn't have access anymore to the system account manager and you might be forced to log in every time you start the app."

**Comment by mxa** [comment] 2018-01-16 15:11
Not sure... I stay in even across restarts of the phone, just sometimes I am 'logged out' but actually just locked out, because I still get notifications and such, so the app is actually still logged in.

**Comment by ovivoda** [comment] 2018-01-18 09:59
@mxa @nereocystis Can you please move the app back to internal memory and let me know if this fixes the issue.

**Comment by nereocystis** [comment] 2018-01-24 01:25
@ovivoda I experimented a bit more. Moving  the app to internal memory does solve the problem, after I delete mapillary app, and then reinstall it.

I noticed a similar problem with different app, ClockSync. Following the same procedure solved the problem. 

The issue is not mapillary-specific.

**Comment by mxa** [comment] 2018-02-07 21:28
@ovivoda I moved the mapillary app back to the internal memory, but the issue is still the same.

**Comment by nereocystis** [comment] 2018-02-07 21:50
And 2 weeks on, I have had success with 2 Androids using internal memory, not needing additional logins.

Strange.

**Comment by ovivoda** [comment] 2018-02-08 07:29
@mxa Please try with http://android-releases.mapillary.io/Mapillary_Android_v3.102-SNAPSHOT2.apk and send me the logs back for the phone where the app is not working

**Comment by mxa** [comment] 2018-02-09 20:01
@ovivoda my apologies, I don't have time at the moment to do this.

**Comment by pczaja** [comment] 2018-05-16 07:37
Same issue here. Can't login via OSM account authentication. On touching "sing up" and choosing signing in via "Openstreetmap" the OSM authentication page is shown. After granting rights to access OSM account settings and touching "Grant access", Mapillary app shortly shows a progress swirl saying "signing you in..". Then quickly a requester is shown "Create account – Mapillary needs permission from your OSM account to sign up.". Repeat.

Mapillary 3.125 on Android 7.0 Nougat 3.18.14-12962328 on Samsung SM-G390F

**Comment by pczaja** [comment] 2018-05-16 20:10
The phone is neither rooted nor is the app installed on SDCard.

**Comment by ovivoda** [comment] 2018-05-17 08:53
@pczaja can you please record the behavior and send it to me. Also please try http://android-releases.mapillary.io/Mapillary_Android_v3.102-SNAPSHOT2.apk and send back the logs.

**Comment by ovivoda** [comment] 2018-07-06 10:13
This issue has been fixed in the latest app version

**Closed by ovivoda** 2018-07-06 10:13 UTC
