### ISSUE TITLE
GoPro Hero 6 issue / Importing Pictures

### ISSUE THREAD

**Issue by thoschu96** [mapillary/mapillary_issues#2808] opened 2017-11-22 09:16 UTC
### Basic information
* Platform: `iOS` 
* Version: `11.1` 
* System/Browser: `...`

### Steps to reproduce behavior

 1. Tab on Uploadbutton of the IOS App
 2. Searching externe Kamera
 3. Asking for Importing Pictures
 4. After Agreed, the Import starts
 5. App crashing/closing down

### Expected behavior

Should start with Downloading new Pictures and starting
with Counting

### Actual behavior

Initial Screen shows up but never started to start counting, instead it's closing/crashing

### Additional information

Would be nice, if you could Choose which Pictures u wanna import.
maybe there are none mapillary realted pictures on it, you don't wanna get imported ...

**Comment by millenbop** [comment] 2017-12-05 19:55
Sorry for the late reply! Unfortunately we don't have access to a GoPro Hero 6 so cannot test ourselves.

When you say closing/crashing, do you mean that the app crashes or just that no images are transferred?

Thanks for reporting!

**Comment by thoschu96** [comment] 2017-12-06 08:46
The App is Closing (so is guess crashing) and after you Restart the App no Pictures are imported.
I can help to Test, just let me know what you need

**Comment by millenbop** [comment] 2017-12-06 09:19
Thank you. Did you format the card before capturing? Do you have other stuff on the memory card, like GoPro movies etc? 

It should be fine to have other files, just trying to figure out what the problem is.

**Comment by thoschu96** [comment] 2017-12-06 09:24
Card got Initial Format before use.
Yes there are regular Pictures, Videos and Capture Sequences on it
Size of the Card is 200 GB and latest Firmware is on the GoPro

**Comment by millenbop** [comment] 2017-12-06 09:38
Do you have another memory card you can use for testing? In that case 1) format the card 2) do a small capture of like 10 images 3) try to transfer

**Comment by thoschu96** [comment] 2017-12-08 07:16
just gave it a try .. same issue..
System Recocnize there is a camer and asking for import.. Initialize the Import and before you see one Picture moving, the App is Closing down

**Comment by millenbop** [comment] 2017-12-08 08:07
Thanks for testing. I'll see if I can dig up a crash report and see anything.

**Comment by millenbop** [comment] 2018-07-05 14:55
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Closed by millenbop** 2018-07-05 14:55 UTC
Labels: affects-ios, bug
