### ISSUE TITLE
Image processing before upload should be done only once 

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#2534] opened 2017-04-17 05:26 UTC
Android app 3.48 on fairphone 2 with Android 5.1 

With the new app version mapillary processes every image before uploading it. 
If there is some upload problem a resume processes every image again. 
The results should be cached somehow.

**Comment by peterneubauer** [comment] 2017-04-19 10:16
Yes agreed, the problem is that the app doesn't know if you did any changes to the files in the meantime, so we are taking the safe route of reeprocessing for now.

**Comment by HolgerJeromin** [comment] 2017-04-19 12:53
First processing one sequence, than uploading it
would help uploading fast. And on abort the unneeded processing would be reduced.

**Comment by jaakkoh** [comment] 2017-04-29 10:28
Especially since there seems to be some more glitches currently  in handling uploading what @HolgerJeromin suggests would be great. I think that it would make sense anyways, though. But with the issues regarding uploading it'd be nice if the order of processing/uploading could be changed to go hand in hand vs. current all processing and then all uploads.

**Comment by peterneubauer** [comment] 2017-05-15 08:29
Now we are processing one image, then starting upload directly, should not be an issue anymore since 3.55, closing

**Closed by peterneubauer** 2017-05-15 08:29 UTC
Labels: affects-android, feature
