### ISSUE TITLE
Add date in Uploads on My Profile

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#833] opened 2015-03-20 17:20 UTC
SUGGESTION:
I would like to see the date of each uplaoded sequence in addition to the location.

**Comment by richlv** [comment] 2015-03-23 07:20
seems to be a duplicate of a slightly older issue #825 ?

**Comment by knikel** [comment] 2015-04-07 12:55
Closing this one, let's continue the discussion in #825.

**Closed by knikel** 2015-04-07 12:55 UTC
