### ISSUE TITLE
Jump to beginning/end of a sequence

### ISSUE THREAD

**Issue by joakimfors** [mapillary/mapillary_issues#869] opened 2015-03-28 10:23 UTC
It would be nice to be able to jump to the beginning or the end of a sequence in the web UI.

**Comment by gyllen** [comment] 2016-07-26 22:16
@angelday I think this is a pretty good idea

**Comment by angelday** [comment] 2016-08-16 09:13
@gyllen @joakimfors let me know what problems are we solving with this

**Comment by kaitu** [comment] 2016-08-16 11:28
I second @joakimfors. Typical use case is when I spot a sequence needing review, and want to quickly jump at the beginning to review all pictures.

**Comment by pbb72** [comment] 2016-08-16 11:47
An easy way to jump to the beginning of a given sequence, is to zoom out until individual dots are no longer displayed for each photo. Then when you click on the sequence, the first image is opened.

**Comment by angelday** [comment] 2016-08-16 13:11
@pbb72 spot on! But this is not by design, AFAIK this is a technical limitation, but you can work around it like that.

**Comment by kaitu** [comment] 2016-08-16 13:13
@pbb72 I suspect this is not so easy, when plenty of sequences overlap in the same area. I would love a button in blur edit mode to jump to first image in sequence.

**Comment by gyllen** [comment] 2016-08-16 22:47
@angelday There is not tech limitation on jumping to the first image in a sequence. We do have that data availble (or at least easily requestable).

**Comment by angelday** [comment] 2016-08-17 04:34
I think jumping to beginning and end of sequences will be part of our "pro" feature set, made note of that. We'll come back to this issue later on.

**Comment by pbb72** [comment] 2016-08-17 07:28
Pro tip, an alternative to jump to the beginning of a sequence as follows:

- Open the photo details window (by clicking on the tree dots).
- Copy the sequence key that is displayed there.
- Open the URL http://www.mapillary.com/map/s/(sequence-key).

**Comment by nickplesha** [comment] 2018-07-27 07:39
The viewer now has a tool for quickly moving through a sequence and it's an easy way to get to the start or end of a sequence quickly. 

Expand the menu next to sequence navigation to access it:
![sequence](https://user-images.githubusercontent.com/3823786/43308177-f4965582-9180-11e8-9e34-92bb2e9a2603.png)

**Closed by nickplesha** 2018-07-27 07:39 UTC
Labels: affects-web-map, feature
