### ISSUE TITLE
forbidden (403) pages

### ISSUE THREAD

**Issue by grinapo** [mapillary/mapillary_issues#1151] opened 2015-07-12 07:40 UTC
I see plenty of 403's around:
GET XHR https://d2munx5tg0hw47.cloudfront.net/tiles/14/9030/5726.mapbox [HTTP/1.1 403 Forbidden 63ms]
https://d2munx5tg0hw47.cloudfront.net/tiles/14/9031/5726.mapbox
...
it says:

HTTP/1.1 403 Forbidden
Content-Type: application/xml
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Max-Age: 3000
Date: Sun, 12 Jul 2015 07:31:55 GMT
Server: AmazonS3
Age: 1
X-Cache: Error from cloudfront
Via: 1.1 a0599354924210c43a9f77e744cf7836.cloudfront.net (CloudFront)
X-Amz-Cf-Id: K0rhXAzsmQFRWw9vw_hZb2ykR27jhFn_QCo7FS4EG4s97WjVJ9Bx6A==

**Comment by gyllen** [comment] 2015-07-13 16:30
@knikel This is our missing tiles for beta viewer right?

**Comment by knikel** [comment] 2015-07-13 16:31
@gyllen yes, missing zoom levels

**Comment by knikel** [comment] 2016-06-01 14:55
Duplicate of #1149

**Closed by knikel** 2016-06-01 14:55 UTC
Labels: web
