### ISSUE TITLE
30+ images stuck in processing queue from a single sequence

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_issues#1971] opened 2016-06-20 20:26 UTC
I've seen occasional pictures getting stuck in the processing queue here and there. A few weeks ago someone manually cleared out a few 10s of stuck ones that had accumulated over the past 6 months or so.

However this past weekend I believe a single sequence generated 35 or 36 permanently stuck pictures in queue. I thought with such a large batch at once it might be a good opportunity to investigate the root cause. There are 2 or 3 individual ones from other sequences as well. Currently the total number stuck in my queue is 38. 

Unfortunately I'm not sure which sequence it was. I uploaded over 15,000 pictures this weekend and obviously haven't gotten around to reviewing them all post-upload.

http://www.mapillary.com/profile/toebee

**Comment by ToeBee** [comment] 2016-06-20 20:28
I guess I should note that I was using the `upload_with_authentication.py` script to upload this weekend. In the past, most of my uploading has been done through the manual upload page in a browser.

**Comment by ybkuang** [comment] 2016-06-20 20:33
Thanks for reporting this and giving the details. We will investigate.

**Comment by HolgerJeromin** [comment] 2016-06-20 20:48
http://www.mapillary.com/profile/zuse has 53 images processing for probably a year or longer

**Comment by gyllen** [comment] 2016-06-22 12:23
In most cases these numbers are actually `artifacts` in our second stage database, so there are really nothing waiting. We are investigating on how these `ghost images` are created though.

**Comment by de-vries** [comment] 2016-06-22 12:29
duplicate of  #1136

**Comment by polarbearing** [comment] 2016-06-22 12:39
My proposal in #1974 would help everybody to keep track of them.

**Comment by ybkuang** [comment] 2018-07-20 00:18
mapillary_issues is no longer an active repository.
This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!

**Closed by ybkuang** 2018-07-20 00:18 UTC
