### ISSUE TITLE
Editing blurring of image clears pending changes

### ISSUE THREAD

**Issue by wiktorn** [mapillary/mapillary_issues#1126] opened 2015-06-29 11:42 UTC
If I do a lot of editing on pictures (like hiding), but do not click "save and review", instead - I click "edit blurring", I lose all the changes on previous pictures, and no warning is raised to the user.

**Comment by de-vries** [comment] 2015-06-29 14:15
Duplicate of #366

Work around: open edit blur in new tab

**Comment by knikel** [comment] 2015-07-30 14:59
@wiktorn, @de-vries As soon as some blurs have been added to a photo, we mark them and display them in the viewer now. We also 'freeze' the photo for further edits until blurs are resolved. Thanks for the feedback!

**Closed by knikel** 2015-07-30 14:59 UTC
Labels: editor, enhancement, new_viewer
