### ISSUE TITLE
version 4.31 dosn't work on Samsung S4

### ISSUE THREAD

**Issue by wegavision** [mapillary/mapillary_issues#1992] opened 2016-07-02 19:25 UTC
The latest version which came automatically makes some problems. The app stops about every 30 min. I can not send a log, because this phone is offline. I can not see any reason, it only says, the app was stopped. Can I send the log later being online?

**Comment by rsahlin** [comment] 2016-07-05 19:04
Hi @wegavision 

I'm sorry to hear that you are experiencing problems with the app.
- Yes you can send the logs when you are online - but there is a risk that the logs are too short (old information is pushed out as new info is logged)
Please send logs as soon as possible, then go into 'Feed' - 'Settings' - and enable 'Save debug logs'

Thanks in advance

Best regards
/Richard

**Comment by wegavision** [comment] 2016-07-05 20:11
My other smartphon Huawei P7light has simular problems. I will change to an other version.

**Comment by jfburke3** [comment] 2016-07-06 17:47
Which version of Android are you running on your S4?

**Comment by wegavision** [comment] 2016-07-06 18:06
5.01

**Comment by rsahlin** [comment] 2016-08-15 09:03
Hi @wegavision 

Could you please test with latest 2.38 release and verify if the problem is still there?
I will close this issue - please reopen if needed.

Best regards
/Richard

**Closed by rsahlin** 2016-08-15 09:03 UTC
Labels: affects-android, bug
