### ISSUE TITLE
Mapillary generates huge files that fill up phone memory quickly

### ISSUE THREAD

**Issue by andrewpmk** [mapillary/mapillary_issues#1943] opened 2016-06-11 21:44 UTC
Using Mapillary 2.20 on Android on a Samsung Galaxy S6, Mapillary is creating 17 MB .jpg files for each image that is being captured. Presumably these files are not being compressed at all. Both the "Take low resolution pictures" and "Take high resolution pictures" settings are disabled. This is causing the phone's memory to fill up extremely quickly making Mapillary essentially unusable. The .jpg files should be compressed as was the case before the Mapillary app was updated.

**Comment by rsahlin** [comment] 2016-06-12 10:34
Hi @andrewpmk and thanks for your report!

We will need to investigate this.
Could you please do the following.
Open the app, enter camera, take 1 photo - then exit camera.
Go into 'Feed' and select 'Send debug logs'

This will give me some data for the problem, thanks!

/Richard

**Comment by rsahlin** [comment] 2016-06-14 07:08
Possible fix in 2.22 - please retest.

**Comment by andrewpmk** [comment] 2016-06-14 14:39
This bug has not been fixed in 2.22. Mapillary is still generating 17MB files.

**Comment by rsahlin** [comment] 2016-06-14 20:20
Hi @andrewpmk 

Could you please follow the above instructions to send debug logs and point me to an uploaded sequence?

What happens if you tick the 'Take low resolution pictures' option?

The application requests JPEG encoded files.

Best regards
/Richard

**Comment by rsahlin** [comment] 2016-06-15 08:25
Thanks - got the logs now!

**Comment by rsahlin** [comment] 2016-06-24 09:24
Hi @andrewpmk 

Please let me know the status of this issue on the latest (2.29) version.

Best regards
/Richard

**Comment by andrewpmk** [comment] 2016-06-27 13:49
2.29 is not available on Google Play. Latest available version is 2.24.

**Comment by polarbearing** [comment] 2016-06-27 14:56
You need to look [here](http://android-releases.mapillary.io/index.html).

**Comment by rsahlin** [comment] 2016-06-27 15:39
Hi @andrewpmk 

Please consider joining the Beta group  - go into 'Feed' and select 'Join Beta Group'
This way you will get automatic updates - otherwise you will have to manually update when we do a release.

Best regards
/Richard

**Comment by rsahlin** [comment] 2016-07-07 21:08
Hi @andrewpmk 

Could you please retest with latest version from Google Play (2.31)?
Closing this issue - if the problem is still there, please reopen.

Thanks
Best regards
/Richard

**Closed by rsahlin** 2016-07-07 21:08 UTC
Labels: android, bug

**Comment by andrewpmk** [comment] 2016-07-30 21:21
This bug still exists in version 2.37. However, it seems to be fixed if I select "Take low resolution pictures" and produces a more reasonable file size, but the picture quality is low. If "Take low resolution" pictures is not enabled Mapillary still generates 17MB files. I can't believe that it makes sense to produce pictures this large by default. JPEG compressed images at fairly high resolution should not take up anything like 17MB. See this photo of a gas station https://www.mapillary.com/app/user/andrewpmk?lat=43.6989636&lng=-79.3861929&z=17&pKey=06LnbLzJwgOyTwYmoCLmEg for an example.
