### ISSUE TITLE
feature request: tune email preferences

### ISSUE THREAD

**Issue by danbjoseph** [mapillary/mapillary_issues#2909] opened 2018-05-14 21:40 UTC
it would be great to be able to select which email types you want instead of the selecting one of three preset groups.

in my case...
i want "comments", "weekly digest", and "account related" 
i don't want "Your Mapillary Activities" (way too many emails about "Your Mapillary images are now published")
but the above isn't possible

**Comment by katrinhumal** [comment] 2018-05-22 12:05
Hi @danbjoseph - thanks for the feature request! I must say that as a Mapillary user, I have the same one ;)

We will probably be reviewing the way we do notifications at some point, but it's not in the foreseeable plans. But in any case, I've taken your suggestion to the team so that this can be considered. Closing the issue since no near-time fix.

**Closed by katrinhumal** 2018-05-22 12:05 UTC

**Comment by danbjoseph** [comment] 2018-06-08 22:03
63 emails in 3 days... with lots and lots more if you go back a little further.
: |
it would be nice if it at least only emailed once a sequence was complete. right now it emails every time even just a few images make their way through the processing pipeline? i guess i can just add a filter rule for "Your Mapillary images are now published"
<img width="1103" alt="screen shot 2018-06-08 at 3 01 22 pm" src="https://user-images.githubusercontent.com/4806884/41182966-e4811aee-6b2c-11e8-8a72-45dd05239c12.png">

**Comment by katrinhumal** [comment] 2018-06-11 07:42
I'm asking @gyllen for help here to explain why this happens. The Mapillary sequence is a mystical concept... 🔮

**Comment by gyllen** [comment] 2018-06-11 15:24
@danbjoseph Yeah this is caused by the behavior of how processing works on Mapillary. Basically lately we have had a hug influx of imagery (this is the main reason).

The reason for you getting so many updates is because we do not treat the sequences as sequences, the nature of the system is that you should be able to stream imagery so every single image is treated as its own entity (this is a great thing actually since we do anticipate that a lot of imagery will start to stream in the future). 

We do a lot of different things when an image hits Mapillary (lots and lots more stuff than other services where you can upload imagery), the main ones are
1. Blurring
2. Semantic Segmentation
3. Structure from Motion
4. Object extraction

Its usually 3. that causes this behavior since areas will be reconstructed in tiles and not in Sequences, this means that some images will finish before others (we are constantly rebuilding the 3D reconstruction of the world).

I think the best we can do is actually to kick up the aggregation time, meaning that we will not send you anything until either
1. 5000 images have completed
or
2. X hours have passed since we have detected that something has processed for you.

I think this will keep the notifications to an acceptable level.

It would be interesting to get your feedback on what you think X should be.

**Comment by danbjoseph** [comment] 2018-06-18 17:07
24 hours?

**Comment by gyllen** [comment] 2018-06-18 17:43
@danbjoseph Yeah thats my thought too actually, let me check this with the team.

**Comment by danbjoseph** [comment] 2018-06-18 17:56
thanks for looking into this.

![screen shot 2018-06-18 at 1 55 22 pm](https://user-images.githubusercontent.com/4806884/41553297-4f6802b2-72ff-11e8-8183-b09946b22980.png)

**Comment by GITNE** [comment] 2018-06-27 18:32
What happened to weekly digests and monthly leaderboards? I have received my last weekly digest on May 31st, 2018.

Also, the last monthly leaderbord has been posted in March 2018. Can we expect this to come back in one way or another (perhaps automated) any time soon?

**Comment by gyllen** [comment] 2018-07-02 06:09
@GITNE Yes they should have been back last week

**Comment by katrinhumal** [comment] 2018-07-02 14:40
@GITNE the weekly digests, that is. The monthly leaderboards are currently no longer published.

**Comment by GITNE** [comment] 2018-07-03 10:47
@gyllen Yep, I got one last week but it did not figure the number of images contributed. :disappointed:

**Comment by GITNE** [comment] 2018-07-04 11:35
@gyllen I would just like to make sure that the contribution numbers are correct in the weekly digest for the last week (June 25th to July 1st) because the one before figured no contributions from me although I have contributed about 2k images that week (June 18th to June 24th). Finally, I have not received my weekly digest yet, hence I am a little bit worried because usually I got it Tuesdays. I will keep informed.

**Comment by katrinhumal** [comment] 2018-07-04 14:31
This week's digest hasn't gone out yet @GITNE - sorry it's more irregular during the summer! We'll try to be more diligent.

**Comment by gyllen** [comment] 2018-07-04 14:31
@knikel FYI!

**Comment by katrinhumal** [comment] 2018-07-05 06:59
Just to be transparent and honest here, it's currently stuck at me not @knikel (that the weekly hasn't gone out yet).
