### ISSUE TITLE
Map zoom and edit

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1382] opened 2015-09-13 20:04 UTC
Something has happened to the map in edit mode. When zooming in to the most zoomed in level the map disappears. That makes it difficult to place the pictures correctly.

**Comment by Andblue** [comment] 2016-04-21 15:52
So there is nice light from the sun once again and time for some Mapillary. Just tried to edit some stuff, but now it doesn't work at all. The map is flipping out. The map zooms out, and somehow jumps to another sequence.

**Comment by gyllen** [comment] 2016-04-21 17:55
Hi @Andblue this issue is our number on priority, as @peterneubauer can explain we are doing a complete rebuild of the editor and the underlaying structure at the moment.

**Comment by peterneubauer** [comment] 2018-08-27 12:27
Closing this for now as the issue is probably not up to date with the web uploader.

**Closed by peterneubauer** 2018-08-27 12:27 UTC
Labels: affects-web, bug
