### ISSUE TITLE
Some of your photos were edited by <wrong name>

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#2433] opened 2017-01-30 07:23 UTC
I got this email:
> Some of your Mapillary photos were edited by @peterneubauer .

[This](https://www.mapillary.com/app/user/de%20vries?lat=20&lng=0&z=1.5&feedItem=user-DigP2j1LaU-4GrIu1-o54g-affected_indirect_object-user-73Q3j-BDvHrsirf6gPYT4w-approved-changeset-image%3A1485506449487) is the changeset in question.

peterneubauer didn't request this edit, micmin1972 did. peterneubauer was the one who approved the edit.

Also the "View on Mapillary" link in the mail doesn't work.

I'll forward the email to hello@mapillary.com

**Comment by peterneubauer** [comment] 2017-02-04 19:58
This should fixed now in the backend. Please report if the issue is not solved for you.

**Closed by peterneubauer** 2017-02-04 19:58 UTC
