### ISSUE TITLE
Editing angle on sequence only partially approved

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#1203] opened 2015-07-30 19:04 UTC
I had applied for angle correction (30 deg left) for a long sequence, and find it now corrected for the first part of the sequence only. Correction stops at ```pdVTq2M8yLWIu1zTQrx70Q``` , from there on the sequence still looks straight. Was the sequence too long so that some overflow happened?

Traced the cs id: 7Ai-DByq5DtNsvWs9Vk1FA , there were 322 angle changes listed, but the sequence is between 400 and 500 images.

**Comment by de-vries** [comment] 2015-07-31 02:59
duplicate of #991

**Comment by gyllen** [comment] 2016-07-21 23:58
Fixed in new editor.

**Closed by gyllen** 2016-07-21 23:58 UTC
Labels: backend, bug
