### ISSUE TITLE
shortcuts for the blur editor

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2269] opened 2016-09-16 18:47 UTC
If you are doing mass blur requests, it is exhausting to click the buttons, which are on different edges on the browser window. Maybe it is possible to provide additional shortcuts for the button: next image, last image, request change, delete all blurs? 
This would accelerate blur editing.

**Comment by gyllen** [comment] 2016-09-19 12:52
Duplicate of #2161

**Closed by gyllen** 2016-09-19 12:52 UTC
