### ISSUE TITLE
Lag for corrected sequences

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#1310] opened 2015-08-23 20:49 UTC
Sequences where I have corrected the placement of pictures aren't being updated on the map? Is it just summer vacation lag or is something else going on?

**Comment by shlublu** [comment] 2015-08-25 09:19
I submitted 36 of them during the last 7 days (either location or orientation) and it looks like none of them was applied yet. Which is not a problem as long as they are not lost: my timeline just says that I submitted a couple of change requests.

**Comment by Andblue** [comment] 2015-09-11 19:11
Any status update to share?

**Comment by peterneubauer** [comment] 2015-09-11 20:28
So, do you have any link to them so we can check? The image positions are updated but not the sequence lines? Got a screenshot in order to see if this is the old blue lines or the new vector tiles?

**Comment by Andblue** [comment] 2015-09-11 20:37
Here are three sequences

http://www.mapillary.com/map/im/dly5s_tQ1w16mJnfM726-w/photo
http://www.mapillary.com/map/im/TdoBHJTgT4aX9jBE9IpGEA/photo
http://www.mapillary.com/map/im/EAdxxzGJwdHRN5Ov6AC5-g/photo

**Comment by gyllen** [comment] 2015-09-23 00:09
We are still lagging in change sets, sorry for the delay

**Comment by Andblue** [comment] 2016-03-26 21:43
Spring is here and its soon time to snap some pictures again. Any chance this thing will get fixed before summer time?

Does it only affect old sequences or will the same thing happen for new sequences?

**Comment by peterneubauer** [comment] 2016-03-27 07:24
Yes, we are working on the first approvals for the old changesets. Once this is working, we won't lag. Expect a couple of weeks until working.

**Comment by nbolten** [comment] 2017-05-11 01:42
This issue is affecting me as well - not sure if it's a regression at this point.

### Description of the issue:

I submitted several sequences directly from the Android app, then immediately fixed the sequences' lat-lons via the web interface. These were quickly approved, but the traces have not updated.

### Examples:

- A sequence with 7 images, edits requested and approved 2 days ago and 1 day ago: https://www.mapillary.com/app/?focus=photo&pKey=fembcqjg4RGGDqYhvrqKbA. After two attempts at editing the sequence, they still appear with the original, inaccurate coordinates. Even after selecting 'edit sequence', the original, inaccurate coordinates, which is why I edited them twice - I thought the initial edit hadn't worked.
- A larger sequence, edits requested and approved 1 day ago: https://www.mapillary.com/app/?focus=photo&pKey=Yrjeac94vSfRKuvPXsbcSQ

### To replicate:
- Upload a sequence (possibly only from the android app)
- Once it's available in the web interface under <your user> -> Uploads, click the sequence's representative image and fix the coordinates, then submit the change.
- Once approved, check the sequence periodically. Its coordinates will not be updated in the main map nor in the 'edit sequence' mode.

### What should happen:
- In a perfect world, the coordinates would update immediately once approved.
- Since a processing delay may be necessary, the sequence should be flagged as 'edits being processed' and inform the user to not submit changes, *or* the new modified coordinates should always be provided in the 'edit sequence' mode.

**Comment by nbolten** [comment] 2017-05-11 03:01
Update: the edited sequences *do* now appear when I enter the sequence editing mode, though they did not a few hours ago.

**Comment by Andblue** [comment] 2017-07-05 17:09
So this just keeps happening. Many edits are simply not being approved. Some edits are approved within minutes, others are just stuck. I don't feel that you are giving any good answers. It feels like you assign edits randomly to people at the office and some people simply have no time to approve edits. It really takes the fun out of it.

Maybe you should add some kind of trust level to users, so that not every edit has to be checked like the user has bad intentions.

**Comment by gyllen** [comment] 2017-07-05 19:17
@Andblue I hear you. Basically we have an algorithm that let some (if you are a trusted user) edits go through directly. While others needs to be approved by our team (thats why you see some edits go through fast and some edits beeing stuck for a while).

What I have been thinking about is upgrading some user to have the power to approve other users edits, what do you think about that idea?

**Comment by Andblue** [comment] 2017-07-06 15:47
@gyllen That could be a solution worth trying. I guess checking blur edits is much easier than other edits, as other edits requires one to understand the context.

I mostly edit my own uploads. But if there are other uploads in the same place or area I sometimes edit those as well. Its easier to edit those as then I know the area. Not sure if that should play a role.

(By the way, how about upping the trust level of andreas.p for other edits :-)

**Comment by gyllen** [comment] 2017-07-07 19:12
@Andblue I think that might be a good first candidate, let me think about how I could do this.

Also another question, do you have many pending edits at the moment?

**Comment by Andblue** [comment] 2017-07-09 22:32
@gyllen Not sure how many edits are pending, but there are a few. I kind of loose track of them in my head when time passes.

This one got approved very fast https://www.mapillary.com/app/user/andreas.p?lat=59.291002710577345&lng=17.9873340655802&z=17&pKey=Xz_VcA4eoJKBG4Qlo_lCfA&focus=map

But this one that was edited earlier is still pending https://www.mapillary.com/app/user/andreas.p?lat=59.291002710568705&lng=17.987334065563175&z=17&pKey=9B44yHqn8rDpYCA7cNHe2w&focus=map

It does make med feel a bit uncomfortable, Mapillary did manage to lose all edits done during a year. So when edits are pending for a long time I always get the feeling that they will be lost.

**Comment by gyllen** [comment] 2017-07-10 18:28
@Andblue I don't think we lost edits actually, but we did implement a much more robust system and moved the old ones to the new system. You should have some stats in your profile on the web that says how many pending edits you have.

It actually looks to me that the second edit also got through. However the tiles are not updated correctly (if you press edit you can see that everything is in the correct position). We are in the process of regenerating all tiles, so this should soon be updated.

Also I want to affirm that nothing is getting lost in the new edit system.

**Comment by peterneubauer** [comment] 2018-08-27 10:28
This should be solved now right? Closing for now.

**Closed by peterneubauer** 2018-08-27 10:28 UTC
Labels: affects-backend, bug
