### ISSUE TITLE
black's faces not blurred

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_issues#2751] opened 2017-10-19 17:37 UTC
You can clearly see here:
https://www.mapillary.com/map/im/zh7KNNHs2E8tO1aNZ3R2eA
that the white male's face is blurred but the black female's face is not.

Have you trained the neural network with only white faces?

see https://www.recode.net/2017/1/18/14304964/data-facial-recognition-trouble-recognizing-black-white-faces-diversity

**Comment by eugensim** [comment] 2017-10-20 09:44
#blackblursmatter  :)))

**Comment by Eric-FR** [comment] 2017-10-20 11:47
+1.

I had the same feeling in Madagascar although I didn't have direct black&white comparison.

https://www.mapillary.com/map/im/QlfX9MTHB_Fq12h1S6tmHg

**Comment by katrinhumal** [comment] 2017-10-20 14:42
Thanks all! We put lots of work into improving the face detection algorithm and train it on as diverse data as possible, ranging from different skin colours to different lighting conditions. Luckily, Mapillary is getting more and more diverse examples to include in the set from very different parts of the world. So we're not only training on white faces, to answer the question directly, and we'll do our best to improve the results that made you think of this issue.

**Comment by Eric-FR** [comment] 2017-10-22 12:00
A funny illustration: the lighter face on billboard is blurred, not darker people in the street.
https://www.mapillary.com/map/im/d8Co0Wadn4PVtTG6HBCXFw

**Comment by GITNE** [comment] 2017-10-23 18:14
Basically a duplicate of #1349.

Unfortunately, there is not much one can do in the short term other than fixing these false negatives manually in the blur editor. In the long run, only manually acquired training data will improve automatic blurring.

@mapillary
Ideally, it would probably be best to have incremental training with every manual blur or tag applied but in reality continuous training cycles should/could suffice.

**Comment by Eric-FR** [comment] 2017-10-26 13:36
That's what I'm doing now: follow sequences, remove all false positives and add blur to faces and ID plates, with the secret hope that, one day, this will be efficiently used as training material for AI learning.

Indeed, when I see the large number of false positives, especially for ID plate, I think there is still a long way. I have the feeling that it is based on pattern detection. When I'm using my NI (Natural Intelligence ? ;-) ), I'm first looking for bodies, then the head on the body and finally the face on the head. Same for ID plate. I'm first looking for vehicles and then trying to locate ID plate at places where they are supposed to be on vehicles. My approach may fail sometime, for instance when body is not fully visible (for instance only face visible inside a car, body cut by the border of picture) but my efficiency is way higher to present Mapillary detection.

I know that the purpose of AI is to avoid silly tasks, not necessary to mimic NI but, for sure, AI learning is better when provided with good hints. I think that the present pattern detection alone is not good method leading to very vague hint.

**Comment by katrinhumal** [comment] 2017-10-27 10:31
@Eric-FR Very good points. A part of the improvements that we're doing to the blur algorithms is exactly what you said - to take the context more into account. So the detections around the detected face or licence plate will help judge if it's correct, before blurring.

**Comment by Alessandro-Barbieri** [comment] 2018-04-15 02:07
I think I can close this now after the recent improvements

**Comment by Eric-FR** [comment] 2018-04-15 16:43
+1. With recent improvements, blurring of black faces in Madagascar improved a lot (ID plates also while false positives disappeared).

**Comment by katrinhumal** [comment] 2018-04-16 08:24
Thanks for the feedback! So happy to hear you consider the results clearly visible - or clearly blurred, should I say ;)

**Closed by katrinhumal** 2018-04-16 08:24 UTC

**Comment by Eric-FR** [comment] 2018-04-16 22:06
https://www.mapillary.com/map/im/NHCFPDpVfkWkX1CbUGY56g
