### ISSUE TITLE
Images "diconnecting" from sequence/track

### ISSUE THREAD

**Issue by ramapongithub** [mapillary/mapillary_issues#2595] opened 2017-06-12 10:41 UTC
### Basic information
* Platform: `Web`
* System/Browser: Windows10 / Chrome

### Steps to reproduce behavior

 1. Go to [https://www.mapillary.com/app/?lat=50.72764711009168&lng=10.945988745111407&z=12.040109096004379&focus=map&menu=false&mapStyle=mapbox_streets](https://www.mapillary.com/app/?lat=50.72764711009168&lng=10.945988745111407&z=12.040109096004379&focus=map&menu=false&mapStyle=mapbox_streets)

### Additional information
I just detected one of my sequences (from 01.01.2017) has a long distance sequence connection over some kilometers.
But i am totally sure there was no problem on the map before.
I checked it an there seem to be a problem. Some pictures "disconnected" from the sequence and are now standalone, like
[https://www.mapillary.com/app/?lat=50.72265833333336&lng=10.833227777777779&z=17&focus=photo&menu=false&mapStyle=mapbox_streets&pKey=mqUs-RT6C4ZoEajflObuwQ](https://www.mapillary.com/app/?lat=50.72265833333336&lng=10.833227777777779&z=17&focus=photo&menu=false&mapStyle=mapbox_streets&pKey=mqUs-RT6C4ZoEajflObuwQ) or
https://www.mapillary.com/app/?lat=50.73437777777781&lng=11.035252777777714&z=20&focus=photo&menu=false&mapStyle=mapbox_streets&pKey=rLVKBguSNbVv5pJ2ckhAYQ

The long distance connection starts here
[https://www.mapillary.com/app/?lat=50.73301666666666&lng=11.035913888888928&z=20&focus=photo&menu=false&mapStyle=mapbox_streets&pKey=ai3zXEGlnc_dhWvKTMG2NQ](https://www.mapillary.com/app/?lat=50.73301666666666&lng=11.035913888888928&z=20&focus=photo&menu=false&mapStyle=mapbox_streets&pKey=ai3zXEGlnc_dhWvKTMG2NQ)

In the same sequence seem to be other, not that noticeable, areas where the images are disconnected from the sequence, like here:
[https://www.mapillary.com/app/?lat=50.72524218653112&lng=11.049132399350412&z=17.569136194373122&focus=map&menu=false&mapStyle=mapbox_streets&pKey=Pkj_73hp8ZOTdP_X8ZQeGw](https://www.mapillary.com/app/?lat=50.72524218653112&lng=11.049132399350412&z=17.569136194373122&focus=map&menu=false&mapStyle=mapbox_streets&pKey=Pkj_73hp8ZOTdP_X8ZQeGw)

The images were uploaded via Python script and sorted manually before. So i am absolutly sure they were not uploaded as single sequences each.

**Comment by gyllen** [comment] 2017-06-13 15:58
@peterneubauer Can you take a look at the data above?

**Comment by ulikoehler** [comment] 2017-07-05 14:30
I think this might be related to my issue in https://github.com/mapillary/mapillary_issues/issues/122 . The single images might be due to the sequence cutter cutting them by distance.

The cause of the issue seems to be mainly that `upload_with_authentication.py` might effectively generate multiple sequences, with images randomly (?) being assigned to one of the sequences.

@ramapongithub If it is the same issue as mine, a preliminary solution is to upload with `upload_with_preprocessing.py` instead of `upload_with_authentication.py`.

**Comment by ramapongithub** [comment] 2017-07-05 15:27
@ulikoehler  I am not sure this is related. I do the "preprocessing" manually, put the images in folders and run `upload_with_preprocessing.py` by script for each folder. And i am a little lost in time: my version of `upload_with_preprocessing.py` is from around September 2015.
But normally it works fine.
In this special case it looks more like a glitch in the database or the database-script communication at the time of upload. I have not seen this in any other case since then.

**Comment by peterneubauer** [comment] 2018-08-29 10:30
I'm closing this for now. The python tools should be more stable now, and the disconnected image is due to the sequence cutter - let us know in the forum if anything pops up again.

**Closed by peterneubauer** 2018-08-29 10:30 UTC
