### ISSUE TITLE
be able to connect Mapillary & OpenStreetMap POIs

### ISSUE THREAD

**Issue by JLZIMMERMANN** [mapillary/mapillary_issues#1373] opened 2015-09-09 10:01 UTC
Something would be great : do something like the bluring request but to 
- give ability to locate on the picture one POI of OpenStreetMap and,
- by this way be sure to give the good direction for the picture and also,
- would improve the photo location.

**Comment by HolgerJeromin** [comment] 2015-09-09 11:37
The problem is, that in osm there is no concept of a stable id.
Often we have a poi point (called nodes) in osm and they are converted later to an area (called way) which will have another id.

So we have nothing sane to store in mapillary.

**Comment by gregorywilliams** [comment] 2015-09-09 19:12
I know that it's still not completely stable (and wouldn't solve the node -> way issue), but couldn't the node / way ID together with it's revision be used? Rather than requiring users to know the current revision of the OSM object that they're referring to it could look it up via the OSM API. Better still would be an interactive selection of the OSM object via clicking on a map or map & list of possible matches to the click.

If these could be exposed via an API or in bulk form then others could determine whether an OSM object that's pointed to has since been deleted or looks like it's been substantively changed (e.g. position / geometry changed by more than just a small amount or where existing tags have changed value since the version that was linked to). Perhaps the changeset could even be linked to, which might make it easier to see, for example, that a node -> way upgrade has been performed.

Gregory


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 09-Sep-2015 12:37:55, Holger Jeromin <notifications@github.com> wrote:
The problem is, that in osm there is no concept of a stable id.
Often we have a poi point (called nodes) in osm and they are converted later to an area (called way) which will have another id.
So we have nothing sane to store in mapillary.

**Comment by HolgerJeromin** [comment] 2015-09-09 22:32
Id with version is a nice idea. 
I think the real value would be to detect if the link was broken. I don't think the automatic tracking of the new version would work. 

Even this has a problem:
A movement is only done via changing the nodes. The way and version is not changed.

**Comment by PeterMead** [comment] 2015-09-11 09:38
Another option would be to link Mapillary to Wikidata.  There is already an effort under-way to link OpenStreetMap to WikiData.  Things could be linked from Mapillary to OpenStreetMap via WikiData .

**Comment by HolgerJeromin** [comment] 2015-09-11 11:41
That would be a very good idea. The Q42 ids are far more stable and WD could be used for nice other stuff.

**Comment by Virtakuono** [comment] 2015-09-24 08:52
I think Peter has a point there. Wikidata is a quite good place to link to, because the reference is highly unlikely to go bad with time.

Also, instead of what Gregory and Holger propose, I would question why to link into OSM at all. With the wikidata tagging, the solution has been rather simple. Since OSM nodes, ways and whatnot keep changing, it is easier to tag OSM objects (that are dynamic) to refer to the wikidata items (that are static). I see no good reason for the reference to be two-sided.

I think it would be enough to be able to link to a particular area of a particular image in mapillary as an URL, then add that URL with an appropriate tag to the appropriate object in the OSM database. This would allow OSM database users to find the mapillary image of the object of their interest. If one would want  to do the opposite and to find an OSM object that refers to a particular area of a particular photo in mapillary, one could do a simple database query and find the OSM object (or objects) that refer to a particular url.

**Comment by PolyglotOpenstreetmap** [comment] 2016-06-07 07:58
Has any progress been made in this direction? Is it possible to mark a part of a picture and refer to the corresponding item on Wikidata?

**Comment by peterneubauer** [comment] 2016-06-07 09:44
So,
there is an upload form integration started that @lokal-profil did, referred to here: https://github.com/peterneubauer/wlm-maps/blob/master/wlm-maps.js#L142 I want to get this going with MApillaryJS (you can then point out POIs in Wikipedia on Mapillary, and submit the image and ID to wikidata). If you want, feel free to do something along these lines?

**Comment by peterneubauer** [comment] 2018-08-27 10:02
Via tags you can mark pictures now, this is what a lot of OSM contributors is doing, so I'm closing this.

**Closed by peterneubauer** 2018-08-27 10:02 UTC
Labels: feature
