### ISSUE TITLE
Images rotated sideways when taken using the app

### ISSUE THREAD

**Issue by simonmikkelsen** [mapillary/mapillary_issues#1972] opened 2016-06-21 10:41 UTC
In http://forum.mapillary.com/t/does-mapillary-team-use-the-blur-requests-for-training/545 several users tells, that they have experienced whole sequences taken with the Mapillary app, to be rotated sideways.

https://www.mapillary.com/map/im/sgmgEBOzKs6r31grrj0W2g/photo is an example and I too had the issue for a few images recently: https://www.mapillary.com/map/im/D0uXE0LWJ86PagVEitOYaA/photo

In my case I made several small sequences within a short period of time, and this one was the only one with problems.

**Comment by Caboosey** [comment] 2016-06-21 14:04
This is a duplicate of issue #1925

**Comment by rsahlin** [comment] 2016-06-22 08:16
Thanks @Caboosey for pointing out the duplicate

@simonmikkelsen I'll close this issue, please add additional information such as logs to #1925 

/Richard

**Closed by rsahlin** 2016-06-22 08:16 UTC
