### ISSUE TITLE
Web : no stat for France

### ISSUE THREAD

**Issue by mgageo** [mapillary/mapillary_issues#1120] opened 2015-06-26 12:17 UTC
On the http://www.mapillary.com/map/places/france , the number of images stays to 0
Toplist for France
0 images

**Comment by de-vries** [comment] 2015-06-26 13:49
duplicate of #1098

**Comment by gyllen** [comment] 2015-06-26 14:10
Closing since duplicate see comment in #1098

**Closed by gyllen** 2015-06-26 14:10 UTC
