### ISSUE TITLE
App should take first picture in automatic modes even when speed=0

### ISSUE THREAD

**Issue by polarbearing** [mapillary/mapillary_issues#775] opened 2015-03-03 21:12 UTC
Shooting only when speed > 0 prevents taking duplicates of the same frame. However that reason is not valid for the first picture. 

For practical reasons, when I start a new sequence waiting at a traffic light, the first picture can be taken already.

This also solves #769 for automatic shooting.

**Comment by jesolem** [comment] 2015-03-03 22:18
Actually, this is the expected behavior. We wanted it this way ;)

**Comment by HolgerJeromin** [comment] 2015-05-13 07:22
Can you explain the reasons? 
This way you loose the first meters of every sequence, till the device is at speed.

**Comment by peterneubauer** [comment] 2015-05-13 07:25
Thinking about it, it seems reasonable to take one picture, then wait for the automatic to kick in. Reopening.

**Comment by HolgerJeromin** [comment] 2015-05-13 07:33
Thanks. Did you forgot to reopen? :-)

**Comment by ovivoda** [comment] 2018-07-09 11:19
This issue should be fixed in the latest app version

**Closed by ovivoda** 2018-07-09 11:19 UTC
Labels: affects-android, feature
