### ISSUE TITLE
Focus option not working on Galaxy S5

### ISSUE THREAD

**Issue by nighto** [mapillary/mapillary_issues#1828] opened 2016-04-26 22:00 UTC
Last week I went on a car trip to the beach and shoot ~5k photos driving and walking. On the driving mode, however, approximately one third of the photos got blurry (unfocused), even though the option to always use infinite focus was activated. This leads me to think that the setting is being ignored by the app on my device.

**Comment by ToeBee** [comment] 2016-04-27 13:57
Possibly a duplicate of #1039. However I will say that I've seen some things around the internet about the infinity focus setting just being broken on some Samsung devices so this may not be Mapillary's fault. I typically have to delete 15-20% of the pictures I take with my GS5 due to blurriness.

**Comment by rsahlin** [comment] 2016-04-28 07:56
Hi and thanks for your reports

We have just release version 2.0 to the Beta group, if you have upgraded to Android 5+ the device will use Camera2 interface.
I have changed the way focus configuration works - the app will now only list the focus modes that are supported.
There is no infinity setting as such, there is only different autofocus modes - one mode being OFF.
If OFF is selected I try to set focus distance to infinity but this may not be possible on all devices - currently the app will silently fail but feedback will be improved in future releases.

Also please try the 'Continuous focus for pictures' option.

Could you please try with version 2.0 - and let us know your thoughts?
-Please consider joining the Beta group if you have not already.

Thanks for your feedback and support!

**Closed by rsahlin** 2016-04-28 07:56 UTC
Labels: android

**Comment by ToeBee** [comment] 2016-04-28 22:30
I signed up for the beta and did two sequences over lunch on my GS5. This looks like a huge improvement! The first sequence was done in "Fixed focus, at unknown distance" mode:
http://www.mapillary.com/map/im/P4mXoOdL8xmZofDvKCzgmw/photo

This sequence had two slightly blurry pictures:
http://www.mapillary.com/map/im/pXCXETRJ-lgZnIS-x5xLkg/photo
http://www.mapillary.com/map/im/KnZXnq88wJHf6w-UHEs83w/photo
But they were still **much** better than what I was getting before on those 10-15% of out of focus pictures.

The second one was done in "Continuous focus for pictures" mode:
http://www.mapillary.com/map/im/unltZT5CcT0-74NCNYGstw/photo
I was unable to spot any blurry pictures in this one at all.

These aren't very long sequences. I'll see if I can get a few more tonight.

**Comment by rsahlin** [comment] 2016-04-30 09:46
Hi @ToeBee and thank you very much for your report!

Great to hear that you can see improvement in picture quality.
Please let us know what your findings are after continued use and help us improve the app :-)

Best regards
/Richard
