### ISSUE TITLE
uneditable sequence

### ISSUE THREAD

**Issue by voschix** [mapillary/mapillary_issues#2555] opened 2017-05-02 14:09 UTC
I managed to create an uneditable sequence. I need to move some photos to a different position, but the sequnce editor does not pen for this specific sequence

### Basic information
* Platform:  `Web`
* Version: current
* System/Browser: Windows 10, Firefox and Chrome

### Steps to reproduce behaviour
 1. open this photo:
https://www.mapillary.com/app/?lat=45.36577754026371&lng=11.762061181469676&z=18&mapStyle=mapbox_streets&pKey=hBAEgKZZmv-J3yBMHYUc9Q&focus=map
 
You see that the sequence is broken in two parts. The first part consists of photos with incorrect positions. I would like to open the sequence editor to move the photos to their correct positions.

2. click the three-dot icon and click "Edit current sequence" in the "Photo Details" pop-up window

### Actual behaviour
Nothing happens

### Expected behaviour
The black sequence editor pop up window should open (where, amongst other things, I could manually move individual photos)

**Comment by katrinhumal** [comment] 2017-05-02 19:11
Thanks for reporting! We've just heard the same from a couple of other people, so have an internal issue for looking into it. I'll add your example and will get back with an update when I get any information.

**Comment by ulikoehler** [comment] 2017-05-04 17:26
Yesterday I was investigating the same issue (it seems to appear consistently for very long sequences, 500+ imgs).
I found out that it was related to an API gateway timeout, but I couldn't reproduce the gateway timeout today.

Here's another link for you to reproduce:
https://www.mapillary.com/app/index/umap?lat=48.13932108216946&lng=11.64880622162326&z=17&pKey=0nyXnMR1UApZZFIjsq_QrA&focus=map

**Comment by ulikoehler** [comment] 2017-05-04 17:28
My Javascript console consistently shows `Unable to get response from server, please try again.`. I will investigate the network requests further and let you know when I find out anything. Said error message does *not* appear when I try to do the same for a shorter sequence (in that case, the edit panel shows)

**Comment by ulikoehler** [comment] 2017-05-04 17:44
Sorry for comment-spamming on this.

One strange HTTP request I found was for this sequence:

https://www.mapillary.com/app/index/umap?lat=48.127157093938195&lng=11.710192105486925&z=17&pKey=3GGnbH2miiYVUh_CJ4FlyA&focus=map

In chrome I found out that this URL was requested: https://d25uarhxywzl1j.cloudfront.net/v0.1/14/8725/5686.mvt
which returned this error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>DB3CB376DD756770</RequestId><HostId>noUwQDCVCjsk4bEF62sUrasybq7z/ZXlg0DqHQoLUtGYcVqlAAWZZGXrOHwsfyb3FmmR4Go4c+k=</HostId></Error>
```

I found this out by using the chrome inspector Network tab. The request occurs only *after clicking on "Edit current sequence"* and fails after *~466ms* for me.


For another sequence in a totally different area, 
https://www.mapillary.com/app/index/umap?lat=48.05244812226513&lng=11.050987803695108&z=17.323735133098275&pKey=aVGBNOzAhroCHjSy5F_eKw&focus=map

The equivalent request https://d25uarhxywzl1j.cloudfront.net/v0.1/14/8694/5691.mvt fails the same way.

For a *working* (i.e. shorter) sequence, the equivalent request https://d25uarhxywzl1j.cloudfront.net/v0.1/14/8726/5688.mvt works fine

Note that the error might also be related to "long sequences of high-resolution pictures", not "long sequences for any picture".

**Comment by ulikoehler** [comment] 2017-05-04 18:00
The same issue (with URLs like) https://d25uarhxywzl1j.cloudfront.net/v0.1/14/8725/5686.mvt also occurs if I use the *ESRI streets* map view. I was thinking it was mapbox-related becuase *.mvt* might mean mapbox vector tile.

**Comment by ulikoehler** [comment] 2017-05-04 18:10
There's also an "Error: forbidden" error message, possibly related to the 403 response code from the cloudfront URLs:

Here's a full error log exported from chrome inspector: https://pastebin.com/7XqxAvdu

**Comment by ulikoehler** [comment] 2017-05-04 18:23
I can create requests to URLs like https://d25uarhxywzl1j.cloudfront.net/v0.1/14/8725/5686.mvt

So here's my take on the source of the issue:
1. Long sequences typically cover a rather large area, as opposed to shorter sequences
2. Mapillary tries to load the entire area covered from Cloudfront as MVT (mapbox vector tile?)
3. However, it does not load it with the appropriate zoom level, therefore the mapbox tile request is rejected and the JS code is getting screwed up.

The zoom level from the URLs is always 14 (first number after `v0.1`). This seems to be a rather fine-grained zoom level (I only know from memory from OSM, so please check if this is actually the case). When I zoom out on the map, the zoom level decreases in the MVTs being requested.

**Comment by ulikoehler** [comment] 2017-05-07 13:53
I've re-checked today and it seems I'm now able to edit those sequences. @voschix Can you confirm this?

**Comment by katrinhumal** [comment] 2017-05-08 13:03
@ulikoehler you beat me to it! We've pushed a fix for this issue, so I hope you won't be experiencing that anymore. Great if @voschix can confirm, too.

**Comment by voschix** [comment] 2017-05-08 13:52
OK here as well

**Comment by katrinhumal** [comment] 2017-05-09 06:48
Thanks for checking! Happy to close this.

**Closed by katrinhumal** 2017-05-09 06:48 UTC
