### ISSUE TITLE
Traffic signal warning sign detected instead of a bump warning

### ISSUE THREAD

**Issue by stefanb** [mapillary/mapillary_issues#573] opened 2015-01-31 19:32 UTC
Instead of a european "bump warning" traffic sign mapillary detects "traffic signal ahead warning" sign.

See:
https://www.mapillary.com/map/im/8x7Ea_VQyxpjby85HjLLMQ

**Comment by ybkuang** [comment] 2015-02-01 06:34
@stefanb Thank you for pointing this out. We will re-train the detection algorithms in the next iteration and also will add a feedback system to tag/remove false signs.

**Comment by floscher** [comment] 2015-02-04 19:24
Duplicate of #568.

**Comment by gyllen** [comment] 2015-02-05 03:27
@stefanb We are "snesk" releasing feature. Feedback should now be possible. Try it out and give us feedback.

**Closed by gyllen** 2015-02-05 03:27 UTC
