### ISSUE TITLE
Spinner on Help Us Detect Traffic Signs

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#672] opened 2015-02-19 12:34 UTC
@korst in https://github.com/mapillary/mapillary_issues/issues/568#issuecomment-74046011
> Gets stuck on spinner After pressing save or approve, it sometimes fails to load new image.

@eMerzh in https://github.com/mapillary/mapillary_issues/issues/568#issuecomment-74408892
> Like korst i got a lot of "stuck on spinner" ... often (but not only) with images still processing message.

I confirm. A lot of spinners when theses messages are displayed:
* *"This image hasn’t finished processing yet! It will look better soon, promise."*
* *"Location not Found by"*

![spinner for images still processed](https://cloud.githubusercontent.com/assets/2158081/6266608/fb6adaf8-b83b-11e4-9a68-e41f0615dc22.png)

**Comment by floscher** [comment] 2015-02-19 12:52
See #670.

**Comment by gyllen** [comment] 2015-02-19 17:52
Duplicate of #670

**Closed by gyllen** 2015-02-19 17:52 UTC
