### ISSUE TITLE
Recent Activity - wrong day

### ISSUE THREAD

**Issue by canadarunner** [mapillary/mapillary_issues#1632] opened 2015-12-21 19:59 UTC
Hi, today I uploaded some images with the python-script.
Now on my profile shows that I uploaded yesterday (20.), but the upload and the capture of the images happened today (21.)

**Comment by ToeBee** [comment] 2016-01-09 07:00
This is a duplicate of #634 (and #900 too)

**Comment by gyllen** [comment] 2016-04-11 00:54
Closing since duplicate

**Closed by gyllen** 2016-04-11 00:54 UTC
