### ISSUE TITLE
When you are sign in button 'Create account' is still there

### ISSUE THREAD

**Issue by kRkk** [mapillary/mapillary_issues#2739] opened 2017-10-15 09:54 UTC
### Basic information
* Platform: `Web`
* System/Browser: `Ubuntu 17.04 | Firefox 56`

### Steps to reproduce behavior

 1. Go to [mapillary.com](https://www.mapillary.com/)
 1. Log in or Sign in

### Screenshot
![screnshot](https://user-images.githubusercontent.com/16520278/31583638-7e82dc74-b19f-11e7-8c96-527ca925c8ef.png)

**Comment by katrinhumal** [comment] 2017-10-16 10:08
Thanks for reporting! I think we've just missed that one. Will pass it on to the developers.

**Comment by nicolas17** [comment] 2018-02-05 02:53
Duplicate of #2581?

**Comment by katrinhumal** [comment] 2018-07-09 19:20
This has been noted down internally to be handled at some point. Since it's not a blocker from using Mapillary, closing the issue here.

**Closed by katrinhumal** 2018-07-09 19:20 UTC
