### ISSUE TITLE
New viewer: Spanning directions of blurring rectangle

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1291] opened 2015-08-13 05:17 UTC
In the new viewer it's only possible to draw/span blurring rectangles from the top left to the bottom right. If one tries to use other directions, the created rectangle is not visible. I'm not sure if in these cases the rectangle is created correctly, however the symbol to remove the rectangle (X) is always shown.

**Comment by richlv** [comment] 2015-11-14 17:21
this is a duplicate of issue #1222

**Comment by knikel** [comment] 2015-11-20 15:59
Fixed too!

**Closed by knikel** 2015-11-20 15:59 UTC
Labels: bug, web
