### ISSUE TITLE
sequence editor renders the wrong (old) image position

### ISSUE THREAD

**Issue by jotpe** [mapillary/mapillary_issues#2273] opened 2016-09-19 20:37 UTC
I catched this error before, but now if done a screenshot.
I edited image locations within a sequence. 
Normal behaviour: Hovering an image position (blue circle) shows a black hand with forefinger pointer, default is an open white hand pointer.

![bildschirmfoto vom 2016-09-19 22 36 12](https://cloud.githubusercontent.com/assets/3539168/18648140/9ad58fa8-7eb9-11e6-954f-d69103cdc3c1.png)
![bildschirmfoto vom 2016-09-19 22 36 17](https://cloud.githubusercontent.com/assets/3539168/18648139/9ad230f6-7eb9-11e6-8741-dc854f8fe33e.png)

After the magic image move: The blue circle stays at its position, but the pointer hover effect and the changed lat/lon tells me it was moved where I dropped it. And I can still move the invisible image location, I can see lat/lon changing.

![bildschirmfoto vom 2016-09-19 22 18 24](https://cloud.githubusercontent.com/assets/3539168/18648083/5139cdb4-7eb9-11e6-83e6-88d7ee6238be.png)
![bildschirmfoto vom 2016-09-19 22 18 55](https://cloud.githubusercontent.com/assets/3539168/18648084/5144a504-7eb9-11e6-8c51-5e6a25c9610e.png)

Chromium Version 53.0.2785.113 Built on 8.5, running on Debian 8.6 (64-bit)

**Comment by gyllen** [comment] 2016-09-20 09:21
@jotpe Thanks for reporting

**Comment by nickplesha** [comment] 2016-10-21 13:45
@jotpe We update `mapbox-gl` to the latest version and updated our map-handling code as well. We can't reproduce this error, can you please check if it still occurs for you?

**Comment by katrinhumal** [comment] 2017-03-29 08:56
@jotpe I'm closing this for now, please get back to us if you still experience trouble.

**Closed by katrinhumal** 2017-03-29 08:56 UTC
Labels: affects-web-uploader, bug, info-tracked
