### ISSUE TITLE
Recent activity on user profile is 1 day out.

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#900] opened 2015-04-05 10:36 UTC
I'm finding the recent activity is often 1 day out. For example is say I uploaded 0 on April 4th, and 2695 on April 3rd. Yet, I uploaded 2695 on the 4th and 617 on the 3rd (which is thinks I uploaded on the 2nd.

**Comment by jesolem** [comment] 2015-04-08 21:30
Could be a time zone issue? @gyllen ?

**Comment by de-vries** [comment] 2015-04-08 22:28
duplicate of #634

**Comment by gyllen** [comment] 2015-04-10 16:39
I thinks its a web client issues.

**Comment by knikel** [comment] 2016-06-01 09:19
Closing in favour of #1632

**Comment by knikel** [comment] 2016-06-01 09:21
This widget needs a complete rework. Won't be part of the upcoming mapillary.com update, but we'll add it after the initial release in a better form. Closing.

**Closed by knikel** 2016-06-01 09:21 UTC
Labels: web
