### ISSUE TITLE
"We failed to log you in"

### ISSUE THREAD

**Issue by shlublu** [mapillary/mapillary_issues#1389] opened 2015-09-15 08:34 UTC
I'm trying to log in Mapillary but the system keeps saying "We failed to log you in". 
My credentials are stored in my browser so I'm sure it is not a typo.

**Comment by gyllen** [comment] 2015-09-16 03:04
@shlublu Our systems do not report any errors, have you managed to login yet?

**Comment by shlublu** [comment] 2015-09-16 06:28
Yes, I retried a few hours later, and I could log in normally.
Strange.

**Comment by gyllen** [comment] 2015-09-19 00:55
Strange, will not investigate further since no other reports of this, reopen if it happens again, in the meantime closing

**Closed by gyllen** 2015-09-19 00:55 UTC

**Comment by shlublu** [comment] 2015-09-19 05:38
Makes sense. I didn't happen again so far.

**Comment by JeopardyTempest** [comment] 2016-04-02 01:54
Not sure if it's best to mention here, or to open a new thread, but I have had the same issue persistently.

I signed up in the Android app, and it has worked.  But have never been able to login on PC... IE or Firefox.  I've changed the password by email successfully (a few times), and was able to relogin on the Android afterwards with the new password... but still cannot bring about any success on PC.  Been trying for about a week, since I first downloaded Mapillary, day or night, no success.  Odd?

**Comment by gyllen** [comment] 2016-04-11 00:44
@JeopardyTempest Can you open a new issue since this is probably not the same one. Also can you login now?

**Comment by JeopardyTempest** [comment] 2016-04-11 07:49
Did finally see the reason why I couldn't login, but went ahead and added a report because of the causes.  #1805 

Thanks

**Comment by gyllen** [comment] 2016-04-11 14:54
Awesome thanks, we will look into it
