### ISSUE TITLE
Timestamp on images on the website is wrong

### ISSUE THREAD

**Issue by jfburke3** [mapillary/mapillary_issues#2540] opened 2017-04-19 21:59 UTC
I noticed a little while back that the timestamp on my images is no longer correct.  (It used to be, but no more.)

I kept forgetting about it until now.  This sequence, for example, is showing a time that is 4 hours before I actually shot the images:
https://www.mapillary.com/map/im/EnR9R5HeqwiYmxJQQA-AAg

And the same seems to be true for the rest.

**Comment by katrinhumal** [comment] 2017-04-21 13:27
@jfburke3 This is interesting. We haven't changed anything in a long while, so what should apply is this:
- if the photos are captured from our apps, it will be UTC (there was some Android app version that recorded local time but that got fixed long ago)
- if the photos are from action cameras/360, it can be anything depending on users’ setting (UTC, local time or random time zone)

What have you been capturing with for those sequences, in particular the one that you shared the link of?

**Comment by jfburke3** [comment] 2017-04-22 12:30
I'm just using your app. 

From what you just said, it sounds like one possibility is that the app is using my phone's time, which is US Eastern time, but the website assumes that it's UTC and subtracts from the image timestamp to adjust the displayed time?

**Comment by peterneubauer** [comment] 2017-04-24 07:56
From discussing this with @ybkuang I think it's like you say @jfburke3 . The problem is that in EXIF, there is no concept of time zone, and there is no standard for what to write into the date fields- UTC od Localtime. The different vendors to different things.

Before, we were writing the phones timestamp after capture into the JSON, not connected to the EXIF. Now, we are trying to be concistent with the coming support of external cams were we only have EXIF to work with.

This is a problem that does not seem to be solvable without a helper method to find out what is in the EXIF.

For the internal CAMs, I will look into checking at image-capture time how the camera is writing the date tags by readding the EXIF time of the first captured image, and the phone time, and saving that difference either in the EXIF or GPX track for use at processing time later before upload. We might be able to do something like that with external cams too if we can take a test picture. Otherwise, I think the user needs to point out the time difference in a calibration step per camera.

Stay tuned for fixing this!

**Comment by GITNE** [comment] 2017-04-24 11:56
> For the internal CAMs, I will look into checking at image-capture time how the camera is writing the date tags by readding the EXIF time of the first captured image, and the phone time, and saving that difference either in the EXIF or GPX track for use at processing time later before upload. We might be able to do something like that with external cams too if we can take a test picture. Otherwise, I think the user needs to point out the time difference in a calibration step per camera.

I do not think this overly complicated path is actually necessary because you can always compute UTC or just get it by calling a system method on the phone locally, that is provided the user has set up the internal clock and time zone (including daylight saving) properly. Of course, you cannot be absolutely sure that the user has done that correctly but you have to start somewhere. Then you can check for the existence and value of the `GPSTimeStamp` EXIF field (which indeed **is** **not** time zone agnostic). If it does not exist just write your computed or system provided UTC value before upload, if it does exist then assume the camera has pulled its value from the GPS signal which should be, in any event, *more* correct than any computed value.

**Comment by GITNE** [comment] 2017-04-24 13:40
> @GITNE so what should the tag look like? there is http://www.exiv2.org/tags-xmp-exif.html but no real example of how to write and combine GPSTimeStamp and GPSDate.

I am not exactly sure what you are trying to say. You cannot *combine* the `GPSTimeStamp` and `GPSDateStamp` EXIF fields in the EXIF header because by specification they are two distinct fields. However, they *are* sort of combined in XMP because they are encoded as an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date time stamp of the form *`YYYY`*`-`*`MM`*`-`*`DD`*`T`*`HH`*`:`*`mm`*`:`*`SS`*`.`*`F`*`Z` and are written as a value of the `exif:GPSTimeStamp xmlns:exif="http://ns.adobe.com/exif/1.0/"` attribute (or in the body of the `exif:GPSTimeStamp xmlns:exif="http://ns.adobe.com/exif/1.0/"` element).

Please also note the comment of the `exif:GPSTimeStamp` XMP field in the table about what to do if the `GPSDateStamp` field is unavailable in case you want to compute it. :wink:

> For now, we will assume that the EXIF timestamps are in local time

Unfortunately, yes, this is actually the only way you can (or even should) interpret time zone agnostic time stamps.

> Also, the GPSTimeStamp is not written by all cameras, but we could try to write it ourselves later.

True, this is why I have hinted at checking the `GPSTimeStamp`'s (and `GPSDateStamp`) existence and its value.

**Comment by peterneubauer** [comment] 2017-04-24 13:43
Yes, I'm trying to say I'm not sure about the format since there seems to be competing  versions (fractions vs Long), see http://stackoverflow.com/questions/4879435/android-put-gpstimestamp-into-jpg-exif-tags

**Comment by GITNE** [comment] 2017-04-24 13:57
Well, Android's API documentation says:
```
Type is String. Format is "hh:mm:ss".
```

But, it would not be the first time for API documentation to be incorrect. :unamused: Try passing strings of rationals, like `"12/1:34/1:56/1"`, `"12/1:34/1:56/789"`, or as one answer on Stackoverflow suggests delimited by commas `"12/1,34/1,56/1"`.

**Comment by peterneubauer** [comment] 2017-04-25 08:13
With 3.51, is this now working better?

**Comment by peterneubauer** [comment] 2017-04-25 11:55
closing this for now as it should be fixed. We will change the filename of the images from localtime to UTC and start using is as the first check, before even looking into EXIF - which will work good for images taken with the apps and supports milliseconds, too.

**Closed by peterneubauer** 2017-04-25 11:55 UTC
Labels: affects-android, bug
