### ISSUE TITLE
Disable Mac Auto-correct in Location Search on Website

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#2354] opened 2016-11-08 15:01 UTC
### Basic information
* Platform: `Web`
* System/Browser: `macOS 10.12.1 / Safari 10.0 `

![image](https://cloud.githubusercontent.com/assets/1827881/20103948/f0a93022-a599-11e6-9cad-0688e3267a71.png)
 ![image](https://cloud.githubusercontent.com/assets/1827881/20103918/d29a5854-a599-11e6-99d9-382b8c3aa9f0.png)

### Steps to reproduce behavior

 1. Search for `Owings Mills` in the Mapillary location search
 2. Note that Mac autocorrects to `Wings ...` before you finish typing

### Expected behavior

Location search box does not autocorrect, as locations are often not in the English dictionary

### Actual behavior

Query is auto-corrected.

### Additional information

![screen shot 2016-11-07 at 5 13 34 pm](https://cloud.githubusercontent.com/assets/1827881/20103794/68fbeb92-a599-11e6-8ef9-53e80702e43c.png)

**It seems like [this](http://stackoverflow.com/a/35514029/2105596) would fix it.**

**Comment by GITNE** [comment] 2016-11-08 17:19
Yeah, I was just about to comment on this that it is not a web page thing but a browser specific thing.
@talllguy You can set this either in your browser or system settings. So, there you go! :wink:

**Comment by talllguy** [comment] 2016-11-08 18:09
@GITNE I'd like to keep it turned on though, on my system and browser. This _is_ web page specific, because the location field in any website isn't one you'd typically want autocorrect to work on.

**Comment by GITNE** [comment] 2016-11-08 19:49
> This is web page specific, because the location field in any website isn't one you'd typically want autocorrect to work on.

I have to disappoint you @talllguy. This **IS** **NOT** a web page thing. Web pages (should) adhere to standards. And, Mapillary's web site does to a large degree. The attributes `autocorrect`, `autocapitalize`, and `spellcheck` you are referring to via the stackoverflow article talks about non-standard attributes. These attributes are **only** honored by **Safari**. They may have been proposed by Apple for the [HTML5 standard](https://www.w3.org/TR/html5) but so far they have not made it into the standard. Besides, HTML5 is not a standard yet. It is a W3C recommendation only. Semantically, the closest attribute to your spellchecker‑thingy is the [`autocomplete`](https://www.w3.org/TR/html5/forms.html#attr-fe-autocomplete) attribute. But, even though this attribute has been recommended by the W3C the Safari web browser may still not support it or even if it does, may exhibit semantically different behavior than intended by the W3C. In other words, it may not target your spellchecker‑thingy.

Please, do not try to argue with or outsmart people who know their craft. In this context, I would like to advise you to pay attention to initial premises because this is exactly what you have overlooked. This is always a good thing to do, not only with regards to web pages. So, please pay attention to initial premises.

> I'd like to keep it turned on though, on my system and browser.

Then this is *your* *personal* choice and the observed behavior of your Safari web browser is a consequence of that. It is not a bug on the web page nor unexpected behavior. However, you may suggest to support this feature on Safari browsers.

**Comment by talllguy** [comment] 2016-11-08 20:20
Thanks for the enlightening op-ed on web standards. /s

> Please, do not try to argue with or outsmart people who know their craft. [...]

Seriously? 🙄 _Please_ don't lecture me, here especially. As a [Mapillary ambassador](http://blog.mapillary.com/update/2016/08/11/mapillary-ambassador-elliott.html), I strive to be loyal to the community and promoter of friendly collaboration on this platform. **This comment is not helpful**. My opinion in the original comment was implied. You're welcome to disagree, citing "standards" or whatever, but don't try and tell me that my opinion / premise is invalid or less valid because I'm not an expert (or that I shouldn't argue).

Any reported issue here, in my opinion, constitutes an opinion of the user that the system isn't performing the way that they expect it should. Thus, I'll continue to report things that I feel to be defective, or are at least worthy of someone on the team taking a look at. Should they call it a non-issue, so be it.

**Comment by GITNE** [comment] 2016-11-08 22:42
> Thanks for the enlightening op-ed on web standards.

You welcome, I am glad I could help. :smile:

I am sorry if I have stepped onto your ego. Obviously, we have different views about the purpose of this issue tracker. You seem to assume that this is some sort of social media discussion forum. In my view the issue tracker is more of a tool for filing bugs and glitches. And sure, you are fully entitled to state your opinion on this issue tracker, you may even make **suggestions**, or **voice** your **wishes**, however this is not what you did. You have written about:

> ## Expected behavior
>
> Location search box does not autocorrect, as locations are often not in the English dictionary

“Expected behavior” is neither an opinion nor a suggestion. You have been suggesting that Mapillary developers did not do their homework, which is not true by any means.

Honestly, I do not understand what you may be complaining about because I have been friendly enough (and still are) to explain to you why your initial assumption is flawed and why it is not a bug on the web page. However, you started to argue against it with unsubstantiated claims. Then, I have been even more forthcoming to you by explicitly laying out to you why your initial premise is flawed by providing you with exact substantial reference to relevant standards documentation. Now, while you seem to be out of arguments, you start taking this fact for whatever reason personally, although the only thing you have been treated with was up most patience, clarity, and extensive explanation.

> that the system isn't performing the way that they expect it should.

The thing is that the service **IS** performing the way it is expected. The issue you are reporting here is at *your* end, more specifically your setup.
This is the equivalent of somebody complaining that the map is not rendered in his/her browser because they are using an outdated browser which does not support WebGL. The service is performing as expected on browsers without WebGL support because WebGL is a requirement (a premise) the service has put out.

Please, in order to avoid any confusion in the future, if you are stating your opinion here then please make it clear that it is an opinion. You are entitled to your opinion, you are entitled to state suggestions or wishes but then please make it clear accordingly.

> You're welcome to disagree, citing "standards" or whatever, but don't try and tell me that my opinion / premise is invalid or less valid because I'm not an expert (or that I shouldn't argue).

Please, read carefully. I did not say that your premise is invalid because you may not be an expert but because you jumped into conclusions (in your *opinion* as we now know) which had flawed foundations.

**Comment by jesolem** [comment] 2016-11-08 23:10
@talllguy Thanks for reporting. I see the point and if the fix you link to does indeed solve this then I think it should be implemented. Assigning to @knikel for checking that. 

@GITNE You're overreacting here. We're an inclusive community and encourage anyone to file issues for things they think can improve the experience of Mapillary, whatever the reason for the "fault". (Including that we should support a browser that is outdated, which we probably won't fix). Still, anyone should be free to file the issue, hear an answer from the team, and be met respectfully.

**Comment by GITNE** [comment] 2016-11-08 23:23
Yes, I am sorry if I may have overreacted. I was only trying to explain the technical limitations and shed some light on the technical background.

**Comment by talllguy** [comment] 2016-11-08 23:57
@GITNE I respect your technical expertise and opinions. No ego issues here, and you're right about us disagreeing on the purposes of the :octocat: Github issue platform.

I don't treat this as a social network , just a controlled way to get issues to the right people. I think that Github has been careful and calculated in calling these _issues_ and not refer to this as a bug tracker. My philosophy is that an issue is just an issue, until someone decided to flag it as a bug or something else, thus saying "in my opinion" is redundant. I hope that clears it up ☮️ . 

As for the _Expected Behavior_ bit, just dutifully filling out the issue template here. I wouldn't expect many non-team contributors are privy to the system requirements and thus what would constitute a true failure, but I see your perspective.

PS: @jesolem I don't normally use Safari, but WebGL on Chrome is apparently not supported on this old Mac I have. But that is a separate issue.

**Comment by gyllen** [comment] 2016-11-10 22:05
Thanks guys Im pulling this ticket in internally

**Comment by gyllen** [comment] 2016-11-10 22:05
Reassigning to @nickplesha

**Comment by nickplesha** [comment] 2016-11-15 11:09
@talllguy This should be fixed now, for all search inputs.

**Closed by nickplesha** 2016-11-15 11:09 UTC
Labels: affects-web-viewer, bug, info-tracked
